### ISSUE TITLE
Support `EvaluatableExpression`s

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10027]
### Feature Description:
Implement support for plugins providing evalutable epressions. see https://code.visualstudio.com/api/references/vscode-api#EvaluatableExpression

Currently, the the debugger scans the current line to guess what expressions to evaluate and show in the hover widget. Instead, the debuggers should forward that work to plugins. It may be necessary to keep the current logic as a fallback when no expressions are provided for a particular location.

**Comment by ndoschek** [comment]
I will pick up this issue

**Comment by alvsan09** [comment]
Hi @ndoschek,
I am wondering what the status of your current commit is?
Are you planning to continue with it?

**Comment by ndoschek** [comment]
Hi @alvsan09!
Sorry I was a bit delayed, but I'm planning to complete it this month.

**Comment by ndoschek** [comment]
Awaits uplift of monaco to add the necessary types in the `monaco.languages` namespace.
Please see PR: https://github.com/theia-ide/vscode/pull/1

@tsmaeder @colin-grant-work 
I had a look and noticed the missing types in the `monaco.languages` namespace. After some investigation I found the branch `uplift-monaco-2022-06` on theia's fork of `vscode`.
Is it sufficient to add those types there or would you suggest to add them to `vscode` directly? TIA!

**Comment by colin-grant-work** [comment]
@ndoschek, in general, we avoid modifying the code of VSCode directly, so I would probably avoid the change in https://github.com/theia-ide/vscode/pull/1. I'm also a little bit confused by the code in that PR. It appears that it adds declarations to `monaco.d.ts` for the functions `registerEvaluatableExpressionProvider` and `registerInlineValuesProvider` but doesn't modify the source code to actually provide those functions in the API object? To actually support new `languages` API, changes would be required in the `createMonacoLanguagesAPI` function in `src/vs/editor/standalone/browser/standaloneLanguages.ts`.

I have opened [a PR](https://github.com/eclipse-theia/theia/pull/11331) to uplift our Monaco dependency to VSCode 1.67.2, and I believe that the `EvaluatableExpression` and `EvaluatableExpressionProvider` types are available there - not from the API, but via imports from the source - and it appears that the registration should be possible using the `ILanguageFeaturesService`, which we can access using Monaco's `InstantiationService`:

https://github.com/eclipse-theia/theia/blob/b63943c25d56523bf35204a48528a21908cd9feb/packages/monaco/src/browser/monaco-outline-contribution.ts#L46-L48

https://github.com/eclipse-theia/theia/blob/b63943c25d56523bf35204a48528a21908cd9feb/packages/monaco/src/browser/monaco-outline-contribution.ts#L133

Given that, I would wait until the uplift / rebase your work on the uplift branch, and work from there, rather than modifying the VSCode source.

**Comment by ndoschek** [comment]
Hi @colin-grant-work!
Thanks for your input! I have a WIP branch and I will try your suggested way of using the `ILanguageFeaturesService` in the meantime and I will abandon my PR and wait for the uplift then. Thanks again!
