### ISSUE TITLE
todo: target `electron-rebuild@^3.2.2`

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#10048]
Just a reminder task.

Doing so introduces a new dependency `lzma-native@8` with problematic licenses.

CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23694

**Comment by vince-fugnitto** [comment]
The issue is no longer relevant as we currently support `3.2.7`:

https://github.com/eclipse-theia/theia/blob/78b7f9558bc35c2f0283e098191f1b24af2721e3/dev-packages/application-manager/package.json#L46

https://github.com/eclipse-theia/theia/blob/78b7f9558bc35c2f0283e098191f1b24af2721e3/yarn.lock#L4956-L4957
