### ISSUE TITLE
Tree View vscode extension issue - path separator encodes to %5c (back slash) in the TreeItem.iconPath property

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#10105]
### Bug Description:
Hi,
The iconPath (dark & light) property in the vscode.TreeItem object is not working correctly in Theia.
I set it as in the documentation: path.join(__dirname, '..', 'resources', 'light', 'icon.svg'), will not find the resoiurce file (got 400), since it convertes the last 2 folder separator to a back slash in the url: url/resources\light\icon.svg.
If I move the svg icon 2 levels up (to the root of the plugin), it works correctly:  path.join(__dirname, '..', 'icon.svg') -->  url/icon.svg

### Steps to Reproduce:

1. Add vscode extension (vsix) that uses the Tree View API, and extend the vscode.TreeItem object
2. e.g set the iconPath{ light: path.join(__dirname, '..', 'resources', 'light', 'icon.svg'), ... }
3. the icon will not be rendered, insrtead and error in the devtools network tab: status 400:
   it is encoded to: <url>/resources\light\icon.svg
  actually in the network is looks like this: url/resources%5clight%5cicon.svg

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.16

**Comment by msujew** [comment]
@safisa I can't reproduce this issue using the [tree-view-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample) and its json view, neither on Windows nor Linux. It follows the same pattern (using `path.join`) and should exhibit the same issue. Perhaps this is already fixed in 1.17.2? Do you mind retesting?

Also, if the issue still persists and you're not able to reproduce it using the tree-view-sample, do you mind providing us a minimal reproducible example in the form of a vscode extension?

**Comment by safisa** [comment]
@vince-fugnitto Next week I will try to reproduce it again and update the ticket.
Thanks.

**Comment by safisa** [comment]
I could not reproduce this issue. I am closing the ticket.
