### ISSUE TITLE
I can't display the sidebar image using Theia

### ISSUE THREAD

**Issue by miharbii** [eclipse-theia/theia#10169]
### Steps to Reproduce:

1. I created a sidebar on the vs extension code and everything worked normally 
2. I tried to use the same code with Theia but the svg image did not display. 

### Additional Information

- Operating System: linux
- Theia Version: 1.17.2

**Comment by msujew** [comment]
Hi @miharbii, are you able to provide a bit more information on that?

For example, does Theia display an error message in the console, when trying to load the svg? Or perhaps a reproducible example extension, so we can better identify what's wrong?

**Comment by vince-fugnitto** [comment]
@miharbii any update? It is likely that `master` has a fix for the issue.

**Comment by the-architect** [comment]
Do you have a publisher set in your package.json? 
If you inspect the activity element with the image, does the path contain "undefined" at some point? I ran into this issue yesterday too.

**Comment by vince-fugnitto** [comment]
Closing the issue due to inactivity, the last two questions were unanswered https://github.com/eclipse-theia/theia/issues/10169#issuecomment-945979647, https://github.com/eclipse-theia/theia/issues/10169#issuecomment-966514115.
If you still experience issues please do not hesitate to comment again :+1:
