### ISSUE TITLE
scroll jumps back to selected tree item when expanding/collapsing other tree item

### ISSUE THREAD

**Issue by MoHcmp** [eclipse-theia/theia#10280]
### Bug Description:
Inside vscode tree view plugin when selected tree item is not visible and user tries to expand/collapse node scroll jumps back to selected item which makes tree view unusable.

![bug](https://user-images.githubusercontent.com/24322410/137488802-440d9a08-247a-4f95-8000-bfaae491a600.gif)

### Steps to Reproduce:

1. Create simple vs code plugin with tree view
2. Open tree view
3. Select some item
4. Scroll tree to make selected item out of sight
5. Expand or collapse node using expand/collapse icon

Scroll will jump to selected item. Expected behaviour: scroll will not jump. Node will collapse/expand.

### Additional Information

- Operating System: windows 10
- Theia Version: 1.16

**Comment by colin-grant-work** [comment]
> I believe it may be similar to #8101 and a general issue with our virtualized trees.

In the case of #8101, part of the problem is that the VSX tree is _not_ virtualized, in that its props specify `virtualized: false`.

In this case , I think the culprit is #9583 and the `expandOnlyOnExpansionToggleClick` flag. In trees using that flag, `this.updateScrollToRow()` is called at the end of `doUpdateRows()` when expansion changes, but since expansion doesn't trigger a selection change, the `scrollToRow` is calculated as being the selected row.
