### ISSUE TITLE
Strange problem with in conditional operator

### ISSUE THREAD

**Issue by bd82** [eclipse-theia/theia#10552]
I have a strange problem where I am trying to test the support for the "when clause in conditional operator"
using this small sample I've created:
- https://github.com/bd82/vscode-extension-samples/tree/main/in-conditional-operator-sample
  - The example includes documentation and relevant scripts to create a vsix to deploy.

The **strangeness** of the problem is that this works successfully when I build Theia browser example on this repo. (master / 1.20 / 1.19).
But does not work on both:
- gitpod (does gitpod still use Theia?).
- SAP BAS (uses Theia 1.19 when tested).

Does anyone have any thoughts on what could be causing this issue?
Could a 3rd party extension somehow break the custom context support?

Thanks in advance.
Shahar.

**Comment by bd82** [comment]
Could it be that the `uri.fsPath` value works on Windows systems in combination with the setContext command and when operators.

- https://github.com/bd82/vscode-extension-samples/blob/main/in-conditional-operator-sample/src/contexts.ts#L34

But not on unix systems?

**Comment by ChayaLau** [comment]
> * gitpod (does gitpod still use Theia?).

gitpod is using vscode, but when we run theia on gitpod the extension also does not work

**Comment by colin-grant-work** [comment]
The menu items are appearing correctly in my Linux environment in both the Electron application and in the browser. Changes to the `package.json` files are also successfully picked up.

**Comment by msujew** [comment]
@colin-grant-work Interestingly enough, it works correctly on Ubuntu (at least in my VM):

![image](https://user-images.githubusercontent.com/4377073/146613838-cd553599-016a-4deb-8749-69b5d86aa3c3.png)

But not on Windows (Electron & Browser):

![image](https://user-images.githubusercontent.com/4377073/146613885-8d5679c5-a7bf-4a27-8d6a-2e157a01b2fd.png)

I assume that @bd82 is correct in his assumption that it's somehow related to windows file path calculation of the `vscode-uri` package.

**Comment by tsmaeder** [comment]
There is an open PR related to uri's and windows: https://github.com/eclipse-theia/theia/pull/10434 Maybe it's related.

**Comment by bd82** [comment]
Thanks everyone for the feedback.
I will continue investigating it tomorrow and update if I have any new information

**Comment by ChayaLau** [comment]
> There is an open PR related to uri's and windows: #10434 Maybe it's related.

hi, 
I checked this fix, but it wasn't enough.
we needed the mentioned fix + additional fix when setting the resourcePath variable :
`this.resourcePath.set(resourceUri && resourceUri['codeUri'].path);` instead of the fsPath.
it seems maybe the fsPath is also cropped somehow, that is why i used the path.
can i upload a PR for that ? or will it be bad ? do you have a better idea or a way to fix the fsPath too?

**Comment by msujew** [comment]
@ChayaLau Since the actual context key evaluation happens inside of monaco code, we would have to wrangle our passed resource paths into a normalized format which is exactly the same across all OS. So relying on `URI.fsPath` is out of the question, since it's transformation is working differently depending on the OS.

Your approach using `URI.path` seems to work fine, however It relies on extension developers using the provided API purposefully wrong. Extension developers should be using `URI.fsPath` for vscode, but for Theia they would have to use `URI.path` instead. This is quite problematic in my opinion, but I don't really see another way to deal with this. It seems like the vscode team also didn't come up with a solution so far for this issue (or they don't know about it) since vscode (web) also exhibits the same issue as Theia.

**Comment by msujew** [comment]
@ChayaLau Actually, I thought about this issue again just now:

In theory, it would be best if the frontend code would somehow always replicate the behavior of the backend `URI.fsPath` implementation, so they always stay aligned. This could be done by replicating the `URI.fsPath` behavior for all OS's in Theia and using the `ApplicationServergetBackendOS()` method to switch which implementation to use.

I think that would be the best solution (although I haven't tested whether it actually works as expected), since it plays well with how vscode extensions use the `URI.fsPath` method. I would gladly look into a PR, if you want to contribute a fix for this.

**Comment by bd82** [comment]
- Does it make sense that the sample extension works for some **only** on windows and for others **only** on unix?
- If I compute the absolute paths myself could I make it work on all envs?
  - Do you know what is the problem with the paths?

**Comment by msujew** [comment]
> Does it make sense that the sample extension works for some only on windows and for others only on unix?

@bd82 It seems like I didn't test this correctly on Windows+Electron. It does work there correctly. In my tests the issue only occurs when the backend and frontend OS are using a different file path schema, like hosting Theia on Ubuntu and loading the frontend on Windows.

**Comment by bd82** [comment]
> In my tests the issue only occurs when the backend and frontend OS are using a different file path schema, like hosting Theia on Ubuntu and loading the frontend on Windows. My recommended solution addresses this mix & match issue for different OS's.

Thanks for the additional info @msujew 

Is there a **workaround** possible from a VSCode **extension** developer's side?
- I am assuming that someone writing a **VSCode** Ext does not have access to a **Theia** API (`ApplicationServer.getBackendOS()`)...

Is there some other manner for a VSCode ext developer to figure out which path (separator?) formats they should use
with `setContext` for the in operator to be evaluated correctly ?
and how would it even work?
- e.g if a path in unix is `/home/user/projects/foo` what is the equivalent windows path? 
  - as there is no drive letter...

Or am I confusing things here?

**Comment by msujew** [comment]
> Is there a workaround possible from a VSCode extension developer's side?

> Is there some other manner for a VSCode ext developer to figure out which path (separator?) formats they should use
with setContext for the in operator to be evaluated correctly ?

I don't think so. The extension runs in the backend and has no idea which frontend is actually connected to it, so it can't possibly decide whether to store the windows or unix path in the context key.

> I am assuming that someone writing a VSCode Ext does not have access to a Theia API

Right, this has to be fixed in Theia itself.

> e.g if a path in unix is /home/user/projects/foo what is the equivalent windows path? 

Good question, I just checked, the `vscode-uri` library will transform that into `\\home\user\projects\foo` on the frontend, which is questionable at best, but I guess it's better than just prepending a random drive letter.

I'll provide a fix for this when I'm back from vacation in January, if nobody else does it before me 👍

**Comment by bd82** [comment]
@msujew again thanks for the detailed replies 😄 

What if the VSCode Ext would **double** all paths in the context? so for `/home/user/projects/foo`, **both**:
- `/home/user/projects/foo`
- `\\home\user\projects\foo`

Would be added via `setContext`.

**Would this flow now work with either a Windows or Unix frontend?**
- (The backend in my productive case is always unix like).

**Comment by msujew** [comment]
> What if the VSCode Ext would double all paths in the context?

@bd82 Oh that's a good idea. I think that should work, yes.

**Comment by bd82** [comment]
Strangly enough, replacing the forward slashes with backslashes (without **double slashes**) is what finally worked in our (productive) scenario.
