### ISSUE TITLE
Issue in the new context menu in Theia 1.21

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#10568]
### Bug Description:
Hi,
In the last Theia 1.21 there is an issue in the context menu over activity bar icons, and on the outline too. It includes some new commands that are not relevant to this context, they should appear only on editors' tabs.

Thanks

### Steps to Reproduce:

1. open context menu on the activity bar icons
2. you will see the new commands added in 1.21, that are not relevant in this context (see attached image), like copy path, close saved...
![Screen Shot 2021-12-20 at 11 33 53](https://user-images.githubusercontent.com/10339204/146745804-37962569-54f6-4836-93e5-0c0a0576394f.png)

![Screen Shot 2021-12-20 at 11 56 38](https://user-images.githubusercontent.com/10339204/146748716-5b10f9eb-36e1-403e-a4c0-4a494503f542.png)

### Additional Information

- Operating System: Win 10
- Theia Version: latest 1.21

**Comment by colin-grant-work** [comment]
@safisa, I'm unable to reproduce your screen shots. For example, at v1.21.0 when right-clicking on the Search-in-Workspace widget's icon, I get this context menu:  

![image](https://user-images.githubusercontent.com/62660806/147010983-1b33d5d3-728b-4436-9a7d-3373f3d09913.png)

And on the outline view:

![image](https://user-images.githubusercontent.com/62660806/147010999-66601b3b-2670-4932-9358-1f1743cb3355.png)

Removing the `Copy Path` and `Copy Relative Path` commands from the context menu when they didn't belong required some modifications to the `ApplicationShell` and [`TabBar`](https://github.com/eclipse-theia/theia/pull/10394/files#diff-bb62d77ca908eb463355fefc1920763f61f7880c48235f559da8d9cd91f8e753) code. If you're working on a downstream application that overrides either of those classes, it's possible that those changes weren't picked up in your application? Or are you able to reproduce what you showed in Theia itself?

**Comment by safisa** [comment]
Hi,
Please try first to open an editor tab in the main panel, then right-click on the tab (file name) to see the menu above with all the new options, then right-click on any of the activity bar icons you will see these commands there too.
So, I think the issue happens after first populating this menu with these new commands and then in the activity bar the  commands will still be visible.

**Comment by colin-grant-work** [comment]
@safisa, the items present in a context menu are recalculated every time the context menu is opened, so I don't think that there's a problem with caching. I get the same results as the screen shots above with or without an editor open:

Open editor:

![image](https://user-images.githubusercontent.com/62660806/147126510-7ed1649a-cbc2-48e4-9e32-57e87266c273.png)

Check search context menu:

![image](https://user-images.githubusercontent.com/62660806/147126593-6a809364-c8bf-4dff-85bb-bf9ee760c9e3.png)

Check Outline context menu:

![image](https://user-images.githubusercontent.com/62660806/147126692-599b36bf-57df-491d-b487-aa4f20e42e5c.png)

As I said, there were a number of changes involved in adding those commands to the context menu and in filtering them out when they aren't necessary. If a downstream application overrides any of those changes, then the necessary code may not be carried over from Theia. Since those commands depend on the global selection state, and changes were made in the tab bar code to enable changes to the global selection state depending on the target of a context menu event, that's the most likely point of failure. Another possibility is [this binding](https://github.com/eclipse-theia/theia/blob/17b419fdf0d1015f2269ffcb64a095b305a8ec2d/packages/core/src/browser/frontend-application-module.ts#L168-L174), which, if overridden, would prevent the `TabBarRenderer` from having access to the selection service to make the necessary changes to the global state.

**Comment by safisa** [comment]
Hi @colin-grant-work,
The issue was as you mentioned above, I am using a CustomTabBarRenderer, and therefore I have this binding:

```
rebind(TabBarRendererFactory).toFactory(context => () => {
        const contextMenuRenderer = context.container.get<ContextMenuRenderer>(ContextMenuRenderer);
        const decoratorService = context.container.get<TabBarDecoratorService>(TabBarDecoratorService);
        const iconThemeService = context.container.get<IconThemeService>(IconThemeService);
        return new CustomTabBarRenderer(contextMenuRenderer, decoratorService, iconThemeService);
    });
```

Once I added this line, the problem was fixed:
const selectionService = container.get(SelectionService);

Thanks a lot
