### ISSUE TITLE
'CUT' not work in context menu 

### ISSUE THREAD

**Issue by shuyaqian** [eclipse-theia/theia#10571]
### Steps to Reproduce:
1.  select something
2.  click Edit—>Cut
3.  `cut` not work

### Additional Information

- Operating System: linux
- Theia Version: 1.19.0

**Comment by msujew** [comment]
@shuyaqian I am not able to reproduce this issue on the current `master`. Do you mind retesting it there?

**Comment by colin-grant-work** [comment]
I believe it's a similar issue to #10540. Basically, it goes back to #9830: that PR introduced conditions under which what was formerly not a context menu got to be rendered as a context menu. That means that commands that formerly didn't receive the default Anchor argument associated with context menus are now receiving it, and since command handlers receive `any[]` as their args and so can assert that they'll receive anything at all, very few commands have effective type checking.

There are a few options:
 - Remove the anchor argument for all context menus, as #10540 originally tried to do.
 - Implement type checks, as we've encouraged in #10540
 - Change the rendering strategy for the menu when `window.menuBarVisibility` is set to `compact` so that it does not behave like a context menu and pass the anchor argument as the default.

I think the last is actually the correct move: it isn't really a context menu, and it shouldn't behave like one. That would fix all affected handlers without us having to identify them one by one.

**Comment by colin-grant-work** [comment]
With a bit of checking, this turns out not to have to do with the context menu anchor issue at all, but with a failure of the menu-opening machinery of the new compact menu widget to restore focus to the previous context when the user makes a selection. Then, since the context is not the text input, the cut command has no effect.
