### ISSUE TITLE
Add `tests` namespace from VSCode API

### ISSUE THREAD

**Issue by sgraband** [eclipse-theia/theia#10669]
### Feature Description:
Add function from the `tests` namespace:

- [ ] createTestController

Add required variables, functions and fields from `root` namespace:

- [ ] TestController
- [ ] TestItem
- [ ] TestItemCollection
- [ ] TestMessage
- [ ] TestRun
- [ ] TestRunProfile
- [ ] TestRunProfileKind
- [ ] TestRunRequest
- [ ] TestTag

VSCode API for reference: https://code.visualstudio.com/api/references/vscode-api#tests.

**Comment by fyudanov** [comment]
Would be nice to have, e.g. for integrating https://github.com/robocorp/robotframework-lsp with Test Explorer view in Theia.

**Comment by planger** [comment]
Note that the test API [has been stubbed](https://github.com/eclipse-theia/theia/pull/11717) for now. So extensions using this API aren't blocked from running, but usages of the test API won't have any effect.

**Comment by KevinClapperton** [comment]
Hello, I speak on behalf of the student project team from Polytechnique Montreal (Kevin, Théo, Mathieu and Zakaria). This is our first time contributing and we would like to work on this API. We are still going through some tutorials and documentation to make sure we understand how to implement this feature (we might have a slow start). 

Here is what we are doing right now in order to understand how to implement the Test API: 
- Reading [Plugin-API.md](https://github.com/eclipse-theia/theia/blob/master/doc/Plugin-API.md) and [how to add the test namespace](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/doc/how-to-add-new-plugin-namespace.md) 
- Looking how the [Test API was stubbed](https://github.com/eclipse-theia/theia/pull/11717) 
- Looking how other VSCode API are implemented (path: [theia/packages/plugin-ext/src/plugin/](https://github.com/eclipse-theia/theia/tree/master/packages/plugin-ext/src/plugin))
- Checking [VSCode extension sample for the Test API](https://github.com/microsoft/vscode-extension-samples/blob/main/test-provider-sample/src/extension.ts) and [the guide](https://code.visualstudio.com/api/extension-guides/testing) plus the [official documentation](https://code.visualstudio.com/api/references/vscode-api#tests)
- Looking at a [partial implementation of the Test API in Haxe](https://github.com/vshaxe/vscode-extern/tree/master/src/vscode) 

Question: 
- Is there something we should be aware that is part of the fact that Theia can be Desktop or Remote? We saw some functions using remote procedure call (RPC). Is that something we will have to use in order to implement the Test API? 

Are we missing something? Is there some documentation or examples we should read?

**Comment by D-Zaq** [comment]
Hi, are the test [coverage](https://github.com/microsoft/vscode/blob/1.72.2/src/vscode-dts/vscode.proposed.testCoverage.d.ts) and [observer ](https://github.com/microsoft/vscode/blob/1.72.2/src/vscode-dts/vscode.proposed.testObserver.d.ts)part not to be considered in the implementation based on this issue as the functions like `runTests`, `createTestObserver` and `onDidChangeTestResults` that are part of the tests namespace and the different variables and fields that come along were not included in the description and the [stubbed tests API](https://github.com/eclipse-theia/theia/pull/11717/commits/d1451f213bd6711576310c6088295acd29baa9ba#diff-039a4c69e33f1a425bb709ef2f423d6152fc269f759c70130b69980f4d883c10)

**Comment by sgraband** [comment]
The functions you are listed are part of vscodes **proposed** api. If i rememeber correctly proposed api is not required to be compatible. @planger is this correct?

**Comment by KevinClapperton** [comment]
> Hi, are the test [coverage](https://github.com/microsoft/vscode/blob/1.72.2/src/vscode-dts/vscode.proposed.testCoverage.d.ts) and [observer ](https://github.com/microsoft/vscode/blob/1.72.2/src/vscode-dts/vscode.proposed.testObserver.d.ts)part not to be considered in the implementation based on this issue as the functions like `runTests`, `createTestObserver` and `onDidChangeTestResults` that are part of the tests namespace and the different variables and fields that come along were not included in the description and the [stubbed tests API](https://github.com/eclipse-theia/theia/pull/11717/commits/d1451f213bd6711576310c6088295acd29baa9ba#diff-039a4c69e33f1a425bb709ef2f423d6152fc269f759c70130b69980f4d883c10)

We talked about this in today's DevMeeting. From what I understood, if the Test API doesn't make heavy use  of the proposed API, then there is no need to implement it.

**Comment by KevinClapperton** [comment]
I wanted to add some information of something that we found during the last month. There are some UI implementation to be done to make this API complete. There is something called `testingDecoration` that are the little play buttons that should appear in the editor's gutter when a test is detected. Here is more information on the UI implementations: 

- testingDecoration in the `common` folder: https://github.com/microsoft/vscode/blob/1.72.2/src/vs/workbench/contrib/testing/common/testingDecorations.ts
- Some more files on the UI implementation in the `browser` folder : https://github.com/microsoft/vscode/tree/1.72.2/src/vs/workbench/contrib/testing/browser 
- Video showing a example of what it should look like: https://youtu.be/AulgIP9P8Cw?t=60 

When we first looked at this issue we didn't think there was any UI implementation to be migrated. Is this part of the issue?

**Comment by KevinClapperton** [comment]
Here is a condensed report of known issues and what is/isn't implemented in the [current PR](https://github.com/eclipse-theia/theia/pull/12175) : 

**Known issues**: 
- No known issues in Plugin Host code 
- The Main Browser code of the Test API doesn't use Inversify and needs a lot of changes to work without failing in runtime. See [this comment](https://github.com/eclipse-theia/theia/pull/12175#issuecomment-1498172220) 

**Implemented**: 
- Testing Workspace
   - `packages/testing/src/common` folder with the code necessary for Plugin Host (contains a lot of code necessary for Main Browser as well) 
   - This workspace contains code from VS Code found in the following folders: 
      - `vscode/src/vs/workbench/contrib/testing/common` 
      - `vscode/src/vs/base/common`
      - `vscode/src/vs/editor/core`
   - Imported interfaces, classes,  variables, functions and fields: 
      - TestController (found in `tests.ts` implemented at run-time in function `TestingExtImpl::createTestController`)
      - TestItem (found in `test-items.ts` as `TestItemImpl`) 
      - TestItemCollection (found in `test-item-collection.ts as `TestItemCollection`)
      - TestMessage (already found in `types-impl.ts`)
      - TestRunProfile (found in `tests.ts` as `TestRunProfileImpl`) 
      - TestRunProfileKind (already found in `types-impl.ts`) 
- Plugin Host logic in tests.ts (the equivalent of `ExtHostTesting.ts` in vscode)
    - Imported `ExtHostTesting` from vscode now called `TestingExtImpl`

**Note**: The following diagram shows the files that were added (green) or modified (in grey) to make Plugin Host work: 
![file diagram](https://user-images.githubusercontent.com/43681350/234694445-c2d581d0-ed96-4b72-b978-b802fee402d0.png)

**Not implemented**: 
- Main browser 
- UI and UI logic 
- TestRun 
- TestRunRequest 
- TestTag 

**Note**: The following diagram shows the files from VS Code that we think should be imported for the Main Browser and UI to work (other files might be missing) : 
![file-diagram-missing-files](https://user-images.githubusercontent.com/43681350/234700599-b402708e-c721-48ab-97f0-0e8bfbc2c990.png).

**Comment by KevinClapperton** [comment]
Feel free to ask any questions about the report or the code before the next meeting on May 2th. That way we will be able to answer them in more detail at the meeting.

**Comment by KevinClapperton** [comment]
Here is a simple extension that pokes the functions `createTestController`, `createRunProfile`, `createTestItem` and `createTestRun` of the Test API. It returns a notification for each of the functions with "SUCCESS" or "FAIL" with details if the functions throw an error. 

vsix file:  [test-api-functional-test-0.0.2.zip](https://github.com/eclipse-theia/theia/files/11446779/test-api-functional-test-0.0.2.zip)
Source code: https://github.com/KevinClapperton/Test-API-functional-test

Once the extension is installed in Theia, execute the command `Test API: Run All Test` in the command palette to call the Test API functions.

**Comment by tsmaeder** [comment]
I'm thinking about what UI we would have to have to implement this API:

1. Test Explorer View
Shows all tests in a tree structure and has toolbar/drop downs to run test, goto location, hide/show, etc. Shows failures, errors, etc.
2. Test Markers in the Editor
You can run Editors from the marker 
3. Test output view
VS Code uses a terminal widget. Not sure that would work for us, based on our implementation
4. Various commands ("configure test profile", "refresh", etc.)
5. Showing errors in the editor in an overlay

In a first step, we could leave out the marker support, since that duplicates functionality from the Test Explorer view. The "peek error" support in VS Code could maybe be replaced by a hover on failed tests. We could also kind of ignore "continuous run" capabilities by always requesting "continuous=false" when running tests. Any "proposed" functionality like coverage or TestObserver could be safely stubbed.

**Comment by tsmaeder** [comment]
So a preliminary plan might be:

1. Define a TestService package that allows for dynamic "TestController" contributions
2. Make a super-simple test contribution
3. Create a simple Test Explorer View (Tree View) It needs to be able to 
   * show tests from contributions
   * refresh
   * show test status
   * show test failure messages
   * run tests
   * debug tests
5. Implement test output
6. Implement the "PluginTestController" contributions in the "plugin-ext" package (based on the existing PR).

**Comment by tsmaeder** [comment]
Some further notes...

1. The test API proper is pretty much a write-only API: there is no way for an extension to obtain references to any test controllers the extension did not create itself. The extension adds things (profiles, test runs, output messages) and writes them to the API, but it can mostly not read back the results of those writes (TestItemCollection being the exception). 
2. The Implementation in VS Code seems to employ a tree-delta mechanism to propagate time-batched updates to the set of tree items in a controller. That makes sense, since discovering tests in a workspace (or refreshing a TestItem node) will likely generate many updates in a short time.
3. The proposed TestObserver API allows to observe tests and test results in the system. The API gives you access to `TestItem` instances, and you would think from the API that you can manipulate these, but in fact, they are effectively readonly. That makes sense, since an extension cannot be expected to run a test it did not create through its controller.
4. Since tests may by created in different plugin hosts (e.g. front-end and back-end), the set of observed tests is non-local: i.e. only the front end can know the set of tests. That means the tests in the TestObserver API is distinct from the set of test in the test API proper. We can therefore reasonably start without the TestObserver API.

**Comment by tsmaeder** [comment]
Note that propagating test run results is also something that might happen at a fast pace an profit from batching. We have to keep in mind that we might have to match a particular result to the location in the test item tree and design data structures accordingly.
