### ISSUE TITLE
Ctrl+R in bash terminal does not activate 'reverse-i-search'

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#10701]
### Bug Description:
When using a bash terminal in Theia, the keybinding sequence `ctrl+r` does not activate the 'reverse-i-search' functionality. This can be inconvenient for users who heavily rely on this bash functionality.

### Steps to Reproduce:

1. Open a terminal bash terminal on your machine outside Theia and press `ctrl+r` to activate reverse-i-search
2. Do the same thing in Theia and observe that it doesn't seem to work

### Additional Information

- Operating System:
- Linux
- Theia Version:
- Master

**Comment by vince-fugnitto** [comment]
@kenneth-marut-work it seems to work fine in the browser, but for electron it will reload the application, likely since there is a keybinding conflict, or it hits some native electron reload:

https://github.com/eclipse-theia/theia/blob/a3b025a206b790005914647311b22a2dcf63c574/packages/core/src/electron-browser/menu/electron-menu-contribution.ts#L317-L318

_browser_:

https://user-images.githubusercontent.com/40359487/152183826-84d08b84-c3a6-4912-be56-0123a1ab6ed0.mp4

**Comment by colin-grant-work** [comment]
I believe the problem is the global shortcut coming in from `ElectronMainApplication`:

https://github.com/eclipse-theia/theia/blob/a3b025a206b790005914647311b22a2dcf63c574/packages/core/src/electron-main/electron-main-application.ts#L451-L466

If I comment out those lines, I get correct behavior in the terminal, and outside the terminal, I still get a refresh, because of the command registration that @vince-fugnitto pointed to. Perhaps we don't need the global shortcut if we handle it internally?
