### ISSUE TITLE
Display 'ctrlcmd' keybindings as 'ctrl' or 'cmd' depending on OS

### ISSUE THREAD

**Issue by gbodeen** [eclipse-theia/theia#10789]
### Feature Description:
Some keyboard shortcuts are set to `ctrlcmd`, which equals Cmd on Mac and Ctrl on other systems.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/20653241/155358249-84c2acbd-371e-4fc8-94d7-99cf123ba739.png)

The meaning is not completely obvious, so the display could be improved. Instead of displaying `ctrlcmd` as above, Theia should detect whether the system is Mac or other, and display `cmd` or `ctrl` as suited to the system.

**Comment by colin-grant-work** [comment]
I think a utility for this already exists and is in use in menu system, since there we do show only the active binding according to OS.

**Comment by vince-fugnitto** [comment]
I also opened the following issue in the past, rather than the string representation we do like vscode and display the actual keys like the menus: https://github.com/eclipse-theia/theia/issues/5377.

![image](https://user-images.githubusercontent.com/40359487/155382943-2ea87b68-82ad-4ba5-915d-323ddfc043b2.png)
