### ISSUE TITLE
Problems with `window.titleBarStyle` on Linux systems

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#10843]
> Starting the application on Ubuntu I am getting some odd behavior with my app (no electron top-menu):
> 
> ![image](https://user-images.githubusercontent.com/40359487/132012898-ca3df31e-2e41-49ad-8ad4-50b3c17f3fc9.png)

I get the same problem now, when I try upgrade theia to 1.23.0. from 1.18.0. 

After build the electron and start, I got it. No titlebar & top menu, only the content be display.

And I try to set window: Title bar style custom -> native, it will be have a windows tile bar. (other: The restart window look like do not show always.) 

So, the window title bar style be default custom in new version, but it can't work in my PC, and then build electron installer running in other PC still so.

And, I try to delete .theia/ in user folder, still so.
And, I try to delete electron/ in AppData folder, still so.

I am using:
node.js: 14.18.1
typescript: 4.5.5

_Originally posted by @orange-pig in https://github.com/eclipse-theia/theia/issues/10044#issuecomment-1058908644_

**Comment by colin-grant-work** [comment]
@orange-pig, I have created an issue to track the problem you've encountered, and I'll look into reproducing it

**Comment by orange-pig** [comment]
By debug, it look like that because a sync process problem in start, the ElectronMenuContribution.onStart() is not executed, the quetions has happening. But I don't have hard evidence yet, then will to trace it.

**Comment by orange-pig** [comment]
It turns out my guess above was wrong in the last commit, it's just my debugging phenomenon.

I guess I found the reason of the bug, the real reason is 133 line in the file 'core/src/eelectron-browser/menu/electron-menu-contribution.ts'

`
130        electron.ipcRenderer.on(TitleBarStyleAtStartup, (_event, style: string) => {
131            this.titleBarStyle = style;
132            this.preferenceService.ready.then(() => {
                      // Note: there is the preference ready, the 'titleBarStyle' value is 'custom'.
                      // I think there need a line with new preference value .
                      //  this.setMenu(app);
133                this.preferenceService.set('window.titleBarStyle', this.titleBarStyle, PreferenceScope.User);
134            });
135        });
136        electron.ipcRenderer.send(RequestTitleBarStyle);
137        this.preferenceService.ready.then(() => {
                  // Note: there is the preference look like default, the 'titleBarStyle' value is 'classic'.
138            this.setMenu(app);
139            electronRemote.getCurrentWindow().setMenuBarVisibility(['classic','visible'].includes(this.preferenceService.get('window.menuBarVisibility', 'classic')));
140        });
`

**Comment by msujew** [comment]
@orange-pig Thanks for tracking this down. I created a fix for this in https://github.com/eclipse-theia/theia/pull/10847, do you mind trying it out?

**Comment by orange-pig** [comment]
@msujew Good, It works fine.
