### ISSUE TITLE
theming: set `theia-file-icons` as the default file icon theme

### ISSUE THREAD

**Issue by Tpuljak** [eclipse-theia/theia#11020]
### Bug Description:
After the last update (1.24) it seems that theia file icons are not set by default. No file icons are displayed by default.

### Steps to Reproduce:

1. Update theia to 1.24
2. Run

### Additional Information
Before the update, theia file icons were default and now this preference has to be applied to make them default:

```json
          "workbench.iconTheme": "theia-file-icons"
```

- Operating System: MacOS
- Theia Version: 1.24.0

**Comment by vince-fugnitto** [comment]
@Tpuljak thank you for the discussion, but it is not a bug, it was a decision made a while ago to use `'none'` as a theme so that applications would be more inclined to set their own. The only thing that was changed in `1.24.0` was to fix a bug on startup where the default was not being applied properly (which is why you see the `'none'` apply).

**Comment by Tpuljak** [comment]
Thanks for the reply @vince-fugnitto. 
If I'm a factor in the decision, I vote to have theia icons defaulted 😅.

Especially because newer developers might struggle to find how to change the default.
