### ISSUE TITLE
nls: missing or incorrect localizations

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11040]
#### Bug Description:

I noticed in a couple of instances that **localizations** are incorrect, either casing or simply completely missing despite being part of [vscode-loc](https://github.com/microsoft/vscode-loc).

#### Steps to Reproduce:

1. start the application
2. install the [french language pack](https://open-vsx.org/extension/MS-CEINTL/vscode-language-pack-fr)
3. execute the command `configure display language`, and select `fr` (french)
4. restart the application using the prompt
5. on restart notice that the `file` (fichier) menu is not capitalized, and notice that submenu items are missing such as `open file...`

**Comment by msujew** [comment]
I believe the `file/fichier` issue is a consequence of https://github.com/eclipse-theia/theia/pull/10946, where I've normalized all strings so that the translations are independent of any capitalization. We should probably use a more "fail-safe" approach there.

Regarding `Open file...`: It seems like I forgot to add the `nls.localizeByDefault` call :)

https://github.com/eclipse-theia/theia/blob/1972f21c93e510dcff3957fdf9f9c01556bc28ca/packages/workspace/src/browser/workspace-commands.ts#L68
