### ISSUE TITLE
files.autoSave doesn't accept "on"

### ISSUE THREAD

**Issue by Tpuljak** [eclipse-theia/theia#11051]
### Bug Description:
In the latest release notes for 1.24 it says that the `files.autoSave` preference can take "on" as a value but that doesn't seem to be the case.

From the release notes:
```
editor.autoSave preference renamed files.autoSave and accepts on, off, afterDelay, onFocusChange. Use !== 'off' to check for any active state.
```

From the editor dropdown:
<img width="398" alt="Screenshot 2022-04-21 at 13 28 55" src="https://user-images.githubusercontent.com/26512078/164449051-51bd600f-f674-422b-b901-416b2309a0da.png">

### Steps to Reproduce:

1. Open the IDE at 1.24
2. Check Files Auto Save preference dropdown values

### Additional Information
I assume that `afterDelay` is supposed to be the equal to `on` in the previous release.

- Operating System: MacOS
- Theia Version: 1.24.0

**Comment by msujew** [comment]
@Tpuljak I believe that's an error in the release notes. We had to align to VSCode's usage of the auto save preference, since we updated our version of Monaco. It does not use `on` anymore, but `afterDelay`, `onFocusChange` and `onWindowChange` instead. However, all of them are implemented the same (i.e. `off` actually turns the auto save feature off, while the others save automatically after a short delay).

@colin-grant-work Can you confirm that?

**Comment by colin-grant-work** [comment]
@msujew, correct. Apologies for the error in the release notes. It was supposed to be that it no longer accepts on, but now accepts the options you described.
