### ISSUE TITLE
Notebooks in VSCode VSIX to be stubbed out

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse-theia/theia#11100]
### Bug Description:
The Notebook API is blocking some modern python plug-ins from being compatible with Theia, as well as Jupyter notebooks. This blocks off the AI/ML  crowd from using Theia. A stop-gap solution would be to stub out the APIs at first and see which ones need fixing next.

**Comment by JonasHelming** [comment]
One thing we would need to think about is how to communicate that this is stubbed. Otherwise I am in full favor of stubbing it for now. @planger

**Comment by planger** [comment]
Right, stubbing out certain API to make extensions at least work with the other API that is fully supported would certainly help in many cases. However, if something is just stubbed, I think we should make _very_ clear that it isn't "functionally" supported.

I would maybe suggest to enhance the vscode-theia-comparator [`info.yml`](https://github.com/eclipse-theia/vscode-theia-comparator/blob/master/conf/infos.yml), allowing to mark namespaces/types specifically as stubbed, so that they show up as warning (orange), meaning that the types are available but actually not functional. WDYT?

**Comment by JonasHelming** [comment]
sound like a good idea to me!

**Comment by vince-fugnitto** [comment]
Closing in favor of #11786.
