### ISSUE TITLE
Inappropriate translation

### ISSUE THREAD

**Issue by meng-jpg** [eclipse-theia/theia#11104]
### Bug Description:
Location: packages/core/i18n/nls.zh-cn.json/theia/debug/threads
Maybe "线程" is better than "缝纫机".

### Additional Information

- Theia Version: theia-master

**Comment by msujew** [comment]
Hi @meng-jpg,

thanks, the translations are done using a machine translation API and since we don't have any Chinese native speakers on the dev-team, we have a hard time correcting incorrect translations. Looking at the back-translation of these terms I agree that "线程" is likely the better translation.

Are you interested in contributing the change yourself?

**Comment by meng-jpg** [comment]
Hi @msujew,

I'm glad you can accept this proposal, but I'm sorry I'm not interested in contributing the change.
