### ISSUE TITLE
Support high contrast light theme

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#11314]
### Feature Description:
With [version 1.65](https://code.visualstudio.com/updates/v1_65#_light-high-contrast-theme), vscode introduced the light high contrast theme. Now that we support the dark high contrast theme, it might be a good idea to support that as well. The necessary infrastructure is in place for that.

**Comment by colin-grant-work** [comment]
I took a look at this as part of #11331, and it turns out not to be trivial. Although it's available, Light High Contrast isn't loaded automatically by the `StandaloneThemeService`, and adding that to its loading sequence and then following the same procedure as we do with the other built-in themes produced a pretty ugly display. I didn't troubleshoot the problems very deeply but decided to omit it from #11331.

**Comment by msujew** [comment]
@colin-grant-work Good to know, thanks for the update 👍
