### ISSUE TITLE
Conflicting declarations in `theia.d.ts` and `theia.proposed.d.ts`

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11556]
### Steps to Reproduce:

1. In `packages/plugin/tsconfig.json` set `compilerOptions.skipLibCheck: false`.
2. Open `theia.d.ts`
3. Find `AuthenticationProviderAuthenticationSessionsChangeEvent` and observe that TS now points out that the interface is declared with different types in `theia.proposed.d.ts`

### Additional Information

Various other problems are found with `skipLibCheck: false`, and straightforward fixes result in build errors in the code.

**Comment by colin-grant-work** [comment]
@martin-fleck-at, since it looks like you added the `authentication` API to `theia.d.ts`, would you be willing to clean up `theia.proposed.d.ts` where to two conflict / where the latter is out of date with VSCode's proposals?

**Comment by martin-fleck-at** [comment]
@colin-grant-work Sure, I can have a look!

**Comment by martin-fleck-at** [comment]
@colin-grant-work I had a look at the API and I do not think there is a good strategy to get the types proposed API and the stable API compatible. I therefore suggest to get rid of the proposed API since we only were compatible with a very specific commit of the proposed API in VS Code 1.53.2 anyway and therefore never fully compatible with 1.53.2 (see https://github.com/eclipse-theia/theia/pull/10709#issuecomment-1029910285 and the PR). Our current stable API matches the stable API from VS Code 1.54.0 and higher which I hope will be enough, what do you think?

**Comment by colin-grant-work** [comment]
@martin-fleck-at, I agree. I don't believe VSCode does, and I don't believe we can or should guarantee ongoing compatibility with outdated proposal stages, so if the API has moved on, we should as well.

**Comment by martin-fleck-at** [comment]
@colin-grant-work Perfect, I already implemented this in a PR here: https://github.com/eclipse-theia/theia/pull/11564 ;-)

**Comment by colin-grant-work** [comment]
Closing this as complete via #11564 and #11684
