### ISSUE TITLE
secondary-window: add electron support

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11642]
#### Bug Description:

The issue tracks a known limitation from https://github.com/eclipse-theia/theia/pull/11048, where secondary or multi windows is not supported for `electron`. The goal is to add proper support for the desktop use-case which already has code in place but is not yet enabled.

#### Additional Info:

- Theia Version: as of a07b74644372ebc6c5f04e153bd7d8607a5afc5c.

**Comment by seltzered** [comment]
FYI, I noticed the readme (https://github.com/eclipse-theia/theia/blob/ac0c246fbcd439c259b4778e41199708d4354899/packages/secondary-window/README.md) still says 
"The extension is currently only suitable for use in browser applications because there are some unresolved issues with Electron." - is this still correct?

I'm noticing (on Electron on Linux , Theia 1.53.2), secondary-window appears functional in the latest theia-blueprint, but in my own app ( https://github.com/seltzered/beancolage ) it seems to open the secondary window but just appears as a blank window. Will try to debug further, not seeing anything really obvious at the moment.
