### ISSUE TITLE
New RPC changes cancellation token behavior

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11685]
### Bug Description:

Prior to the changes to the RPC architecture, cancelling an RPC using a cancellation token would not automatically result in a rejection on the calling side. Instead, the cancellation would be passed to the receiving side, and the callee could handle the cancellation itself. In the new RPC, any cancellation automatically cancels the request on the sending side.

https://github.com/eclipse-theia/theia/blob/99edac2e68cc8886c30865842b895cd93dc331b3/packages/core/src/common/message-rpc/rpc-protocol.ts#L135-L146

Arguments can be made for either approach (if the frontend cancels, it probably shouldn't expect the response; on the other hand, perhaps it would be happy to accept a partial result on cancellation), but it is a definite breakage.

### Steps to Reproduce:

1. Implement a frontend service that calls a backend service, provide a cancellation token, and cancel the action immediately.
2. Implement logic on the backend to handle cancelation and return some kind of default / partial result.
3. Before 1.27 (tested on 1.24), the partial return from the backend would be received on the frontend; since 1.27, the call will be rejected.

### Additional Information

- Theia Version: 1.28

**Comment by colin-grant-work** [comment]
@tortmayr

**Comment by tortmayr** [comment]
Thanks for raising this issue. I had a second look at the cancellation API implementation and we are currently in a somewhat weird state. On the one hand we already forward cancellation tokens to the  receiving side so that the callee could handle the cancellation itself. On the other hand we immediately reject the pending promise on the sender side if a cancellation is triggered.

>Arguments can be made for either approach (if the fronted cancels, it probably shouldn't expect the response; on the other hand, perhaps it would be happy to accept a partial result on cancellation), but it is a definite breakage

I feel like handling the cancellation on the receiving is probably the more flexible approach. As you already mentioned this allows partial results and more importantly in certain cases the client can continue normally after the cancellation without  the need for special rejection handling.

The plugin RPC protocol also seems to use this "receiving side cancellation handling".

I will provide a PR to restore the "receiving side cancellation handling" that we hand prior to the RPC architecture changes
