### ISSUE TITLE
PR: Refactor to use the new tunnel API 

### ISSUE THREAD

**Issue by lemanschik** [eclipse-theia/theia#11949]
### Feature Description:
The Visual Studio Code [Remote - Tunnels](https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-server) extension lets you connect to a remote machine, like a desktop PC or virtual machine (VM), via a secure tunnel. You can connect to that machine from a VS Code client anywhere, without the requirement of SSH.

Tunneling securely transmits data from one network to another via [Microsoft dev tunnels](https://learn.microsoft.com/azure/developer/dev-tunnels/overview).

This can eliminate the need for source code to be on your VS Code client machine since the extension runs commands and other extensions directly on the remote machine.

## Usage
You can also install and unpack the CLI through the terminal of your remote machine. This may be especially helpful if your remote doesn't have a UI:
```
curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz
tar -xf vscode_cli.tar.gz
code tunnel
```

See: https://code.visualstudio.com/docs/remote/tunnels

- [x] https://github.com/microsoft/vscode/commit/25cfb20ec9f1c6e8059b140e45e6610ae916fe7e
- [ ] Implementing above linked API as Part of: 
- [x] https://github.com/eclipse-theia/theia/issues/11948

**Comment by lemanschik** [comment]
Upstream got aligned: 
- [ ] https://github.com/eclipse-theia/theia/issues/13272
- [ ] Wait for the Alignment of [open-vscode server. ](https://github.com/gitpod-io/openvscode-server/tree/main)
- [ ] VSCodium
- [ ] https://github.com/eclipse-theia/theia/issues/11948

**Comment by lemanschik** [comment]
@vince-fugnitto please re read the new Issue description to see what this is about. While i prepare more planning for the switch. And Support for external Auth Providers so none Github.com. 

- Github Enterprise and Gitlab support and so on is incoming.

**Comment by msujew** [comment]
The Remote Tunnels extension prevents us (or anyone not officially Microsoft) from using the extension (see [license](https://marketplace.visualstudio.com/items/ms-vscode.remote-server/license)). Also, due to technical limitations (it attempts to run a VS Code instance, while we are using Theia) it's possible to connect to the provided backend.

Closing this issue, as the tunnel API (similar to the remote resolvers API, see https://github.com/eclipse-theia/theia/issues/12768) cannot be supported by Theia.
