### ISSUE TITLE
[vscode] Support property enabled in SourceControlInputBox

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12027]
see https://code.visualstudio.com/api/references/vscode-api#SourceControlInputBox

since 1.69, boolean property enabled has been added.

**Comment by jonah-iden** [comment]
i would work on this one

**Comment by jonah-iden** [comment]
ok this seems really hard to test because it requires creating an own SourceControl. That in itself is not difficult but it seems like the vscode api method vscode.scm.createSourceControl does not seem to work correctly currently. 
It seems #8291 added the support for multiple providers but it does not react to createSourceControl. 
In vscode calling `vscode.scm.createSourceControl('test', 'test scm', vscode.Uri.file('/workspace/theia'))` works fine and looks  like this
![grafik](https://user-images.githubusercontent.com/34068281/212314431-52fa3e51-ef2d-4834-a823-54bba6ed9b37.png)

in theia nothing happens to the scm view. Am i overlooking something? If not i would create an issue for this which probably needs to be done before this one

**Comment by vince-fugnitto** [comment]
@jonah-iden we don't actually have support for #8291 where we can list multiple providers yet, but you should be able to test if you simply remove `@theia/git` from the examples:

![image](https://user-images.githubusercontent.com/40359487/212324804-17356ece-4bfd-43d3-8a43-c9f9239721b2.png)
