### ISSUE TITLE
[playwright] Flaky Playwright test in `theia-explorer-view.test.ts:56:9`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#12063]
### Bug Description:

As I'm tracking the executions of the [Playwright tests](https://github.com/eclipse-theia/theia/tree/master/examples/playwright/src/tests) and recording their failures continuously, I observed that there is actually only one test in the past four months which fails from time to time (about 3-4 times a month). I didn't observe any other test failing in this time frame.

Thus, I believe it is worth spending some time investigating whether this flaky test can be stabilized.

See below for the output of the flaky test, when it fails:

```text
[playwright]   1) ../../src/tests/theia-explorer-view.test.ts:56:9 › Theia Explorer View › should show one folder named "sampleFolder" and one file named "sample.txt" 
[playwright] 
[playwright]     Error: expect(received).toBe(expected) // Object.is equality
[playwright] 
[playwright]     Expected: true
[playwright]     Received: false
[playwright] 
[playwright]       56 |     test('should show one folder named "sampleFolder" and one file named "sample.txt"', async () => {
[playwright]       57 |         await explorer.selectTreeNode('sampleFolder');
[playwright]     > 58 |         expect(await explorer.isTreeNodeSelected('sampleFolder')).toBe(true);
```

See also https://github.com/eclipse-theia/theia/actions/runs/3815148923/jobs/6489956895

**Comment by marcdumais-work** [comment]
I noticed this issue has been re-happening recently \[1\]. I tried the Playwright tests locally for the first time and was lucky that I was able to reproduce the failure rather consistently \[2\]. I will be posting a PR shortly to try to improve the flaky tests I was able to troubleshoot locally. 

@planger I would appreciate your review on it. I think you had the correct idea in your related recent PR, but the same issue is happening in other test cases too, so I went with a fix in the test infrastructure. More details in the PR.

\[1\]: e.g.:
https://github.com/eclipse-theia/theia/actions/runs/4566999149/jobs/8060253354#step:7:422
https://github.com/eclipse-theia/theia/actions/runs/4558355274/jobs/8055182849#step:7:415
https://github.com/eclipse-theia/theia/actions/runs/4564018969/jobs/8053243319#step:7:420

\[2\]: Way more so that in our CI, which passes most of the time. This suite seems extremely sensitive to timing - t some point I tried adding some entropy by running `stress -c 1 -m 1" during the Playwright tests and the failures went away until I stopped :)
