### ISSUE TITLE
Outline does not work for Python

### ISSUE THREAD

**Issue by el-coder-sb** [eclipse-theia/theia#12219]
### Bug Description:

With python extension installed, opening a python file in the outline box it says:
`The active editor cannot provide outline information`

### Steps to Reproduce:

1. Install Theia Blueprint Version 1.32.0 (Beta)
2. Install Python extension by ms-python
3. Open any python file.

### Additional Information

- Operating System: Win10
- Theia Version: Theia Blueprint Version 1.32.0 (Beta)

**Comment by msujew** [comment]
[ms-python](https://open-vsx.org/extension/ms-python/python) is an extension that bundles the proprietary [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) extension for Python support. Since the Pylance extension does not allow installation outside of officially distributed vscode instances, Theia will not install the extension (it's not available on `open-vsx` anyway). So not having outline support is expected, since the extension that's supposed to supply the outline information doesn't install in the first place.

I would recommend to use [Pyright](https://open-vsx.org/extension/ms-pyright/pyright) instead, its an open source version of Microsofts proprietary Pylance extension. Outlines seems to work as expected with the extension installed:

![image](https://user-images.githubusercontent.com/4377073/221164584-e72ef014-610e-424a-9751-3d2de8d35f36.png)

**Comment by el-coder-sb** [comment]
@msujew Thanks for the explanation. As theia works as expected I´ll close this issue.
Thanks for the pyright solution. That works for me fine.
