### ISSUE TITLE
Cannot find Spark Development Tools in extensions list

### ISSUE THREAD

**Issue by vgherissi** [eclipse-theia/theia#12290]
### Bug Description:

Hello,

I don't have the extension "Spark Development Tools" to create a Spark Interpreter in the extension available.
Why ? There is a other thing to do to get this extension ?

Thanks in advance.

### Steps to Reproduce:

1. use Theia version 1.35.0
2. Go to extension at left
3. Enter Spark Development Tools

### Additional Information

- Operating System: Ubuntu 20.04.5
- Theia Version: 1.35.0

**Comment by msujew** [comment]
Hey @vgherissi,

we're using the [`open-vsx`](https://open-vsx.org/) registry for supplying users with vscode extensions. I assume you're looking for [this extension](https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight)?

It seems like nobody has uploaded it to the open-vsx marketplace yet, and I'm not sure whether this is actually (legally) possible, given that the extension is [closed source](https://github.com/microsoft/Spark-Hive-Tools). Anyway, Theia and Theia based applications are not allowed to use the official vscode marketplace due to legal reasons, so you'll need to find some way to get your hands on the extension using other means.

Since this is unrelated to Theia, I'll close this one.
