### ISSUE TITLE
There's no translation for menu 'view -> test'

### ISSUE THREAD

**Issue by doubaozia** [eclipse-theia/theia#12372]
### Bug Description:
There's no translation for menu 'view -> test'

### Steps to Reproduce:

1. Install theia's any example
2. Install vscode plugin loc-vscode(zh-cn) from open-vsx
3. Click top menu view, you can see the test is not translated as below

![image](https://user-images.githubusercontent.com/12318032/229742578-fb177ae6-8a0e-490d-84e5-43e2d9b1a8f8.png)

### Additional Information

- Operating System: Mac os
- Theia Version: 1.35.0

**Comment by doubaozia** [comment]
I have tried to search the word from 'nls.metadata.json', but can only find 'vs/workbench/common/actions', show as below:
![image](https://user-images.githubusercontent.com/12318032/229747462-cdef481e-18cb-4fe7-b3b3-96c54de43d64.png)

**Comment by doubaozia** [comment]
By the way, some submenus in the context menu is also not translated.
![image](https://user-images.githubusercontent.com/12318032/229747740-46a8d700-0f46-4b62-9c67-45728cf62fa6.png)

**Comment by msujew** [comment]
@doubaozia As for the `Test` view, that's probably an oversight and will likely get fixed with https://github.com/eclipse-theia/theia/pull/12175 anyway.

As for the other submenus. They're contributed by other vscode extensions, and not by Theia itself. See for example the [clangd commands](https://github.com/clangd/vscode-clangd/blob/8ce86b2dbb9cd266d2cee6a95d398791e9aef38f/package.json#L164-L168). Extension devs need to take care of localization by themselves, there's nothing we can do on Theia's side.

**Comment by doubaozia** [comment]
Thx~
