### ISSUE TITLE
regression: unable to build browser-only application

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#12490]
#### Bug Description:

Following https://github.com/eclipse-theia/theia/pull/12299, we are unable to successfully build a browser-only application as the electron preload functionality is incorrectly used in the browser.

Attempting to build the browser app will result in:

```
$ theia build --mode development
Failed to resolve module: @theia/electron
```

#### Steps to Reproduce:

1. follow the steps from https://theia-ide.org/docs/composing_applications/#consuming-vs-code-extensions
2. perform `yarn` - the result will fail

#### Additional Information

Also reported in https://community.theia-ide.org/t/failed-to-resolve-module-theia-electron/2820/11.

**Comment by bayodesegun** [comment]
I still get this error on the latest version of Theia, `1.43.1`, _though the build succeeds_. 

Could it be I'm doing something wrong? I started getting the error when I removed the `electron-app` directory automatically generated by the Theia extension generator. I also removed `electron-app` from `workspaces` in `package.json`.

I tried removing all build folders and re-running `yarn`, but that message still appears but build is successful.

**Comment by msujew** [comment]
@bayodesegun It's Theia itself trying to resolve `@theia/electron` which fails since it's not used. I'm not sure the reason for this, but it's not an error in itself. See [here](https://github.com/eclipse-theia/theia/blob/bf93b2910d8fcee7e3a9f9768194f49191fb552f/dev-packages/application-package/src/extension-package-collector.ts#L65).
