### ISSUE TITLE
nls: certain localizations are not always applied

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#12517]
#### Bug Description:

There seems to be a regression where certain localizations are not applied.
I've noticed the following but there might be others:

https://github.com/eclipse-theia/theia/blob/4867d2ad53894ad7746848456334a09a1696f9f5/packages/core/src/browser/dialogs.ts#L73

https://github.com/eclipse-theia/theia/blob/4867d2ad53894ad7746848456334a09a1696f9f5/packages/terminal/src/browser/terminal-frontend-contribution.ts#L682

#### Steps to Reproduce:

1. start the application
2. use `configure language display` to change language besides english (ex: french)
3. confirm that the two user-facing strings are not localized

**Comment by msujew** [comment]
@vince-fugnitto It's likely due to the fact that the vscode version was bumped without me updating our `nls.metadata.json` file. VSCode language packs and this json files need to stay in sync to actually work as expected.

I'm currently on a longer vacation. But I'll be back on the 22nd and could take care of this.
