### ISSUE TITLE
VS Code menu contributions to "editor/title/run" seem to behave no different than to "editor/title"

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#12687]
### Bug Description:
I see that support for menu insertion point "editor/title/run" was added to Theia in recent months. It works...but not really how it works in VS Code. 

In VS Code, if you have two or more contributions to "editor/title/run", a "Run or Debug..." submenu item is added to the editor title area. It appears as a regular menu item in the editor title toolbar (as icon or text), with a carat next to it for opening the submenu.

![image](https://github.com/eclipse-theia/theia/assets/109228283/937f2e8b-bf03-49c7-a610-de75b3c6d64e)

In Theia, the contributions to "editor/title/run" seem to appear exactly as if they were contributed to "editor/title". I.e., there is no grouping of them into a "Run or Debug..." submenu with a caret, etc.

I don't know if this is a known limitation of the current implementation. Perhaps the point was to get the contributed menu items into the UI in the simplest form possible, but not provide the full behavior of VS Code. However, if this is an unintended behavior/gap, I'll provide reproducibility steps.

**Comment by cdamus** [comment]
I'm happy to look into this.

**Comment by cdamus** [comment]
In rebasing #12804 onto the latest `master` branch, I discovered that the fix for this issue causes a regression in the rendering of toolbar items that have a `menuPath` in addition to a `command`: they are now rendered as pop-up menus instead of simple buttons to be clicked. For example, the actions contributed with `navigation` group on the `menu_bug_1` branch of the OP's sample repository, for issue #12686, end up rendered like this:

![CleanShot 2023-08-28 at 17 24 28](https://github.com/eclipse-theia/theia/assets/1615558/83c23265-3d81-42d0-b6df-f182fe176acc)

instead of this:

![CleanShot 2023-08-28 at 17 27 19](https://github.com/eclipse-theia/theia/assets/1615558/7968bdd7-5524-4481-ad7e-2197fe037a46)

@jcortell68 or @martin-fleck-at could one of you please re-open this issue? I haven't permission as non-owner and non-committer.

**Comment by jcortell68** [comment]
@cdamus I also do not have the ability to re-open this issue.
