### ISSUE TITLE
[vscode][proposed] resolvers proposed API updates for 1.80

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12768]
RemoteAuthorityResolverContext execServer was added. 

We currently do not support much of the resolvers currently, only LabelProvider. So this task does not seem a priority, we may probably skip this one.

**Comment by rschnekenbu** [comment]
resolvers proposed API is used only in vscode-test-resolver builtin extension. Given our current version of theia implementation, many interfaces required by the vscode-test-builtin extension do not exist. So I assume this extension is not part of our interest or we do not rely on it.

**Comment by tsmaeder** [comment]
The `vscode-test-resolve` extension is only used when testing VS Code, as far as I understand it. Since it's not included with the built-ins, we can ignore it.
Had a conversation with @msujew and he says these API's are used to implement WSL and remote SSH, etc., but are not usable in their work towards remote SSH in Theia. So the most may have to do is stub the API, but for now, we can just ignore it, IMO.

**Comment by tsmaeder** [comment]
Closing as "nothing to do".
