### ISSUE TITLE
When backend-to-backend plugins are supported, we'll need the plugin-host to be launched on backend startup

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#12959]
### Feature Description:
Today, a plugin-host is forked only when a frontend attaches to the backend. @martin-fleck-at confirmed this recently. This is fine given that today's plugins only interact with the browser. I.e., all functions in the VS Code extension API are serviced by Theia extension code running in the frontend. Thus there is no point in loading plugins if there is no frontend.

Issue #12946 asks for backend-to-backend plugin support. Once that's available, we'll want to take things a step further. There might be backend functionality in an app that we want to run in a headless manner--either via a command-line interface, or via a server/REST model. Any backend-to-backend plugins need to be able to participate in that functionality, which means plugins need to be loaded and activated in that headless Theia environment.

**Comment by msujew** [comment]
I'm sceptical how this is supposed to work and the general usefulness of the feature compared to it's potential complexity. Generally, we have three classes of vscode plugins:

1. Written for VSCode, but work in Theia as well (virtually everything that's on the Open VSX marketplace).
2. Written for Theia but using the VSCode API; they work just as well in VSCode (the common approach taken by Theia product developers trying to add language support or Debuggers to their app).
3. Written for Theia, using product specific APIs.

While 1. and 2. don't get any benefit from this feature, since they were written against VSCode's API with VSCode design and behavior in mind (which also doesn't spawn a plugin host on backend start), 3. could just have been written as a regular Theia extension and work just as well (if not better). Not to mention that you effectively need to mock a frontend just for the plugin host to start - which sounds pretty hacky in my opinion.

**Comment by jcortell68** [comment]
@msujew We are developing a product that needs to support vendors, third parties and even savy users extending the application in product-specific ways. Furthermore, this needs to be doable from components that can be deployed and installed in the field.

**Comment by msujew** [comment]
I get the business requirement/purpose behind this feature proposal - I just don't think it fits into the scope of the Theia open source repo. My main gripe with this feature is that it requires to mock a frontend on the backend which is just not architecturally sound. @tsmaeder I'd be interested in hearing your take on this, since you're always going on about architectural soundness ;)

Having a backend plugin mechanism that is generally similar to the existing plugin mechanism (that mainly emulates vscode's extension mechanism) is perfectly fine. I just think that it should be explicit for-backend-only use and not use the existing vscode API, which requires access to a frontend. But then again, this would probably be best suited as part of a product-specific Theia extension and not part of this repo.

**Comment by jcortell68** [comment]
I'm not advocating for mocking a frontend. Backend-to-backed support need not carry over anything from the backend-to-frontend support. Whatever such a solution carries over would be out of convenience--for the sake of not reinventing the wheel or duplicating code. But there are no backend-to-backend plugins today, so there is no backward compatibility to be concerned about. We just need the ability to have backend-to-backend plugins, period--in whatever form that ends up looking like.

**Comment by tsmaeder** [comment]
Methinks this is a side issue: the main question is, whether to do back-end plug-ins at all: let's discuss on the linked issue https://github.com/eclipse-theia/theia/issues/12946

**Comment by msujew** [comment]
@jcortell68 Nevermind, I believe I overread the last part of your post:

> Any backend-to-backend plugins need to be able to participate in that functionality, which means plugins need to be loaded and activated in that headless Theia environment.

I was under the assumption that normal vscode plugins are also supposed to contribute to this backend-only plugin host. Sorry for that. So yeah, since this plugin host would be effectively only for specialized plugins and use a dedicated backend API, that would make sense.

**Comment by jcortell68** [comment]
> Methinks this is a side issue: the main question is, whether to do back-end plug-ins at all: let's discuss on the linked issue #12946

Indeed. If #12946 doesn't get implemented, then this ask goes away with it. However, #12946 could be implemented without implementing this ticket. But that would be a shame :-)

**Comment by martin-fleck-at** [comment]
Closed with https://github.com/eclipse-theia/theia/pull/13138
