### ISSUE TITLE
theia is affected by libwebp vuln CVE-2023-4863

### ISSUE THREAD

**Issue by Sharyie** [eclipse-theia/theia#13000]
electron was affected by a vuln refer to CVE-2023-4863, and electron has been upgraded to fix it and released secure editions.

electron-mocha depends on electron, and has been released a new version 12.1.0 which upgreaded electron to secure edition.

theia depends on electron-mocha 11.0.x, so could you please release a new version to upgrade electron-mocah to 12.1.0 for fixing the vuln?

**Comment by Sharyie** [comment]
hello, Are there any plans to fix this vuln?

**Comment by msujew** [comment]
@Sharyie Since our version of Electron itself seems to be unaffected (23.2.4), and we only use `electron-mocha` as a [dev-dependency](https://github.com/eclipse-theia/theia/blob/e0c82d13a461d1732c13852c8f1e3adc5d234d2f/package.json#L31), there is no immediate security risk for adopters/users of Theia.

This will likely be fixed the next time we perform a electron update, but it requires no immediate action.

**Comment by msujew** [comment]
@Sharyie This will be fixed with the next electron dependency upgrade, see also https://github.com/eclipse-theia/theia/issues/12855. Note that the risk of this vulnerability is pretty minor in Theia - it would require the use of a malicious vscode extension or manually loading a malicious webpage through the in-app browser.

**Comment by Sharyie** [comment]
Thanks, note that the security electron version of 25.x.y is 25.8.4 and later.
