### ISSUE TITLE
Support to capture terminal contents

### ISSUE THREAD

**Issue by kavitha-subr** [eclipse-theia/theia#13085]
### Feature Description:

As a developer, I would like the ability to capture the contents of the terminal so that I can identify errors and warnings for further action.
Currently, the only possible way to get terminal contents is to spawn a new terminal and have an event listener listen to the output data. I would like to have this feature without having to create a new terminal.

**Comment by kavitha-subr** [comment]
Yup, this looks great!

**Comment by tsmaeder** [comment]
I've made a branch at https://github.com/tsmaeder/theia/tree/13085_terminal_observer with the necessary changes. Here's the source for a plugin using the API: 

[terminalobserver.zip](https://github.com/eclipse-theia/theia/files/13460830/terminalobserver.zip)

**Comment by tsmaeder** [comment]
To test, you'll have to build & run theia from the branch. To build the plugin, you will have to yarn link the `@theia/plugin` package. In order to do so, you have to 

1. go into the `<theia>/packages/plugin` folder and type `yarn link`
2. go in the root folder of the example plugin source and type 'yarn link @theia/plugin`

Then you can just build the plugin and copy the resulting *.theia file into the theia plugins folder.

**Comment by kavitha-subr** [comment]
Thank you so much! I'll verify if everything works as expected.
