### ISSUE TITLE
Different IDEs rendered using the same package.json and similar steps

### ISSUE THREAD

**Issue by kjq** [eclipse-theia/theia#13141]
### Bug Description:
I am trying to get a consistent Theia build between development and production environments that runs inside a Docker container before diving in any deeper but using similar steps, and the same `package.json`, I get two different IDE's representations.

In both cases, development and production I am running inside of a Docker container.  Even if I replicate the steps being done in the `Dockerfile` inside the shell in the development container I get the same results (2 different views).

My expectation is that the IDEs would be the same, and because of having only 2 `@Theia dependencies` I am assuming the _development_ view is the right one with the minimal functionality exposed on the sidebar.

**So, my questions are:**
1. Which view is the _correct_ one? It appears pulling in the `@theia/plugin-ext-vscode` pretty much pulls in everything anyhow (which is not what I want but another question) but given the minimal dependencies the first _seems_ like what I would expect or something similar.

2. Is there a definitive example of _just_ a browser IDE being built not using this monorepo?

3. How do you properly package this inside a Docker container for production?  I have had various levels of success with any example I have tried from the Theia repositories.  

I have been working at this for quite some time, and not being a Node developer could have something misconfigured, but finding a solid example that is recent has been challenging.

### Steps to Reproduce:
Below are screenshots from both approaches, notice the different sidebar items, and the project folder as it is right now.

#### Development Steps
Because Node is not our native environment this is a container that has node in it with the project folder mounted.  It is meant to be shelled into and the node commands are run within the container.

1. `docker build . -f Dockerfile.build -t theia-dev`
4. `docker run -it --rm -v $PWD:/project -p 3000:3000 -t theia-dev bash`
5. `yarn install`
6. `yarn build`
7. `yarn start`
8. Navigate to `http://localhost:3000`

> Interestingly enough, if I navigate to the same URL in a Chrome incognito window I see the same IDE as I do with the production steps below.

#### Production Steps
The production `Dockerfile` is cobbled together from the examples as best I could and meant to be deployed as a container.

1. `docker build . -t theia`
2. `docker run -p 3000:3000 -t theia`
3. Navigate to `http://localhost:3000`
 
### Additional Information

**Running the development steps I get this:**
![theia-dev](https://github.com/eclipse-theia/theia/assets/533810/903c7e55-621d-4896-8832-a0338c0050e8)

**Running the production steps (or an incognito window using the development steps) get this:**
![theia-prod](https://github.com/eclipse-theia/theia/assets/533810/d10a302f-7340-4d0a-9b0c-d25bf00db511)

**Project Folder**
[theia.zip](https://github.com/eclipse-theia/theia/files/13540141/theia.zip)

- Operating System: WSL2 but running Theia and its build completely inside Docker containers
- Theia Version: 1.44.0

**Comment by msujew** [comment]
@kjq Theia has a feature that stores the layout of the application in your browsers local storage. When visiting the same URL, Theia restores the most recent layout. It's likely the case that the first layout that was stored in your browser was a very simple one (just showing the navigator in the side bar). You can reset the layout to the default by using the `Reset Workbench Layout` command.

That would also explain why you're seeing the correct layout in incognito mode. You get a fresh local storage, which doesn't contain the old layout. Note that the layout is mostly independent of which widget actually exist in the application. You can access all views via the `View` menu at the top of the application.

> Which view is the correct one? It appears pulling in the @theia/plugin-ext-vscode pretty much pulls in everything anyhow (which is not what I want but another question) but given the minimal dependencies the first seems like what I would expect or something similar.

`@theia/plugin-ext-vscode` pulls in most Theia packages, because to emulate the vscode API, it requires a lot of functionality, such as the stuff contributed by `@theia/monaco` (for editor support), `@theia/terminal` and `@theia/workspace`, etc. You can always remove stuff from Theia by using [contribution filters](https://github.com/eclipse-theia/theia/blob/master/examples/api-samples/src/browser/contribution-filter/sample-filtered-command-contribution.ts).

> Is there a definitive example of just a browser IDE being built not using this monorepo?

Theia is just a framework. You can build your IDE however you like, we don't give out any *definitive* recommendations.

> How do you properly package this inside a Docker container for production? I have had various levels of success with any example I have tried from the Theia repositories.

Again, we're just building a framework. It really depends on the use case. You can find a good one [here](https://github.com/eclipse-theia/theia-blueprint/blob/master/browser.Dockerfile) though. Theia blueprint is the "standard distribution" of Theia.
