### ISSUE TITLE
Backport Issues for 1.45.1

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#13293]
### Bug Description:
List of issues to backport for the 1.45.1 Community release

- [x] https://github.com/eclipse-theia/theia/issues/13215

**Comment by planger** [comment]
Maybe this one is an easy fix for the next release in order to enable SSH remote development support?
https://github.com/eclipse-theia/theia/issues/13294

**Comment by tsmaeder** [comment]
@planger I don't see any changes to be done for that issue. At least no PR is linked in the issue.

**Comment by planger** [comment]
@tsmaeder Yeah, no need for changes immediately, we just need to make sure we also release the native dependencies and upload it to the release.
I was just wondering whether we should automate the publishing of the native dependencies in the release pipeline, otherwise we may forget it in the future again, breaking the remote SSH support.

**Comment by tsmaeder** [comment]
That does not sound like something for a patch release. Also, I am not aware that we need to do anything for the patch release regarding native dependencies, etc. I'm just the piano player.

**Comment by tsmaeder** [comment]
But it does sound like a great issue to open ;-)

**Comment by planger** [comment]
> That does not sound like something for a patch release. Also, I am not aware that we need to do anything for the patch release regarding native dependencies, etc. I'm just the piano player.

Well, we need to ensure that the release artifacts (also for the patch release) include the native dependency archives, because the URL to download them into the remote machine is constructed from the concrete Theia version (see [app-native-dependency-contribution.ts#L39](https://github.com/eclipse-theia/theia/blob/master/packages/remote/src/electron-node/setup/app-native-dependency-contribution.ts#L39), which is different also between a patch release and the .0 release.
Since there doesn't seem to be an automatic workflow, we need to upload the native dependency archives to the dot release in Github manually, afaik.

> But it does sound like a great issue to open ;-)

Definitely, I'll create an issue.

**Comment by tsmaeder** [comment]
Calling @msujew to the rescue.

**Comment by msujew** [comment]
We should be able to modify the existing dispatch workflow that generates the artifacts to automatically attach them to each release.

**Comment by tsmaeder** [comment]
But what do we need to do for the 1.45.1 release, @msujew?

**Comment by msujew** [comment]
@tsmaeder I've already added the binaries to the release.

**Comment by planger** [comment]
I've added https://github.com/eclipse-theia/theia/issues/13308 to track the automation of this step.

@tsmaeder The 1.45.1 release should be fine, because it already contains the native dependency artifacts (probably @msujew added them manually).

**Comment by tsmaeder** [comment]
@msujew could you add steps to https://github.com/eclipse-theia/theia/blob/master/doc/Publishing.md in case we don't have the automation ready for the next release (tomorrow ;-))?

**Comment by msujew** [comment]
@tsmaeder I've notified Vince that these files should be added to the release. In the worst case I'm going to add them manually again. It's probably not worth the effort of adding (and then removing) stuff from the documentation.
