### ISSUE TITLE
Extensions View does not update as expected

### ISSUE THREAD

**Issue by jfaltermeier** [eclipse-theia/theia#13320]
### Bug Description:

When I install or uninstall an extension, the UI does not update as expected.
Tested with Electron

![Peek 2024-01-26 08-51](https://github.com/eclipse-theia/theia/assets/5889696/64a1f1bd-3073-40fd-9c80-3bcc6ba51a39)

### Steps to Reproduce:

1. Uninstall or Install an extension from VSX
2. After this is done, the button does not update as expected

### Additional Information

- Operating System: Ubuntu 22.04
- Theia Version: 1.46.0

**Comment by msujew** [comment]
Probably a regression from https://github.com/eclipse-theia/theia/pull/13138.

**Comment by xai** [comment]
> Probably a regression from #13138.

It is, yes. I bisected it down to that. Commits prior to that do not have the issue.  
We are having some dependency injection issues here.

The first one is in https://github.com/eclipse-theia/theia/blob/b15b639fa3b64a9518efdf3e82ea9098915ba145/packages/plugin-ext/src/hosted/browser/worker/worker-main.ts#L59
where `RPCProtocolImpl` instead of `RPCProtocol` is used (Christian spotted that yesterday),
but there is more. Currently, I have trouble with the binding of `MinimalTerminalServiceExt`.

**Comment by xai** [comment]
Okay, apparently, dependency injection issues are not the only reason for this. I started a draft PR that resolves the DI-related issues, but the bug is still present.

**Comment by cdamus** [comment]
The crux of the problem was that the Headless Plugins refactoring lost the forwarding of `onDidDeploy()` events from the frontend `HostedPluginSupport` to the `HostedPluginWatcher`. With that restored, the issue seems to be resolved.
