### ISSUE TITLE
Add trigger for automatic (next) releases

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#13384]
While it's theoretically possible to consume Theia directly from source (`master` branch) to test new features/bug fixes in adopter projects, I would like to have an option to trigger an automatic `next` release to npm. We used to have something like this on every commit, but it became quite cumbersome, which is why we've disabled that.

We can also reuse that workflow to perform the actual release process after tagging/releasing a specific commit. We use this in Langium as well, see [here](https://github.com/eclipse-langium/langium/blob/main/.github/workflows/publish.yml).

**Comment by msujew** [comment]
@jfaltermeier Since you're our current release engineer, what is your opinion on that? It would probably make your work a bit easier :)

**Comment by jfaltermeier** [comment]
I agree that having the release build as a workflow would be good. This would remove any possible user errors, like wrong node versions or something like that. 
Also having npm provenance would be nice. 

Regarding the `next` builds. I like having `next` builds available, but as far as I remember we stopped with this because we did not want to spam the npm registry with all those versions nearly nobody was using. 
Having e.g. a weekly next versions might be a good compromise for allowing end users to test early but not spamming on every commit. 

I was also experimenting with with a dockerized verdaccio registry, allowing to build Theia locally and get it published to a local registry with just a single docker command. I plan to continue on this. This might then be a good starting point for users that want to test a specific Theia commit.
