### ISSUE TITLE
[navigator] Navigator context menu enhancements

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#1344]
- [ ] Copy path.
 - [x] Open in terminal.

**Comment by kittaakos** [comment]
@svenefftinge, where should I put the `Open in Terminal` implementation, for instance?
 - I can put it into the `@theia/navigator`, but then I need to depend on the `@theia/terminal`.
 - I can implement it into the `@theia/terminal` if introduce the `@theia/navigator` dependency which I do not want to.
 - Alternatively, I could move this to the `@theia/workspace` but it does not yet depend on `@theia/navigator` or `@theia/terminal`.
 - Do we need a new package; `@theia/workbench`?

**Comment by akosyakov** [comment]
I like an idea with `workbench` extension. It allows to keep extensions decouple without changing the core. It could serve as a base extension for Theia, i.e. including typical extensions like `navigator`, `terminal`, `editor`, `preferences` and so on.

**Comment by svenefftinge** [comment]
It should go into `terminal` without a dependency to `navigator`. I understood that dependency would only exist because of the menu entry. We should just use the id (string).

Introducing a third extension that is the place for everything where we have have such dependency issues will end up being a big kitchen sink with dependencies to everything. Also the name is very generic.

**Comment by kittaakos** [comment]
@thegecko, the `Copy path` is not implemented, right?

**Comment by kittaakos** [comment]
> copies a path as well

The URI, not the path.

**Comment by vince-fugnitto** [comment]
I believe the issue can be closed thanks to the following pull-request which adds `copy path`:
- https://github.com/eclipse-theia/theia/pull/7934
