### ISSUE TITLE
Running command in terminal cannot be canceled

### ISSUE THREAD

**Issue by sgraband** [eclipse-theia/theia#13560]
### Bug Description:
Currently it seems like `ctrl-c` is not properly forwarded/registered on the built-in terminal. Pressing the keys does not cancel the currently running command.

### Steps to Reproduce:

1. Open a terminal
2. Run a long-running command (e.g. `yarn start`)
3. Try to cancel the command with `ctrl-c`
4. Observe that the command i s not cancelled.

### Additional Information

- Operating System: Ubuntu 22.04
- Theia Version: Theia IDE 1.48.0 (preview)

**Comment by tsmaeder** [comment]
I suspect this change is responsible for the problem: https://github.com/eclipse-theia/theia/pull/13493/files#diff-9d5279a0f960f7a97475073be510df0dcff9e33cf65830eb7205eb1c7ee96caaR42

**Comment by tsmaeder** [comment]
Turns out, this has nothing to do with the above change. There are several keybindings for `ctrl-c` the keybindings are traversed in registration order (per scope) and the first one that matches and is enabled is returned. In this case, it's `copy` (set `core/browser/keybinding.ts#matchKeybinding()`. If this ever worked, it's by accident.
