### ISSUE TITLE
Add abstraction layer to support different types of container (Electron, Tauri, ..)

### ISSUE THREAD

**Issue by nimo23** [eclipse-theia/theia#14427]
### Feature Description:

Currently, Theia can run in the browser and in the electron container. To meet the need for other platforms (web, desktop, iOS app, Android app (see https://github.com/eclipse-theia/theia/issues/14040)) it would be great to have an abstraction layer to add more container environments easily. In this case: **Tauri** (see https://v2.tauri.app/). With Tauri it is possible to create native apps for desktop and mobile devices using only HTML, CSS and JS. It would be nice to add Tauri support for Thea. This can be achieved, for example, by providing a (container packaging) interface layer with two implementations (or two package.json tasks), one for Electron and one for Tauri.

**Comment by msujew** [comment]
Hey @nimo23,

we already have a discussion for that, see https://github.com/eclipse-theia/theia/discussions/9888. Note that Theia, in it's core, is a mixed JavaScript server/frontend application. You have very little to gain from wrapping it in Tauri, since the server requires running on node.js anyway.
