### ISSUE TITLE
Use ESM versions of Monaco

### ISSUE THREAD

**Issue by ishitatsuyuki** [eclipse-theia/theia#1542]
https://github.com/Microsoft/monaco-editor/issues/18 has been resolved; we may benefit from ESM by bundling them into one bundle, instead of doing XHR for various code files.

**Comment by akosyakov** [comment]
It depends of https://github.com/theia-ide/theia/issues/1542 if not a dub.

**Comment by AlexTugarev** [comment]
let's await the solution for https://github.com/Microsoft/monaco-editor/issues/850

**Comment by JonasHelming** [comment]
@tsmaeder : Is this even relevant anymore?

**Comment by tsmaeder** [comment]
@JonasHelming t.b.h, I have no idea.

**Comment by colin-grant-work** [comment]
@JonasHelming, @tsmaeder, I believe what's referred to here is the ability to bundle Monaco using Webpack rather than our current [`monaco-loader`](https://github.com/eclipse-theia/theia/blob/master/packages/monaco/src/browser/monaco-loader.ts) which uses [VSCode's loader](https://github.com/microsoft/vscode-loader) which (I think) loads the modules asynchronously by making separate requests for each file it discovers that it needs.

This issue is still relevant, and we may want to think about having some sort of epic about improving our Monaco consumption / simplifying Monaco uplifts:
 - Updating the documentation (minimum)
 - Consuming Monaco via Webpack
 - Automating the generation of [this file](https://github.com/eclipse-theia/theia/blob/master/packages/monaco/src/typings/monaco/index.d.ts) or (much better) eliminating that file in favor of typings coming from the Monaco package.

**Comment by colin-grant-work** [comment]
I believe that with the last few uplifts of, we've done all the things that I described above, so I think this ticket is ready to be closed.
