### ISSUE TITLE
Filtering for outline view

### ISSUE THREAD

**Issue by gorkem** [eclipse-theia/theia#1642]
It should be possible to filter the outline view.

**Comment by vince-fugnitto** [comment]
Closing in favor of #8380 (generic solution for all trees).

**Comment by akosyakov** [comment]
@vince-fugnitto I am not sure how it is related to #8380. We already have search in trees, enabling it for outline view is a matter of one line change.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I am not sure how it is related to #8380. We already have search in trees, enabling it for outline view is a matter of one line change.

Since we already have the search for the outline as I mentioned previously: https://github.com/eclipse-theia/theia/issues/1642#issuecomment-451233463. However, the filtering or narrowing down of nodes like in vscode is not present, but is something that is now tracked by #8380.

I re-verified that searching in the outline-view is present:

![outline](https://user-images.githubusercontent.com/40359487/90248144-1adbbd80-de06-11ea-81bf-1bebf25bb3f4.png)
