### ISSUE TITLE
Theia starts with the wrong workspace

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#1834]
User expected to have the specified workspace when initiating the browser.

How to reproduce:
1- Web browser: already open in a workspace
2- Create a new workspace: mkdir ~/zzworkspace + create some filesin it: baba, ppp, qqq, toto
3- Start Theia application: yarn start ~/zzworkspace
4- Note In the web browser, The current workspace will go from off-line to on line (The bottom status bar change color and state)
5- Select the refresh workspace from the web browser
  Note: Since the user initiated the application specifying a new workspace, as an end-user, I would expect that the "localhost:3000" would show me the new workspace when I refresh the browser (Not the case here)
Show files in work1 (Files: aaa, bbb, ccc,ddd)

6- Even If I modify the old workspace, it will refresh it if that workspace still exist !!!!
7- Now close the web browser with the old workspace (just the workspace page) the browser has other pages available
8- Open the web browser to localhost:3000
  -> Re-open the old workspace instead of the workspace specified when I started Theia !!!

9 Now close again the web browser "localhost:3000"
10- Stop theia (server side)
11- restart Theia with the same original workspace : yarn start ~/zzworkspace
12- On the browser, start a new "localhost:3000"
--> browser show the user-selected workspace now (As expected initially)
(Files: baba, ppp, qqq, toto)

![peek 2018-05-01 wrongworkspace](https://user-images.githubusercontent.com/419051/39483542-bc03c65c-4d40-11e8-907a-98f79073e739.gif)

**Comment by marcdumais-work** [comment]
I agree that it's sometimes hard to predict which workspace will be opened, when starting a Theia client. 

Experimenting with this a bit, I observed that there seems to be many factors, that affect the workspace, that ends-up being opened. In no particular order: 
 - A) workspace provided at the command-line when starting the backend : ```yarn run start /path/to/some/ws```
 - B) "latest" workspace, saved in user's home directory (e.g. in ```~/.theia/recentworkspace.json``` on Linux), updated each time a client is closed/restarted.
 - C) workspace currently being used by a pre-existing client
 - D) workspace already being used by a given client, when restarting that same client, is re-set
 - E) workspace apparently "remembered" by the backend, that was recently used by a client that is now closed, even if ```~/.theia/recentworkspace.json``` is erased, if the backend was not restarted since
 - F) until recently we had an additional wildcard: a timing bug would sometimes have Theia open with no workspace, when it should have opened with one. Upon client reload, that situation would correct itself.  (see: https://github.com/theia-ide/theia/pull/1846)

In the absence of all these factors, Theia starts without a workspace. If we make sure to insulate a single one factor, the intuitive thing seems to happen. The question is, when a mix of those factors is present, which do we expect should "win"? This is not always obvious. 

> 1- Web browser: already open in a workspace
[...]
5- Select the refresh workspace from the web browser
Note: Since the user initiated the application specifying a new workspace, as an end-user, I would expect that the "localhost:3000" would show me the new workspace when I refresh the browser (Not the case here)

This seems to assume that A should have priority over D? I think it should be the reverse, and that A should only provide a default, e.g. for the workspace server case, so that the user does not need to manually open a workspace that was already pre-populated for them by the workspace server, the first time that workspace is used. 

If the reverse was true (if A had priority over D), we following could happen: 
- Start Theia Backend specifying a workspace
- Start a few clients that connect to that backend
- In each client select a different workspace, e.g. simulating working on different tasks / repos
- Restart each client
- They all restart on the workspace specified in the first step

> 6- Even If I modify the old workspace, it will refresh it if that workspace still exist !!!!

It's not clear to me what this means? 

> 7- Now close the web browser with the old workspace (just the workspace page) the browser has other pages available
8- Open the web browser to localhost:3000
-> Re-open the old workspace instead of the workspace specified when I started Theia !!!

This might be because currently B has priority over A? This behavior seems ok to me. I guess I see A as a last-chance fallback, in case no worthy workspace can be found in any other way.

**Comment by JonasHelming** [comment]
Question was answered, closing this. Please reopen if you have any follow up questions!
