### ISSUE TITLE
undo/redo does not work in inputs and textareas

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#1867]
Use a git commit message input to reproduce.

**Comment by epatpol** [comment]
Here's what happens with vscode. If you type in an input box (ctrl-shift-f) for instance, go back to an open editor, type something else, then go back to the input box, pressing undo/redo will undo the text you changed in the monaco editor and even after that, you can't undo what you typed in the input box. Shouldn't monaco commands only work when you have the editor focus (context)? I know vscode doesn't do it this way, but I'm not sure if it's the best way. Otherwise maybe modifying the input boxes should add something to the undo/redo stack...

**Comment by akosyakov** [comment]
Hit it twice this week, very annoying to lose content :(

**Comment by akosyakov** [comment]
It was resolved.
