### ISSUE TITLE
[question] How can we distinguish two files with identical names?

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#1980]
How can we distinguish two files with the same name?
i.e. When I open the workspace/settings.json, I can see the file from the workspace navigator gets highlighted, but what about the user setting.json file gets opened right after, It is under the user home folder/.theia, but if I opend the two settings, the end-user see no selection for the user preferences from the navigator, the selection remains the last selection.  I only see two files with the same name in the editor.

**Comment by kittaakos** [comment]
Try to hover over the editor tab. I hope this helps.

![screencast 2018-05-29 10-19-24](https://user-images.githubusercontent.com/1405703/40646601-ec1a7846-6329-11e8-9135-53428ffb4bb5.gif)

**Comment by lmcbout** [comment]
Thanks @kittaakos It shows he name OK
What about the highlight in the navigator, when you select a file, it is highlighted in the navigator, but when the second file is not visible (i.e. .theia/settings.json), it keeps the last file selection in the navigator, shouldn't we not highlighted the selection then ?

**Comment by kittaakos** [comment]
> shouldn't we not highlighted the selection then

+1 for not removing the selection.

Let's put this differently: would you remove the selection from the navigator after closing the last opened editor. I would not.

Here is another use case: Let's imagine the user can open a temporary text file in an editor. (One can do this in VS Code with the <kbd>Ctrl/Cmd</kbd>+<kbd>N</kbd> binding or with `New` > `General` > `Untitled Text File` in Eclipse.) This would be cool because I could use Theia to add my notes to a file which I might save later or not. When selecting this file in the editor (please keep in mind, it does not yet have the corresponding resource in the FS) would you remove the selection from the navigator?

I am OK with the current behavior, and I am expecting the users to understand this but if the majority is up for changing this, then let's change it.

**Comment by vince-fugnitto** [comment]
@lmcbout can the issue be closed thanks to the fact we display the complete path when hovering over the tabbars, as well as the PR #5775 ?

**Comment by lmcbout** [comment]
Yes, I am closing this issue since it was fixed by PR #5775
