### ISSUE TITLE
Consider gRPC / protobufs for messaging

### ISSUE THREAD

**Issue by thegecko** [eclipse-theia/theia#2003]
I've created an example of using gRPC messaging over IPC or WebSockets:

https://github.com/thegecko/hyperion

What are people's thoughts around implementing frontend/backend messaging in theia using this approach in addition to/instead of JSON-RPC?

Pros

- Services and messages are defined using a simple and agreed definition language. This promotes contract-first development decoupling client and service implementations and dependencies between them.
- Messages are encoded into small binary packets, making them faster to transmit across networks.
- Services and messages are strongly-typed (where languages support this) promoting compile-time checking of service usage and template generation through abstract classes.
- Services can support streamed request and response messages which allow large amounts of data to be transferred without excessive buffering.
- Messages can be easily passed/proxied to services implementing gRPC without decoding or transformation.

Cons

- The overhead of encoding/decoding messages into their binary representations may have a negative impact on IPC performance. This has yet to be tested and could be mitigated by passing messages un-encoded.

@svenefftinge @gorkem @marcdumais-work @dneary

**Comment by svenefftinge** [comment]
I think the streaming could come in handy, e.g. for transmitting large document buffers. 
Otherwise, I am interested in comparing performance based on current use cases. 

FWIW, our current approach is statically typed, too. Also, it is a little simpler as we define the types in the language we use (TypeScript). Furthermore, we can simply reuse the type definitions from LSP and DAP. 

If I understood correctly, with gRPC we would have to redefine everything in protobuf, and then add a code generation process to our tool chain. Correct?

@akosyakov what do you think?

**Comment by thegecko** [comment]
@svenefftinge, it would likely need some code generation. The `protobufjs` library does allow you to load `.proto` files on the fly, but you have less control. A change like this needs careful consideration regarding its benefits as it will likely be quite impactful.

**Comment by akosyakov** [comment]
Closing: 
- we use ws compression to send binary messages under the hood. 
- we have a way to define statically typed interfaces over json-rpc
