### ISSUE TITLE
Unable to access electron features

### ISSUE THREAD

**Issue by thegecko** [eclipse-theia/theia#2162]
We have a need to access the execution path of Theia when running in electron using the following method:

```typescript
    import { app } from 'electron';
    console.log(app.getAppPath());
```

The expectation is that the electron environment is available to an electron backend as mentioned in the [extension README](https://github.com/theia-ide/theia/tree/master/packages/extension-manager).

This works as expected in a debug scenario, however fails to work when running the application standalone.

Investigation has shown this is due to the use of the [Node.js cluster module](https://nodejs.org/api/cluster.html) which is [disabled when debugging](https://github.com/theia-ide/theia/blob/master/.vscode/launch.json#L26).

Short of disabling clustering in the target application, is there a recommended way of achieving electron environment access? I was expecting to see something using IPC, but can't see any example of this in the codebase.

Thanks!

**Comment by kittaakos** [comment]
I am aware of one single IPC message between the backend and the client; please check your generated `/theia/examples/electron/src-gen/backend/main.js`:
```js
// ...
address.then(function (address) {
    if (process && process.send) {
        process.send(address.port.toString());
    }
});
// ...
```

and the generated `/theia/examples/electron/src-gen/frontend/electron-main.js` module:
```js
// ...
const cp = fork(mainPath);
cp.on('message', (message) => {
    loadMainWindow(message);
});
// ...
```

**Comment by thegecko** [comment]
Thanks.

OK, so the inability to access electron from the backend of an electron extension is expected?

Forgive me if I'm missing something, but I'm having difficulty creating a mental map of this.

It would be really useful if the [architecture docs](https://docs.google.com/document/d/1aodR1LJEF_zu7xBis2MjpHRyv7JKJzW7EWI9XRYCt48/edit) could reflect these models.

**Comment by akosyakov** [comment]
Hi, ideally we would allow it, but while working on the dynamic extension system we had to separate (via the cluster module) the server code to allow install/uninstall extensions at runtime, for example that we don't kill the existing server if a new is not good. Unfortunately, a forked process does not have an access to electron APIs, it is plain node process with some flags.

My mental map looks like that: `electron (cluster) main process` (manages server workers) --> `server worker process` (run actual server code)

There is a possible solution to the issue to spawn a new electron process for each server worker instead of using the cluster module but it will involve reimplementation of things already done by the cluster module.

For now if you are not interested in the dynamic extensions you can indeed use `--no-cluster` mode. Or you can try to spawn a new electron process from an extension. It is a way, for example, how vscode extensions try to access electron apis: https://github.com/Microsoft/vscode/issues/3011#issuecomment-184402806

**Comment by thegecko** [comment]
Thanks for the explanation.

In this specific case, we need to know where electron is being executed from so that we can run other installed binaries installed with our application. 

I can see the need to access the other [electron app methods](https://electronjs.org/docs/api/app), too. Perhaps this object needs to be exposed to the worker processes?

**Comment by thegecko** [comment]
Ironically it seems electron app methods are available in frontend modules via [electron.remote.app](https://electronjs.org/docs/api/remote), however it seems non-sensical to pull data through to the frontend only to send it back to the backend!

**Comment by thegecko** [comment]
@kittaakos

**Comment by tsmaeder** [comment]
@thegecko does __dirname or __filename not let you find out where your extension is installed?

**Comment by thegecko** [comment]
Probably, but we got round this somehow years ago ;)
