### ISSUE TITLE
[git] pull and push actions are pretty hidden

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse-theia/theia#2194]
Important Git actions like _pull_ and _push_ are really well hidden behind that `...` button.

I know it's the same as in VSCode, but this is also a reason why I use a separate Git tool instead when doing local development.

Maybe it's already enough to use a more Git-specific icon, like a git fork. 
Or have two separate menus for local actions (amend and sign off) and ones that interact with a remote (pull, push, fetch, merge).

**Comment by vince-fugnitto** [comment]
I do not believe there are any plans for the framework to deviate from vscode's implementation, especially since the framework should support plugin scm providers which contribute to following contribution points:

![image](https://user-images.githubusercontent.com/40359487/109694591-fb657180-7b58-11eb-9765-e82b5a03d780.png)

If the idea is to update the toolbar items, it would likely need to be customized through a custom extension instead.
_Note_: commands are always available through the command palette as well.
