### ISSUE TITLE
[terminal] Alt+W doesn't close terminal

### ISSUE THREAD

**Issue by MarkZ3** [eclipse-theia/theia#2217]
Theia master as of (603fe22), Electron, browser example. Ubuntu.

If I open a terminal and then try to close it with Alt+W, it doesn't close it, even though that's the keyboard shortcut displayed in the context menu of the tab.

**Comment by simark** [comment]
The keyboard shortcut is caught by the terminal and sent to the process running in the terminal.  I don't think we should change that if we want our terminal to act as much like a "real" terminal as possible.  Otherwise, somebody will come and complain that alt-w closes the terminal, when they want to send alt-w to their terminal application.

Would it be good if we didn't show the keyboard shortcut for the terminal widget (if that's even possible)?

**Comment by MarkZ3** [comment]
In gnome-terminal, I can do ctrl+shift+w to close a tab. I would like to be able to close a terminal especially since is easy to end up with multiple ones.

**Comment by marechal-p** [comment]
On Firefox <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>w</kbd> closes every tab. From my test it is not the kind of shortcut that can be intercepted...

**Comment by MarkZ3** [comment]
Sorry, I didn't mean that we should use that shortcut in particular, but rather that the functionality should be viable.

**Comment by FernandoAscencio** [comment]
Currently, the command does not have an assigned keybinding.
Assigning one Seems to work in Electron in Windows
![Issue2217](https://user-images.githubusercontent.com/48699277/235249612-2968ad4e-c358-4be4-94ee-953c8b75331e.gif)

**Comment by vince-fugnitto** [comment]
I believe the issue can be closed.
