### ISSUE TITLE
Proposal: apply list Theia plugins to the About window.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-theia/theia#2427]

**Comment by vince-fugnitto** [comment]
I don't believe this is necessary any longer?

The `About` dialog should be one of the first elements an application would customize as the base dialog does not display any relevant information for end-users for an app. Also, since we have the `plugin` view and eventually replace it by the more useful and informative `registry view`, displaying the list of plugins in the `About` dialog is unnecessary.

Please feel free to re-open the issue if you disagree.
