### ISSUE TITLE
[java] Go to Definition works only for JDK classes

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#2930]
It works for `Map`, `String`.

It does not work for classes in the workspace, such as `PreferenceManager`.
It does not work for other dependencies, such as `CompletionItem`, `IProgressMonitor`

**Comment by tsmaeder** [comment]
Context? Steps to reproduce?

**Comment by kittaakos** [comment]
This happened with Theia `master`, and my workspace root was the [jdt.ls](https://github.com/eclipse/eclipse.jdt.ls) repository.

**Comment by DamMicSzm** [comment]
Go to function definition or go to function declaration don't work for c ++. The other "go" similar. It's a pity because it's one of the better features in vscode.

**Comment by msujew** [comment]
@DamMicSzm Do you mind opening a separate issue for this? Ideally with a few more informations, i.e. which Theia version you're using and which extension for cpp support.

I'll close this, since the original issue is quite outdated; we don't deliver native Java support anymore and just use VSCode extensions instead.
