### ISSUE TITLE
Add dialog in theia

### ISSUE THREAD

**Issue by ankitmithu007** [eclipse-theia/theia#2959]
I am working on a project in which we are using theia as an IDE with eclipse che.
There is a requirement where I have to add a dialog(pop up for creating a new project) in theia.
I looked into the [documentation](https://www.theia-ide.org/) but couldn't find much except that you guys are using Phorphorjs.
Can you please provide some documentation or code link to achieve my requirement?
Please let me know if I was not clear enough to explain my requirement. 

Thanks.

**Comment by akosyakov** [comment]
@ankitmithu007 Hi, Theia has its own base class to implement dialogs: https://github.com/theia-ide/theia/blob/38ca484cab170b92ff6a6f4ff6efb7e2c03b3e80/packages/core/src/browser/dialogs.ts#L55

A good starting point to look at its implementations and usages.

**Comment by ankitmithu007** [comment]
Thanks @akosyakov .
After looking into the code, I was wondering why theia is not using any web framework like angularJs or React to contribute to the frontend.
This way it would reduce developer work for handling cases like updating the UI in case of any change (taken care by two way binding in angularJs) and also make the code more readable.

With the present code is there any way to use web framework(angular or react) in theia?
If it's already in theia , can you please provide a link.

Thanks.

**Comment by akosyakov** [comment]
A Theia widget is agnostic to JS frameworks and basically an HTML node with lifecycle hooks. It allows extension developers to pick whatever JS framework they want to implement widgets and make sure that Theia UI does not get obsolete in a couple years.

Widgets in this repo are implemented with pure HTML or React. We did not go with Angular because it is much more than just a UI framework.

There is a base class for React widgets: https://github.com/theia-ide/theia/blob/ee1eb3e619b7fd2024cac5d417684e039e3a74cd/packages/core/src/browser/widgets/react-widget.tsx#L24  Look at `onUpdateRequest` method. Widgets should implement rendering in it.

With dialogs it is a bit trickier because the base class is React independent, nevertheless nobody stops you to render using React in subclasses. Look for example at how `FileDialog` does it: https://github.com/theia-ide/theia/blob/ee1eb3e619b7fd2024cac5d417684e039e3a74cd/packages/filesystem/src/browser/file-dialog/file-dialog.ts#L160-L171

**Comment by ankitmithu007** [comment]
Sorry for late reply.
I went through the code and got a good understanding of ReactRenderer and ReactWidget class.
But what I am trying to achieve is a little complex with  the present design.

Let's take a step back here and let me try to explain my requirement.
I want to develop a dialog and the content of the dialog should be a [React.Component](https://www.tutorialspoint.com/reactjs/reactjs_components.htm)(the [way ](https://www.tutorialspoint.com/reactjs/reactjs_forms.htm)we create in React).
As it is React.Component , I can use this.setState() to render the UI if anything changes instead [this.render()](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/widgets/react-renderer.tsx#L33)

For simplicity , I have taken a example where I have text box and a text area which displays the textbox content.
I am trying to achieve this with the below code.
Due to some reason it's not working.


```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Disposable } from '@theia/core/src/common';

export class CustomReactRenderer extends React.Component<any,any> implements Disposable {
    readonly host: HTMLElement;
    constructor(
        host?: HTMLElement
    ) {

        super({});  // tslint:disable-line
     
        this.host = host || document.createElement('div');
    }

    dispose() {
        ReactDOM.unmountComponentAtNode(this.host);
    }

    render(): React.ReactNode {
        ReactDOM.render(<React.Fragment>{this.doRender()}</React.Fragment>, this.host);
        return;  
    }

    protected doRender(): React.ReactNode {
        return undefined;
    }
}
```

```
import * as React from 'react';
import { CustomReactRenderer } from './custom-react-renderer'


export class FileContentRenderer extends CustomReactRenderer {

    constructor() {
        super();
        this.state = {
            data: 'Enter file name'
        }
    }
    private updateState(e) {
        this.setState({ data: e.target.value });
       /**
        If I use the below code it's working.
       this.state.data = e.target.value;
        this.render();
       But I want to update it through this.setState()
     */
    }


    protected doRender(): React.ReactNode {
        return <div>
            <input type="text" value={this.state.data}
                onChange={this.updateState.bind(this)} />
            <h4>{this.state.data}</h4>
        </div>
    }

}
```

```
import { inject, injectable } from 'inversify';
import { Message } from '@phosphor/messaging';
import { AbstractDialog, DialogProps, DialogMode, DialogError } from '@theia/core/lib/browser';
import { FileContentRenderer } from './file-metadata-renderer';

export const ABOUT_CONTENT_CLASS = 'theia-aboutDialog';

@injectable()
export class ProcedureFileDialogProps extends DialogProps {
    readonly initialValue?: string;
    readonly validate?: (input: string, mode: DialogMode) => DialogError;
}

@injectable()
export class ProcedureFileDialog extends AbstractDialog<string> {

    protected readonly okButton: HTMLButtonElement;
    protected readonly fileContentRenderer: FileContentRenderer;

    constructor(
        @inject(ProcedureFileDialogProps) protected readonly props: ProcedureFileDialogProps
    ) {
        super({
            title: props.title
        });
        
        this.fileContentRenderer = new FileContentRenderer();
        this.contentNode.appendChild(this.fileContentRenderer.host);
        this.appendAcceptButton('Ok');
    }


    protected onUpdateRequest(msg: Message): void {
        super.onUpdateRequest(msg);
        this.fileContentRenderer.render();
    }

    get value(): string { return ''; }

}
```



```
Error:
root ERROR Warning: Can't call %s on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the %s component. setState FileMetadataRenderer
```

I am new to react so maybe I would be making silly mistake
Please let me know if I was not able to explain myself.

**Comment by ankitmithu007** [comment]
Any update, please.

**Comment by vince-fugnitto** [comment]
@ankitmithu007 sorry for the late reply, are you still experiencing issues?
I believe you might have more luck and info by reading up on React documentation directly as it looks to be more a generic React question.

**Comment by SOWMITHRACHINNADURAI** [comment]
I am trying to create the New text field using theia.For that i am trying to use 'SingleInputTextDialog' present in '@theia/core/src/browser/dialogs.ts' . But it does'nt work for me.Can you please provide some suggestion to work on it?

Thanks

**Comment by vince-fugnitto** [comment]
> I am trying to create the New text field using theia.For that i am trying to use 'SingleInputTextDialog' present in '@theia/core/src/browser/dialogs.ts' . But it does'nt work for me.Can you please provide some suggestion to work on it?
> 
> Thanks

@SOWMITHRACHINNADURAI 
What kind of problems are you experiencing? Are you trying to trigger the `SingleInputTextDialog`, or are you attempting to extend it and create a new type of dialog?

**Comment by tschanni** [comment]
Hey, for a project I need to implement a new dialog which appears when the user want to leave the page (when the unload Event is triggered). It should say something like "Do you really want to leave the page?" - Yes/No, through the contribution I found some helpful places in the source text. 
But im running in some problems when I try to think about Implementation, because the project is kinda overwhelming for a newbie .. 

To specify my questions:
- I tried to inject the saveable class to build my own dialog - is this the right way or is there a better class to build the dialog ?
- how can I trigger than my unload event ? 
- Do I need React to render the Dialog field, the further conversation confused me a little bit. 

hope someone can help me :)

**Comment by msujew** [comment]
This issue is pretty outdated. In case anyone has more questions regarding dialogs, please feel free to create a GitHub discussion.
