### ISSUE TITLE
Animating background for tree nodes

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-theia/theia#3450]
Now expanding of tree nodes works asynchronously and it is not clear how long it needs to wait until the children appear. It's looks strange when the user click on tree node, arrow on this node has been changed on opened but children appears with some delaying.
Let's see how expanding of tree nodes works with [tree-sample-plugin](https://github.com/eclipse/che-theia-samples/tree/master/tree-view-sample-plugin) provides ftp-explorer widget.

![expanding-tree-nodes](https://user-images.githubusercontent.com/1655894/47920292-5ff56080-deba-11e8-895f-a46128f87cdf.gif)

In this example the opening time depends on the speed of the network and may take some time.

The proposal is to add animation to the background of the tree node when it's fetching the children.

We did something similar for our Che IDE. Let's see how it looks

![animation when expanding tree nodes in che ide](https://user-images.githubusercontent.com/1655894/48257417-291fcd00-e41b-11e8-8525-69f7dcbec81e.gif)

The same video https://youtu.be/RYAopXBC0HU

The styles for the tree node may look like styles for Che IDE

https://github.com/eclipse/che/blob/master/ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/smartTree/TreeStyles.css#L144

**Comment by akosyakov** [comment]
I like an idea of displaying loading, especially when a connection is lost. Also if loading is failed it would be nice to show a reason, maybe as a child error node.

Not sure about the animated background. It could be also a child node with a spinning loading indicator which either resolves to real children or to an error node.

//cc @svenefftinge

**Comment by akosyakov** [comment]
Displaying resource resolution is not specific to trees. There can be different resources opened, not necessary from the navigator. In VS Code one can report progress as the blueish bar running at the top of the main area, maybe we can make use of something like that for Theia as well.

**Comment by vitaliy-guliy** [comment]
What shall we do when node has no children? Adding and then removing temporary node may look KO.
I have just tried to play with VS Code but cannot see blue bar.
When use animation we can add a simple delay on start. Then it will not be displayed when children appear immediately.

**Comment by vitaliy-guliy** [comment]
Another issue. What shall we display when tree is opening root nodes?

**Comment by vitaliy-guliy** [comment]
I would like to try a version with animated background as a cheapest option. And then decide how good it looks.

**Comment by akosyakov** [comment]
> I have just tried to play with VS Code but cannot see blue bar.

I am not sure what is triggering it in VS Code. I see it from time to time. It looks like here, only in the main area: https://github.com/Microsoft/vscode/issues/50730#issuecomment-393116274

> Another issue. We have to show something when tree is opening root nodes?

With the progress bar, we can run it till there is no content.

**Comment by vince-fugnitto** [comment]
@vitaliy-guliy  @akosyakov  I really like the `FTP Explorer` styling with the title band and icons, is it something we can easily update our `Files` widget to? I'm also thinking of adding buttons to the band for the `Files` view to have for instance a `Collapse All Nodes` feature.

**Comment by vince-fugnitto** [comment]
@vitaliy-guliy yes exactly `vscode` does something quite similar. I'll see if I can somehow adopt to our `Files` view, I really like the feature and UI for it :)

**Comment by akosyakov** [comment]
@vince-fugnitto please discuss it with @svenefftinge first, it was not done on the purpose to have more space and avoid duplicate title (we have a title already in the sidebar).

For `collapse all` action we can add a menu item which is available on all nodes.

**Comment by vince-fugnitto** [comment]
@akosyakov thanks and I agree that we save some space but I was also thinking in the case that we display icons rather than titles in the sidebar (https://github.com/theia-ide/theia/pull/2867). Perhaps in such a case we'd want to display widget titles within the widget themselves for easier identification.

**Comment by svenefftinge** [comment]
The toolbar contributions are really useful and it somehow odd, that we don't show them for widgets attached to the side panels (because we don't know where to render them). 
If we go with the VS Code way, of having Icons in the vertical tabs, a hover showing the full label and a first row with the label followed by the tool bar icons this would be solved. Given that people have asked for the icon option over time, we might just go down that path and make it the default.

**Comment by svenefftinge** [comment]
Regarding this issue, I'd prefer to look into a general way of reporting progress. Also because we need to support the VS Code Api in our plug-in system I'd say it makes sense to go with a similar approach. I.e. show progress on top of a widget.

**Comment by vitaliy-guliy** [comment]
We can support the VS Code API and do whatever we want with Theia UI.
Having a general way of reporting the progress it's certainly good. But then in a case with the tree we need to connect it somehow with a parent container and this container must have the API to display a progress.
Let's describe which progress we have to track:
- loading folder content in the tree
- loading file content on double click tree node
- something else??

I think having some animation in the tree is enough for now.

By the way, I don't see that VS Code API describes the way to display a progress inside view.
But it describes `window.withProgress(...)` method to display a progress on top of the window.

**Comment by svenefftinge** [comment]
So we are in agreement that it would make sense to implement it similarly to VS Code?
I think that's the way to go, because
 - we would need to support the VS Code API anyway
 - the VS Code extension implementation has a certain expectation to how the UI does it.
Also, I think it just works nicely. So no need to do it different.

**Comment by akosyakov** [comment]
The blue progress bar is available already. We are going to add loading spinner for any tree to align with VS Code UI.

![36672590-1e8e5cb0-1b00-11e8-99b8-74aa7b2d2645](https://user-images.githubusercontent.com/3082655/75240210-47523d80-57c4-11ea-87b4-5f491db7af4d.gif)

It will be shown on `Tree.resolveChildern` after some configurable delay. It could be disabled by setting delay to 0.

**Comment by westbury** [comment]
> It will be shown on `Tree.resolveChildern` after some configurable delay. It could be disabled by setting delay to 0.

@akosyakov That looks like https://github.com/eclipse-theia/theia/pull/5535.  At the time I was holding off as other progress work was being done and I never got back to it.  Our use-case was slightly different, as we wanted the progress indicator to be active when certain context actions are unavailable on a tree node, eg a tree node representing a project that is being built.  If you have this in hand then I will close the PR, otherwise I will resurrect it and ensure it covers this issue.

**Comment by akosyakov** [comment]
@westbury ok, thanks for reminding, i need quite urgent for the customer, so planing to work myself. I will have a look at your PR though.
