### ISSUE TITLE
Menu action "Find in Folder..." should not be visible for files

### ISSUE THREAD

**Issue by adi7ya** [eclipse-theia/theia#3614]
Currently, this option is visible even when we right click on a file. I was trying to figure out a way to remove this command for files by overriding the isVisible method of the handler for this command. I tried to obtain the FileStat of the URI and then determine if it is a directory in following manner:
```
const stat = await this.fileSystem.getFileStat(uri);
if (stat.isDirectory) ...
```
But because of the async nature of filestat, I'm not able to do this in isVisible. 

Is there any way, we can disable this command in case of files? I'm new to theia so please correct me if my understanding is wrong. And please tell me if you need more information to better understand the issue.

**Comment by adi7ya** [comment]
Currently, when we click on this menu item for a file, we are getting wrong results for search because we are appending '/**' even to files in findInFolder method of SearchInWorkspaceWidget. The closest I'm to fixing this for files is by applying this check for directory in the execute of the handler, which is async, and then pass appropriate argument to findInFolder method from there.

@vincent-fugnitto , @jbicker please share your input.

**Comment by vince-fugnitto** [comment]
My understanding is we cannot do any `async` call from within `isEnabled` or `isVisible`.

In order to fix the issue we should probably enhance the `FileNavigator` nodes to also contain their `FileStat` so we have access to more functionality.

A quick alternative is when calling `execute` from a file for `Find in Folder`, we search from it's closest parent.
