### ISSUE TITLE
Custom Syntax Highlighting

### ISSUE THREAD

**Issue by Sandared** [eclipse-theia/theia#3684]
It would be nice to be able to customize the syntax highlighting for any language, e.g. for Java so that I can configure the same syntax highlighting as in my previously used IDE (Eclipse ;) ) 
I think this would be better for onboarding new users that come from a different IDE and are used to the specific syntax coloring.

**Comment by vince-fugnitto** [comment]
For some information, the framework supports syntax-highlighting and grammars from vscode extensions.
In order to customize syntax highlighting for a language, a vscode extension will need to be implemented using the [guide](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) and consumed from a custom application.
