### ISSUE TITLE
Julia Language Extension

### ISSUE THREAD

**Issue by virtualgraham** [eclipse-theia/theia#3982]
I have built a Theia extension for Julia using the Julia Language Server and grammar files from the Julia VS Code extension. https://github.com/virtualgraham/theia-julia-extension

It would be great if this was available under the @theia package namespace

**Comment by vince-fugnitto** [comment]
Hi @virtualgraham, thank you for the initiative.
Unfortunately it looks like the issue may have gone unnoticed (under the radar).
Please note that the VS Code extension support for Julia should work out-of-the-box already.

**Comment by vince-fugnitto** [comment]
Unfortunately, there are no plans in supporting and maintaining a language extension for the team (due to bandwith a priority). The long term goal is to replace existing language extensions with their VS Code counterparts (since they provide additional language features and will not need to be maintained directly by us). Therefore, the goal is to re-use the [`julia extension`](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia) from VS Code. We appreciate the initiative :)
