### ISSUE TITLE
scrolling inside Monaco editor navigates the browser

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4059]

**Comment by akosyakov** [comment]
Actually, it is reproducible even for the editor.

@spoenemann Maybe you can have a look? I remember you fixed it last time.

**Comment by spoenemann** [comment]
Maybe an update of Monaco led to a different DOM structure. I implemented the fix for #1860 with a hard-coded analysis of the DOM:

https://github.com/theia-ide/theia/blob/096f2a3fb5e8c92e6d7a3023b39aabb9df7f32f2/packages/core/src/browser/browser.ts#L88-L103

We should at least update that code, but maybe we can find a more general solution?

**Comment by akosyakov** [comment]
it works for @svenefftinge 🙈 maybe it is just some 3rd party chrome extension which breaks it for me

**Comment by JonasHelming** [comment]
I have never experienced this issue. @tsmaeder : You recently tested the editor a lot I guess, shall we close this one?

**Comment by tsmaeder** [comment]
Works for me 🤷

**Comment by JonasHelming** [comment]
closing this, please reopen if it occurs again
