### ISSUE TITLE
When I build my own ide, I report errors.

### ISSUE THREAD

**Issue by bj-white** [eclipse-theia/theia#4454]
When I build my own ide, run "yarn theia build", the shell gets stuck.

**Comment by bj-white** [comment]
[root@white my-app]# yarn theia build
yarn run v1.13.0
$ /root/my-app/node_modules/.bin/theia build

**Comment by marechal-p** [comment]
You could try to debug the script and see where it gets stuck.

Using the following line, you should be able to hook a node remote debugger on the build script process:

```sh
node --inspect-brk /root/my-app/node_modules/.bin/theia build
```

**Comment by bj-white** [comment]
@marechal-p [root@white my-app]# node --inspect-brk /root/my-app/node_modules/.bin/theia build
Debugger listening on ws://127.0.0.1:9229/a8e4935b-2063-43d4-955d-8ad0ac4feaf9
For help see https://nodejs.org/en/docs/inspector
why?Thank you.

**Comment by marechal-p** [comment]
Because unfortunately I have no idea what to tell you to try, other than identifying yourself the cause of the process hanging and then report back.

See the following page on how to use VS Code in order to attach to a running Node.js program:
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_attaching-to-nodejs

Just make sure to open Theia's sources you are trying to build when attaching the debugger (to see what is happening where).

**Comment by bj-white** [comment]
@marechal-p I can't.
Can I download the packages I use and upload them to linux using ftp?
Do you have the address of the package?

**Comment by marechal-p** [comment]
Please reopen if you are still having issues.
