### ISSUE TITLE
Preference to toggle between tab scrolling and shrinking-to-fit

### ISSUE THREAD

**Issue by stuartpb** [eclipse-theia/theia#5085]
#1445 changed the behavior for tabs for files with long names to extend the width of the tab bar, rather than shrinking the tab so all the bar's tabs can fit in the bar.

Can we get a preference to re-enable the old behavior? I have a workspace where I have to open a lot of files with long, arbitrary UUIDs for filenames, and the "expand tab length" behavior is much less useful than shrinking the tabs to fit would be.

**Comment by vince-fugnitto** [comment]
I guess the main idea is to support creating tabs like in a browser (shrink the available tabs so they are always present and there is no need to scroll). I can understand why some would want this feature (no need to scroll), but it also might be considered bad UX since tabs will not be easily distinguishable when there is a lot of files opened. 

At the moment, the easiest approach to view all opened editors, is to run the command 
`View: Show All Opened Editors` like below:

<div align='center'>

<img width="1370" alt="Screen Shot 2020-02-17 at 11 44 41 AM" src="https://user-images.githubusercontent.com/40359487/74672306-f8c8f180-517a-11ea-92a9-4afd243eed36.png">

</div>

If this is a feature you need in your own product, please feel free to open a pull-request.

**Comment by stuartpb** [comment]
What'd be best would be to have the hybrid behavior seen in Firefox, where tabs shrink until they reach a certain size, *then* they start scrolling.

**Comment by tsmaeder** [comment]
This is implemented.
