### ISSUE TITLE
Compare theia vs. code-server?

### ISSUE THREAD

**Issue by pwFoo** [eclipse-theia/theia#5347]
How do theia compare / differ to https://github.com/cdr/code-server?

**Comment by akosyakov** [comment]
Theia is an extensible IDE Framework with cloud-first mindset not a patch to electron and VS Code source code to run it in a browser as code server. Theia does provide similar UX and compatible with VS Code extensions but relies on stable components and protocols like Monaco, LSP, DAP and vscode extension api. Besides it is vendor neutral and allow to build white labeled products like Gitpod or ARM Mbed Studio.

**Comment by GalacticLion7** [comment]
Does Theia work better on iPadOS than code-server? If not, then they are effectively the same thing on iPadOS.

**Comment by tstibbs** [comment]
A comparison to codespaces would also be useful (yes, I realise that's probably uncomfortable because github codespaces compete with gitpod, which appears to fund most of the theia dev?). It would be interesting to see an architecture diagram of theia showing which bits are re-used from vscode and which are theia-specific.

@akosyakov your answer provides a comparison at a technical level, but from a out-of-the-box user functionality point of view, is there much difference?
