### ISSUE TITLE
[ui/ux][quick-open] Better icon support for the dark theme

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#5395]
Better support for the dark icons in the command palette. Do <kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd> to open the symbols.

Expected (VS Code):

![Screen Shot 2019-06-07 at 13 33 45](https://user-images.githubusercontent.com/1405703/59101680-078fb100-892a-11e9-93bb-28a0a8411190.jpg)
![Screen Shot 2019-06-07 at 13 34 01](https://user-images.githubusercontent.com/1405703/59101681-078fb100-892a-11e9-8dd4-b1af579ce782.jpg)

Actual (Theia):

![Screen Shot 2019-06-07 at 13 33 17](https://user-images.githubusercontent.com/1405703/59101688-14140980-892a-11e9-834c-109cfe5658f7.jpg)
![Screen Shot 2019-06-07 at 13 33 36](https://user-images.githubusercontent.com/1405703/59101689-14140980-892a-11e9-8107-c2d8c2ae5aa9.jpg)

**Comment by vince-fugnitto** [comment]
The following looks to be fixed in `master`, please reopen if its not the case:

![image](https://user-images.githubusercontent.com/40359487/71898000-2ce5d700-3126-11ea-805c-fb3ea9956a55.png)

![image](https://user-images.githubusercontent.com/40359487/71898038-471fb500-3126-11ea-8b98-0e8e12442a35.png)
