### ISSUE TITLE
Error while using inbuilt git provided by dugite (USE_LOCAL_GIT:false)

### ISSUE THREAD

**Issue by ankkumar-progress** [eclipse-theia/theia#5418]
### Description
I am trying to use the dugite inbuilt git in theia by USE_LOCAL_GIT:false.
But due to some reson I am getting the below error:

`Git could not be found at the expected path: '/home/theia/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging`

I checked the git is present in that location.

Due to some reason, I can't install local git due to license issue (GPL).
So I am bound to use the dugite inbuilt git.

**OS and Theia version:**
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.1
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"

Thiea: 0.3.14

**Comment by kittaakos** [comment]
> I am trying to use the dugite inbuilt git in theia by USE_LOCAL_GIT:false.

@ankkumar-progress, due to licensing issues, we [do not ship the embedded Git with `dugite`](https://github.com/theia-ide/dugite/commit/9b7f5314f68e9897e42c7e15cfb5a56e4073d615). See: https://github.com/theia-ide/theia/issues/4209

> So I am bound to use the dugite inbuilt git.

It won't work, unfortunately. You will need `git` on the `PATH` to be able to use the Git/SCM extension in Theia.

**Comment by kittaakos** [comment]
> Thiea: 0.3.14

@ankkumar-progress, I am not sure if it is possible with `0.3.14`, but with the latest API
 - You can create your extension that depends on `dugite`. Note, by default, it will download the executables on `postinstall`.
 - In your extension, you can rebind the default [`GitInit`](https://github.com/theia-ide/theia/blob/b7b8691c4ced43a40f4b96f758a3c215b2fca19a/packages/git/src/node/init/git-init.ts#L29-L36) implementation.
 - Make sure your implementation retrieves and sets the `LOCAL_GIT_DIRECTORY` and `GIT_EXEC_PATH` variables manually [instead of finding it from the `PATH`](https://github.com/theia-ide/theia/blob/b7b8691c4ced43a40f4b96f758a3c215b2fca19a/packages/git/src/node/init/git-init.ts#L57).

I hope this helps.

**Comment by ankkumar-progress** [comment]
Thanks @kittaakos 
I will give a try
