### ISSUE TITLE
alt + w close editor should not close other ui

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5487]
### Description
in theia close window
![temp](https://user-images.githubusercontent.com/10203793/59581158-95c41e00-9106-11e9-8ca9-3920e960f976.gif)

in vscode close window
![temp](https://user-images.githubusercontent.com/10203793/59581188-af656580-9106-11e9-8675-d1688cee0750.gif)

### Reproduction Steps
look gif

**OS and Theia version:**
**Diagnostics:**

**Comment by 502647092** [comment]
@akosyakov 
Can you solve this problem?

**Comment by akosyakov** [comment]
In Theia we don't treat editors somehow special from other shell widgets, so it works by design as for now. We need to discuss whether we want to change it. Also in VS Code everything in main area is an editor, so it is probably take into account other widgets, like previews, webviews. We need to investigate first what is the proper behaviour.
