### ISSUE TITLE
Multiroot support command 'Add folder to workspace' should be in the main menu File

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-theia/theia#5522]
### Description
When multiroot enabled We have  'Add folder to workspace'  command in the file navigator. **But it should in the menu File too**, like in the VSCode:
<img width="960" alt="AddFolderToWorkspaceVsCode" src="https://user-images.githubusercontent.com/6873095/59761183-c8a01a80-929c-11e9-9052-62dce82d7c2b.png">

**Comment by vince-fugnitto** [comment]
I know that in certain use cases the top-level menu item will not work properly, for example in the case of Electron. We are currently creating the menu items based on the preference `workspace.supportMultiRootWorkspace`, but this means that if a user enables/disables the preference, the Electron menu will not update (since we create the menu once).

I know it's a small enhancement (we already have the context menu and command), but if it's necessary, I guess others can live with the menu not appearing in Electron.

**Comment by vince-fugnitto** [comment]
@AndrienkoAleksandr  the command `Add Folder to Workspace...` has been added as part of the explorer's `More Actions...` toolbar menu. Is this sufficient?

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/64552607-96371400-d305-11e9-9dc5-e9a854f5e0d2.png)


</div>

**Comment by tsmaeder** [comment]
This is implemented, it seems.
