### ISSUE TITLE
[file-search] As a user I want exact matches to show up in file search

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#5636]
### Description
 
I cannot see `os.ts` in the file search when I search for `os.ts` in the workspace.

### Reproduction Steps

 - Open a workspace on the Theia source.
 - <kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>
 - Type: `os.ts`.
 - I cannot see `os.ts`.

Expected:
 - I can see `os.ts` among the items.

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
I did some testing and noticed that if we remove the limit we get much more consistent results, I believe we somehow never get to `os.ts` because we match more worse results and get to our limit.

https://github.com/theia-ide/theia/blob/20251eae573ae89f5cf3242131add17f0ef40956/packages/file-search/src/browser/quick-file-open.ts#L204-L210

Removing the limit gives me the following results:

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/60664138-1e44fd00-9e2f-11e9-846a-eb22ffde69a4.png)




</div>

**Comment by vince-fugnitto** [comment]
@kittaakos is the limit something we want to keep, else we will probably need to fix the file-search-service to return much better results initially.
