### ISSUE TITLE
Don't advise to run `yarn watch` in the root

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5778]
See for motivation: https://spectrum.chat/theia/dev/what-is-the-best-option-to-watch-for-changes~efc10195-0720-4765-b5c7-bc925c69e296

We should advise to work individual packages and one app. And provide an example of such workflow in docs.

**Comment by marechal-p** [comment]
Speaking of which, should we get rid of `npx run <command> <package>` and rather use `yarn workspace <package> <command>` ?

It does the same thing, and is less confusing (`npm run` vs `npx run` where `run` is `theia-run`...)

**Comment by akosyakov** [comment]
Does it support running the same task of all transitive dependencies? It looks more verbose btw, an idea behind `npx run` was to make it as short as possible.

**Comment by marechal-p** [comment]
If you mean like triggering scripts in arbitrary dependencies, then no it doesn't. If you are talking about workspaces within the current repo matching something like `**/meh/*`, then yes it does.

I would rather advocate using `yarn workspace` which is simple enough to understand and can be looked up online. Unlike `npx run` which comes from Theia and gets confused with `npm run` by new members that don't understand where this magical command comes from.

Unless the tool does more than just calling lerna, I don't see the point.

**Comment by akosyakov** [comment]
I mean https://github.com/theia-ide/theia/blob/master/doc/Developing.md#watch-a-specific-package-and-its-local-upstream-dependencies. I don't think `yarn workspace` can do it properly.

The point is not to type `yarn lerna run --concurrency=1` each time on windows for example.

> gets confused with npm run by new members that don't understand where this magical command comes from.

Whom are you talking about? Could you provide an issue that someone was confused?

**Comment by marechal-p** [comment]
TIL that lerna has a flag to do that, nice. And indeed `yarn workspace` doesn't handle this use case. Never had to do that before though, but if I do I'll know what to do :)

> Whom are you talking about?

Mostly people I was helping ramping up face to face, some are not npm experts and I had to explain them that one was an npm command, while the other was a script/bin contributed by Theia. It took me a while to realize as well in the beginning. The biggest issue is that people cannot lookup what this script does since we only document some usages like you provided, but not what it is doing nor where it is coming from (again, not obvious that it is a lerna shortcut).

From what I understand for the most simple cases, `yarn workspace` works, but for lerna based magic, `npx run` is the way to go. Just a matter of documenting a bit the tool itself maybe.

**Comment by akosyakov** [comment]
> TIL that lerna has a flag to do that, nice. And indeed yarn workspace doesn't handle this use case. Never had to do that before though, but if I do I'll know what to do :)

I usually don't use it for `watch`, but for `build` in order to avoid rebuilding everything. Actually yarn devs explicitly say that yarn is not replacement for lerna [here](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/):

> Lerna provides a lot more than just bootstrapping a project and it has a community of users around it that have fine-tuned Lerna for their needs.

Maybe yarn 2 will take more of lerna responsibilities. I'm always for cutting our dependency tree.

Ok, agree that `npx run` and `npm run` can be confusing, although removing or renaming it now will disturb workflow of active contributors now. We could consider to use another binary name not `run`, then you can also use call it with `yarn mybin`.

**Comment by akosyakov** [comment]
yarn watch does not spawn multiple process anymore, it is still slow, but it does not eat up all CPU
