### ISSUE TITLE
don't share event loop between windows when possible

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5857]
> All windows on the same origin share an event loop as they can synchronously communicate

from http://hassansin.github.io/shared-event-loop-among-same-origin-windows

As a consequence debugging in one window blocks all other windows for the same origin.

The obvious candidate is mini-browser. But we should review other places where we use `window.open` and pass `rel=noopener` when it makes sense, i.e. we did not need to communicate with an opened window.

**Comment by DanTup** [comment]
I wish I'd found this earlier - I've been debugging this most of the morning 🙈 The issue is when we hit a breakpoint in the web app, it causes GitPod to lock up and everything hangs.

I tested adding `'noopener'` as the third argument to `window.open` here and it solved my issue:

https://github.com/eclipse-theia/theia/blob/aff11bec2a0424a63e506613d9e23f2e6bdd1d42/packages/core/src/browser/window/default-window-service.ts#L44

However since this prevents it from returning a `Window`, it may make sense to change the interface to return `void` to avoid confusion (as far as I can tell, nothing is using the return value?).

**Comment by akosyakov** [comment]
@DanTup Could you send a PR please? Changing a return type is fine. I could not find any clients using the returned window object.

**Comment by DanTup** [comment]
@akosyakov I made a start, but I'm not getting very good errors in my IDE so I'm not sure if this is everything. I'm also not sure whether changing the `undefined`s to `void` throughout like this is desired?

https://github.com/DanTup/theia/commit/ce9c034393ead9f9c4369c5fd7a427e3a881b475

Does this seem reasonable?

**Comment by akosyakov** [comment]
>  I'm also not sure whether changing the undefineds to void throughout like this is desired?

`OpenerService` api should be changed, it is used to open anything, not only a window, e.g. editors, preview widgets and so on. In such cases a widget will be returned. But other places look fine to me.

**Comment by DanTup** [comment]
> `OpenerService` api should be changed

I presume there's a missing "not" there? I'll revert that then and use `undefined` instead of `void`.

Does it seem ok removing the error-throwing code in default-window-service since it'll always get an undefined return value now?

btw, I don't know if I can reliably test all of this locally.. I tested the `noopener` change on GitPod by just using the dev console to replace `window.open` with a wrapper that did passed this arg.
