### ISSUE TITLE
[core] add `Copy (Relative) Path` to the tab's context menu

### ISSUE THREAD

**Issue by fangnx** [eclipse-theia/theia#5937]
### Description
As a user, I would like to have `Copy Path` and `Copy Relative Path` options present in the tab's context menu. It exists in VS Code and it can be quite useful for programming/development in general.

**Comment by akosyakov** [comment]
Should it be also added to the navigator context menu?

**Comment by kittaakos** [comment]
> exists in VS Code

It should copy the platform-specific paths. This means, on Windows the result of the copy should be like these:

 - `Copy Path`: `C:\Users\kittaakos\dev\theia\examples\browser\src-gen\frontend\index.js`
 - `Copy Relative Path`: `examples\browser\src-gen\frontend\index.js`

Otherwise, Windows users cannot do much with the copied paths.

**Comment by kittaakos** [comment]
> navigator context menu

https://github.com/theia-ide/theia/issues/1344
