### ISSUE TITLE
Show progress in Explorer

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-theia/theia#5959]
As a follow-up of https://github.com/theia-ide/theia/pull/5830.

A progress indicator similar to git/scm could be useful.

**Comment by westbury** [comment]
See also PR https://github.com/theia-ide/theia/pull/5535.  That PR shows progress by an tree item and solves the problem of showing when individual items in a tree are 'in progress'.  We should make both available because in some cases the progress will apply to the workspace as a whole and if other cases progress will apply to a single item in the tree.
