### ISSUE TITLE
[fs-watcher] not support soft link watch

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5968]
### Description
fs-watcher not support soft link watch

### Reproduction Steps
![temp](https://user-images.githubusercontent.com/10203793/63205430-ab3dd000-c0d6-11e9-8915-3bfe1cc4465e.gif)

**OS and Theia version:**
git-commit: 9105c43ab

**Diagnostics:**

**Comment by akosyakov** [comment]
Unfortunately nsfw reports an event only for one symlink, not all :( We've decided to resolve all symlinks to real paths: https://github.com/theia-ide/theia/issues/2566#issuecomment-477478224 It covers most of the cases. But obviously we cannot report for all symlinks, since we don't have such information. Also see https://github.com/Axosoft/nsfw/issues/30, implementing it via indexing all symlinks will harm performance

**Comment by akosyakov** [comment]
As an idea we could try to preserver an information whether the given file node is a symlink or not and to which realpath and refresh it as well when an event is reported. I remember trying something like that but it would fix an issue only for the navigator and design was quite impactful to apis.

**Comment by havogt** [comment]
I probably encountered this bug with a gitpod setup. I didn't want to enforce `.theia/settings.json` for the non-gitpod users, so I decided to put the `.theia` folder in a subdirectory and create a symlink on gitpod init. The effect is that in the debug view, the launch selector doesn't get updated if a new configuration is added to the launch.json file.
Here is an example setup to reproduce: https://github.com/havogt/gitpod-playground.
Not high priority for me, as I solved the problem with hard links.
