### ISSUE TITLE
Parameter hints not working (for Python)

### ISSUE THREAD

**Issue by ziatdinovmax** [eclipse-theia/theia#6249]
### Description
As of yesterday, the parameter hints option in Gitpod does not work for Python. It doesn't get triggered automatically, nor I can trigger it with a keyboard shortcut. I was recommended on Gitpod forum to file an issue here.

### Reproduction Steps
Docker file:

```
FROM python:3.7

RUN  apt-get update && apt-get install --assume-yes python3-pip
COPY req.txt .
RUN  pip3 install -r req.txt
WORKDIR "/home"
```

req.txt:
```
setuptools==41.0.1
matplotlib==3.1.1
jupyterlab==1.0.1
pyro-ppl==0.4.1
nanonispy==1.0.6
```

.gitpod.yml:
```
image:
  file: Dockerfile
ports:
- port: 8080
```

**OS and Theia version:**
Theia on Gitpod

**Comment by vince-fugnitto** [comment]
Hi @ziatdinovmax, thanks for following up with the issue.
I may be mistaken, but based on the information provided in the issue, it appears to be more of a Gitpod issue than a Theia one. Perhaps someone from Gitpod can confirm.

**Comment by akosyakov** [comment]
@vince-fugnitto that's problem an issue with VS Code extension integration in Theia, not with Gitpod. @AlexTugarev maybe you can clarify?

**Comment by svenefftinge** [comment]
@vince-fugnitto Gitpod is Theia. There are very little changes and we are updating regularly.

**Comment by AlexTugarev** [comment]
<img width="459" alt="Screen Shot 2019-09-24 at 10 28 08" src="https://user-images.githubusercontent.com/914497/65494946-1fc61480-deb6-11e9-9c43-f177447a0ed6.png">

@ziatdinovmax I just verified, that this is working nicely with current master state of Theia, cf. my answer on spectrum.

FYI `python.jediEnabled` has to be set to `false` in order to use the new engine, and there was a bug in Theia which let it fail on load (https://github.com/eclipse-theia/theia/pull/6173)

I think we can close this issue :-)

**Comment by ziatdinovmax** [comment]
@AlexTugarev thank you!
