### ISSUE TITLE
Unknown actor StorageExt error

### ISSUE THREAD

**Issue by benoitf** [eclipse-theia/theia#6305]
### Description
When loading plug-ins, error is displayed in the browser console:

Uncaught (in promise) Error: Unknown actor StorageExt

![image](https://user-images.githubusercontent.com/436777/66021573-6daccf00-e4eb-11e9-9a5a-7fe11f252099.png)

### Reproduction Steps
Add bracket pair colorizer in plugins folder
https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer

**OS and Theia version:**
master branch

**Diagnostics:**

**Comment by AlexTugarev** [comment]
Was about to report the same issue. I think it's missing in plugin-context.

**Comment by raphaelsantos** [comment]
We are also running into this error with our vscode plugin, it started today.

**Comment by akosyakov** [comment]
It does not harm, but exception is annoying. I will do a PR. The issue is that we fetch plugin manager initialization data lazily in the meantime storage RPC on the main side gets initialized and tries to update the ext host side. But there is no storage service yet since the initialization of the plugin manager does not happen yet.
