### ISSUE TITLE
Content assistant for tasks.json is broken

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#6542]
### Reproduction Steps
Open `tasks.json` file and try to add a new configuration using `Ctrl + space`
https://youtu.be/JzM3ah9VRAE

Problems for invalid configurations are not displayed for me as well.

Please see expected behavior in the description of the [PR](https://github.com/eclipse-theia/theia/pull/6492) 

**OS and Theia version:**
Ubuntu 18.04.1
Theia version: d7f7c90376e3660f15149a2de8286d8d2b015c75

**Comment by vince-fugnitto** [comment]
The issue might have been present before, but it was made visible following the #6255.
I noticed that before the changes, the schema configs were working correctly, but now they are not. The PR #6255 simply updates the `yarn.lock` and dependencies to the versions that applications will likely pull when building their products and our `yarn.lock` was outdated.

**Comment by vince-fugnitto** [comment]
There is also an issue with the `preferences` schema.

**Comment by vince-fugnitto** [comment]
I attempted to verify when the schema was broken and used `theia-apps` to do so (since it is not constrained by a `yarn.lock`)

I observed that: 
- `theiaide/theia:0.10.0` (v0.10.0) worked correctly
- `theiaide/theia:0.11.0` (v0.11.0) had a regression

The major update as part of v0.11.0 looks to be the monaco update.
@akosyakov is there something we might have missed about the `yarn.lock` pinning that might explain why schema assist throughout the application might not work correctly after the monaco update?

**Comment by akosyakov** [comment]
@vince-fugnitto I don't know, maybe related to LSP integration of JSON service.

**Comment by vince-fugnitto** [comment]
It looks like the `JSON` language server has problems when starting:
(when opening the output view with the JSON channel)

```
[Error - 10:57:33] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'create' of undefined
[Error - 10:57:33] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'create' of undefined
[Error - 10:57:39] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'update' of undefined
[Error - 10:57:39] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'update' of undefined
[Error - 10:57:40] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'update' of undefined
[Error - 10:57:42] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'update' of undefined
[Error - 10:57:43] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'update' of undefined
```

**Comment by tolusha** [comment]
Updating to LS 1.2.2 doesn't help

**Comment by tolusha** [comment]
This is a configuration incompatibility between json-language-server (1) and vscode-languageserver (2)
(1) tries to create a TextDocuments service and does pass any parameters, but the latest version of (2) expect a configuration.

That's why we can see `Cannot read property 'create' of undefined` or `Cannot read property 'update' of undefined`

**Comment by akosyakov** [comment]
@tolusha So it is not something that we can fix in Theia, but need to upgrade vscode-languageserver? Can we do it only for `@theia/json` and if not can we pin to stable version of a language server?

**Comment by tolusha** [comment]
we need a new version of json-language-server, but it hasn't been released yet

**Comment by tolusha** [comment]
@benoitf Is there a way to set explicit version of a transitive dependency?

**Comment by akosyakov** [comment]
@tolusha you can set it with `yarn resolutions`, but all adopters will need to do the same for now too

**Comment by tolusha** [comment]
https://github.com/eclipse-theia/theia/pull/6607

**Comment by akosyakov** [comment]
Reopened since the original issue is not resolved.

**Comment by akosyakov** [comment]
We don't use `@theia/json` anymore.
