### ISSUE TITLE
DAP - Different behavior between VSC and Theia while updating a variable and its children-variables

### ISSUE THREAD

**Issue by ParOvBroadcom** [eclipse-theia/theia#6547]
### Description
After changing the value of a variable that affects also the value of a child-variable, the VSC DAP updates everything correctly, while Theia DAP updates only the changed variable (not the child variable). Is there a way to trigger the child-variable to update forcibly?

### Reproduction Steps
Using the setVariable method to update a variable is updating everything except the children-variable values in Theia. All the variables are updated correctly on the resume debugging, because the whole scope is re-fetched and refreshed.

**OS: Windows 10 and Theia version:0.11.0**

**Diagnostics:** 
No diagnostics

**Comment by vince-fugnitto** [comment]
For additional information, there is the thread from [spectrum](https://spectrum.chat/theia/dev/dap-different-behavior-between-vsc-and-theia~5e6f2f94-508c-4f82-8f6f-cb937e9424a5).

There is mention of a fix:
 https://github.com/eclipse-theia/theia/blob/8147d0676d325d68fc408a344d1da0e2460ae0b4/packages/debug/src/browser/console/debug-console-items.tsx#L193
Which states that `undefined` should be set so that it will be fetched on next rendering.

--- 
@ParOvBroadcom is it something you'd like to provide a PR for? :)

**Comment by tolusha** [comment]
Merged https://github.com/eclipse-theia/theia/pull/6555
