### ISSUE TITLE
Complete terminal(pseudoTerminal) api

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-theia/theia#6589]
### Description
VSCode has new pseudo-terminal api https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L7518 

We need implement it.

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
Are there known VS Code samples, extensions to test again?

**Comment by AndrienkoAleksandr** [comment]
> Are there known VS Code samples, extensions to test again?

I will take a look.

**Comment by PEZ** [comment]
I am about to switch to this for Calva (a Clojure extension for VS Code). Here's the PR: https://github.com/BetterThanTomorrow/calva/pull/654

It's a bit ironic, because the reason I started with it was to see if it would help Calva start working in Theia. Something that is partly do to Theia loosing track of the terminal used for hosting the orphaned Task I am currently using.

I elaborated some more on how I use the API here: https://community.theia-ide.org/t/can-i-use-vscode-extensionterminal-in-theia/24

Also throwing in some more of my struggles here: https://community.gitpod.io/t/is-there-an-easy-way-to-debug-a-vscode-extension-inside-gitpod/596/68?u=pez (I wanted to keep reporting in that thread, but am to new to the community to be allowed to 😄 ).

**Comment by akosyakov** [comment]
@PEZ I don't think anyone is looking into it, right now. PRs are welcomed.

**Comment by datou0412** [comment]
this sample can be used to test [extension-terminal-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/extension-terminal-sample)

**Comment by tsmaeder** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/12074
