### ISSUE TITLE
Implement SelectionRange and SelectionRangeProvider

### ISSUE THREAD

**Issue by tolusha** [eclipse-theia/theia#6623]
### Description
`css-language-features`, `html-language-features`, `json-language-features` builtin extensions failed due to unimplemented VS Code API.

https://github.com/Microsoft/vscode/blob/8795a9889db74563ddd43eb0a897a2384129a619/src/vs/vscode.d.ts#L3842
https://github.com/Microsoft/vscode/blob/8795a9889db74563ddd43eb0a897a2384129a619/src/vs/vscode.d.ts#L3863

**Comment by akosyakov** [comment]
Right now html and css coming from monaco. It's backed in the generator: https://github.com/eclipse-theia/theia/blob/b8c5e18530b93c5a8b7a1890b68f5bcc202e5817/dev-packages/application-manager/src/generator/webpack-generator.ts#L56-L57

We should make it optional somehow. Otherwise there would be duplicate proposals from monaco and vs code built-in extensions.

**Comment by vzhukovskii** [comment]
Implemented via https://github.com/eclipse-theia/theia/pull/7534
