### ISSUE TITLE
The 'see here for detailed documentation' is not leading to relevant docs

### ISSUE THREAD

**Issue by kdvolder** [eclipse-theia/theia#6638]
### Description

Most of the packages under the packages directory in this repo contain a very skeletal readme that shows a text "See here for a detailed documentation." with a link that leads to `https://theia-ide.org/docs/`. 

For example:

- https://github.com/eclipse-theia/theia/tree/master/packages/workspace

This link is not all that useful and just leads back to the a 'general' overview page rather than to a detailed documentation of the package in question.

### Reproduction Steps

- Go to https://github.com/eclipse-theia/theia/tree/master/packages/
- Select almost any of the package folder readme
- Follow the link to 'detailed' information
- Notice that it does not lead to detailed information of the package in question

**Comment by vince-fugnitto** [comment]
@kdvolder you are correct, the documentation for each extension is in fact lacking at the moment.
It is definitely one of the reasons I proposed the following: https://github.com/eclipse-theia/theia/issues/6518

I think we can greatly improve the `README` for each extension, and it will be useful since they are displayed by default when browsing through `npm`. Just look at the `@theia/cpp` extension which is a much better case: https://www.npmjs.com/package/@theia/cpp

**Comment by vince-fugnitto** [comment]
Closed by #7254
