### ISSUE TITLE
Indicate Symlinks in File Explorer

### ISSUE THREAD

**Issue by meysholdt** [eclipse-theia/theia#6660]
The File Explorer currently displays symlinks that point to files or folders just like regular files. This can be confusing, because as a user it becomes easy to overlook that two files or folders are physically the same and thus changes to one change both.

It would be nice if the File Explorer would indicate that a file or folder is a symlink, for example by giving it a special icon.

**Comment by akosyakov** [comment]
We actually have issues with symlinks: https://github.com/eclipse-theia/theia/issues/5968

@eclipse-theia/ecd-theia-committers What do you think about disallowing traversing symlinks, since experience is bad, show them differently, and provide a command to reveal in the real path? For directories, for files they still can be opened.

**Comment by vince-fugnitto** [comment]
The symlink decoration is supported by https://github.com/eclipse-theia/theia/pull/10439.
