### ISSUE TITLE
Is there a list of supported vscode plugins?

### ISSUE THREAD

**Issue by datou0412** [eclipse-theia/theia#6729]
### Description

Since not all vscode plugins are supported, is there a list of the supported ones?

**Comment by vince-fugnitto** [comment]
@datou0412 I don't believe there is curated list of supported plugins at the moment, since it will take significant effort to test and track all available VS Code extensions. Instead, testing is performed on plugins which are marked to replace internal extensions, and also popular extensions. The idea is to test these extensions and ensure that APIs are successfully implemented, and when a plugin is not working correctly, an issue is created which can later be fixed. As we support more missing APIs, other extensions (which use such APIs) will work correctly as well.

We have already tested a significant number of VS Code extensions and raised issues for them:
- [vscode labeled issues](https://github.com/eclipse-theia/theia/issues?q=is%3Aopen+is%3Aissue+label%3Avscode)

**Comment by datou0412** [comment]
Since you have already worked on it, cloud you from now on mark the extension which can pass your tests?

Just something like a todo list

- [x] vue
- [x] Python
- [ ] Material Theme

**Comment by akosyakov** [comment]
Using One Drak Pro to test https://github.com/eclipse-theia/theia/pull/6722 😉Hopefully we land it this week to include in next release.

**Comment by datou0412** [comment]
> Using One Drak Pro to test #6722 😉Hopefully we land it this week to include in next release.

Excellent job

**Comment by datou0412** [comment]
So, can anybody answer my question, can you make a list of currently supported vscode extensions?

**Comment by akosyakov** [comment]
@datou0412 we are targeting to support all of them. If some does not work file an issue and we will have a look. There could be intermediate issues if an extension is using some proposed experimental API, but they will be resolved over time.
