### ISSUE TITLE
[notification] I want the notification promise to resolve when it timeouts

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6731]
### Description
 
The notification closes,
 - when a `timeout` was specified and not actions were provided and the notification closes without user interaction, or
 - when actions were provided, and the user dismisses it or performs one of the actions.

The notification promise resolves only in the latter case, I want the promise to resolve when it timeouts without interactions.

So I can write something like
```ts
this.messageService.warn(`Reconnecting in ${x} seconds`, { timeout: x * 1000 }).then(()=> this.reconnect());
```

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by AlexTugarev** [comment]
`timeout` in message options was used to hide the message from the beginning. that could  break clients. 

in general, cancellable messages (like progress messages) would be a really nice idea, which was asked for already. cancellation after some timeout would do the trick. the only reason I didn't include that into the revision of the notification center was to not break API, because it required to change the type of the promise.

now, in examples like ☝️, actually, I suggest to use progress messages like so:

```ts
const progress = await this.messageService.showProgress({ text: `Reconnecting in ${x} seconds`,  });
timeoutAfter(4).then(() => progress.cancel);
progress.result.then(() => this.reconnect());
```

**Comment by kittaakos** [comment]
> I suggest to use progress messages like

Nice! Thank you!

> cancellable messages (like progress messages) would be a really nice idea

I agree.

> which was asked for already

Assuming it someone has already requested it in another issue, and you gave me a working solution, there's not much to do here. I am closing it.
