### ISSUE TITLE
[navigator] race condition between click and dblClick handlers 

### ISSUE THREAD

**Issue by shahar-h** [eclipse-theia/theia#6784]
### Description
When opening a file with a double click, both [handleClickEvent](https://github.com/eclipse-theia/theia/blob/25d0e2b3d38bb80e875cda93974ba6a2a7b9015d/packages/navigator/src/browser/navigator-widget.tsx#L233). and [handleDblClickEvent](https://github.com/eclipse-theia/theia/blob/25d0e2b3d38bb80e875cda93974ba6a2a7b9015d/packages/core/src/browser/tree/tree-widget.tsx#L1063) on navigator-widget.tsx are called.
The result is [open](https://github.com/eclipse-theia/theia/blob/25d0e2b3d38bb80e875cda93974ba6a2a7b9015d/packages/core/src/browser/opener-service.ts#L80) method inside opener service is called twice.

When working with editor-preview extension and `Editor.enablePreview` is true The following issues occur:
- Open any file with double click results in flickering behavior.
- Open a file with a single click, then open a second file with double click: in some environments the new file content is not rendered:
![image](https://user-images.githubusercontent.com/16555289/71358025-30a72480-2590-11ea-875f-e04dcd1233d9.png)

This issue happens because of a race condition in [open method of editor-preview-manager](https://github.com/eclipse-theia/theia/blob/25d0e2b3d38bb80e875cda93974ba6a2a7b9015d/packages/editor-preview/src/browser/editor-preview-manager.ts#L111) which is triggered twice, both from click handler and doubleClick handler.

**Comment by colin-grant-work** [comment]
This is similar to #8511

**Comment by vince-fugnitto** [comment]
> This is similar to #8511

I believe the main issue is the following: https://github.com/eclipse-theia/theia/issues/8168.

**Comment by colin-grant-work** [comment]
> > This is similar to #8511
> 
> I believe the main issue is the following: #8168.

I don't think that's quite right, because it can occur outside of editor contexts, as reported in #9485, so the click-double-click problem is a special case. I think the approach adopted here is reasonable - creation and attachment are separate events - but I think another part of the solution is to fix some bad architecture in the `editor-preview` package. I've had success with an approach that has the `EditorPreviewManager` extending and replacing the `EditorManager`, rather than competing with it as a completely separate `OpenHandler`. PR pending :-)
