### ISSUE TITLE
Opening the Plugins view using the key bindings does not work initially

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#6935]
### Description
Using keybindings to open the plugins view does not work initially
Note: Only use the keybindings, **not** the view context menu

### Reproduction Steps

- Start Theia,  open a Java project + a java file
DO NOT USE ANY OTHER KEYBINDINGS before using "CTRL + SHIFT + L"
- "CTRL + SHIFT + L" --> should open the Plugins view, **but is NOT opening**
- Use "CTRL + SHIFT + M" to open the Problems view OR the context menu to open the Plugins view
- Try again to open the Plugins view with the key bindings --> works now

**OS and Theia version:**
Ubuntu 16.04
Web: Firefox and Chrome
Theia: latest  commit 7097574ea2f3d7a7692144a07fa567212cc090d6

**Diagnostics:** 

![PluginKeyBindings](https://user-images.githubusercontent.com/419051/72805334-9d115400-3c20-11ea-8279-86915d11614f.gif)

**Comment by vince-fugnitto** [comment]
@lmcbout 

I would not place this issue as a must fix since the `plugins-view` as we know it is soon to be deprecated by the `registry-view` (#6655)

Also, I do not think it is a bug since, there are two keybindings which use 
<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>l</kbd> (in the first case the view was not opened since the editor had focus):

![image](https://user-images.githubusercontent.com/40359487/72806597-7f91b980-3c23-11ea-87cc-dc574453e6f0.png)

**Comment by vince-fugnitto** [comment]
I tested and the keybinding to toggle the `plugins-view` is triggered whenever an editor **does not have focus** as described in it's `context/when`. 

Closing the issue as there is nothing to do.
