### ISSUE TITLE
Scrolling in Editor is Slow in Firefox

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#7039]
When I scroll with the mouse wheel in the editor in Firefox, the scroll rate (the amount the editor content moves) is much lower in Firefox than in Chromium. The renders scrolling with the mouse-wheel useless.

### Reproduction Steps
1. Run the browser example
2. Open any large file
3. Use the mouse scroll wheel to scroll
4. Observe: the content moves only a tiny amount, even when frantically scrolling.

**OS and Theia version:**
Windows 10, FF 72.0.2, master

This scrolling works fine in Electron and Chromium

**Comment by tsmaeder** [comment]
https://youtu.be/DKJ8fUkslhM

**Comment by vince-fugnitto** [comment]
Depends on https://github.com/eclipse-theia/theia/issues/6223

It has been previously mentioned and it looks to be fixed in the newest monaco update.
Some additional information:
- https://github.com/eclipse-theia/theia/issues/6223#issue-496100290
- https://github.com/eclipse-theia/theia/pull/5901#issuecomment-533146298
- https://github.com/eclipse-theia/theia/pull/5901#issuecomment-528397513

**Comment by tsmaeder** [comment]
Thanks, @vince-fugnitto I didn't find that searching for existing issues.

**Comment by vince-fugnitto** [comment]
Fixed thanks to https://github.com/eclipse-theia/theia/pull/7149
