### ISSUE TITLE
[electron] Electron not showing the active editor in the window title as in VScode

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7076]
### Description
 
Theia electron version does not show the active editor in the window title as in VSCode

### Reproduction Steps

Open a file in Theia 
--> observe the window title, it does not show the active file editor
Open the same workspace with VSCode
--> Observe, the window title is upsdated including the active file editor 

**OS and Theia version:**
OS: Ubuntu 18.04
Theia : latest commit cc0da4e69f8141122496c119bb72f4df46584e76

**Diagnostics:** 
Theia electron:
![ElectronTitleNotshowingActiveeditor](https://user-images.githubusercontent.com/419051/73766818-94eb0580-4744-11ea-8b54-303fce2d8d2d.gif)

VSCode electron:
![VSCodeShowPreview](https://user-images.githubusercontent.com/419051/73766853-a2a08b00-4744-11ea-8848-3cb7e91e1498.gif)

**Comment by vince-fugnitto** [comment]
I don't believe it is possible at the moment, but perhaps after #4869 (at least for electron)
I believe it is also a small enhancement, for instance the `browser` target also does not update based on the active file.

**Comment by akosyakov** [comment]
It is not fix, we have quite different concept of what is active compare to VS Code.

**Comment by vince-fugnitto** [comment]
@lmcbout I've removed the `electron` label since the enhancement is not specific to electron (the browser target also does not display the active editor). As Anton mentioned, our concept of **active** is quite different and due to limitations it might not be easy to update the title.

I see the enhancement as a low-priority if we ever do decide to work on it.

**Comment by lmcbout** [comment]
Low enhancement priority is fine with me
Thanks
