### ISSUE TITLE
plugins: add flag to 'download:plugins' script

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7122]
**Description**

The main idea is to be able to call the `download:plugins` script with the ability to specify if the `.vsix` should be preserved or unpacked. 

The flag `preserveVsix` will:
- unpack the `.vsix` if `preserveVsix` is set to **false** (**default**)
- preserve plugins as `.vsix` if `preserveVsix` is set to **true**

**Comment by amiramw** [comment]
Why are both options required? What are the tradeoffs between them?

**Comment by akosyakov** [comment]
If you unpack during the build time, startup time will be around 10x faster. But it is not possible currently for Electron, since one cannot write inside asar archives, so there unpacking happens at runtime. Eventually we will move away from it, see discussions here: https://github.com/eclipse-theia/theia/pull/7093#issuecomment-583820160

**Comment by kittaakos** [comment]
> since one cannot write inside asar archives

FYI: We do not support asar.
