### ISSUE TITLE
History Service

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#73]
We should provide commands to go back and forward in the "editor selection history".
I think we could just listen on selection events and store the information, then on back we reveal the previous selection, vice versa for forward.

**Comment by MarkZ3** [comment]
Is it something planned for this year (Theia 1.0 BETA)?

**Comment by svenefftinge** [comment]
I do think it is very important, but there are no commitments so far.

**Comment by hexa00** [comment]
@MarkZ3
btw I would like it if we could have something that's distinct from the selection history when we do go to definition etc...

I have that at the moment in emacs, when I go to def repeatedly I have a history just for that and I can push/pop it.. 

It's nice that's it's different from the selection history since usually I would go to def.. and then explore the code a bit around... and then when I want to go back from that go to def.. it's easy rather than pressing back on all my 'exploring'

I don't think it should be in the lsp directly but something to consider in Theia...

**Comment by epatpol** [comment]
> Thinking about it, we should have an explicit history service, where clients actively register something that can be used to reveal a certain selection (URI). This way different widgets can decide whether they want to participate and when.

Would clients have to contribute a sort of unique "callback"? I don't see the history service being aware of how to open these particular selections in this case. Maybe a use case would help?

If possible I'd like a basic implementation of back/forward across text editor selections, maybe selection-history "providers" could be another iteration?

**Comment by svenefftinge** [comment]
Yes, I agree with both comments. It should not be as fine-grained as tracking all selection events and also it would mainly be important to have it for text editors. Also, we need it shortly.

**Comment by epatpol** [comment]
@hexa00 I like the idea of a different history for that, maybe it could be implemented in another iteration?

I'm trying to see how we could have a basic implementation for at least selection history, without making it too specific (so that we can expand on the idea of @svenefftinge to have clients contribute their selection history handling).

**Comment by svenefftinge** [comment]
What is the selection history anyways? I think we are all talking about the same 'navigation history' that should not keep every selection change but rather the important ones.

Here is the logic they use in vscode : https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L59

**Comment by hexa00** [comment]
Just to clarify for me the history is being able to go back and forth based on a navigation action.

So if you move your cursor you have:  back/forth selection history.
If you do Go to definition you have: Go to definition/ Come back from definition

So I think we should implement the selection history first but think about it being general enough to accommodate thins like Go/Come back definition.

**Comment by hexa00** [comment]
Maybe we should have a a generic navigation history component that anyone can use and that would just record the location markers and provide push/pop access to them ?

**Comment by svenefftinge** [comment]
Going back and forth should be commands with keybindings, of course.

**Comment by kittaakos** [comment]
Could we generalize this functionality, so that some parts of the API and the implementation could be merged with `Navigatable`? I do not yet have a good idea how, but it seems to be very similar?
 - In the context of this task, we have to reveal editors as opposed to revealing something ( tree node in the navigator) from an editor.
 - Additionally, we have to select a (partial) range. (Which is done by the `OpenerOptions`, so it is [already](https://github.com/theia-ide/theia/compare/GH-73) generic.)

I thought it might worth a show discussion.

CC: @akosyakov, @svenefftinge
