### ISSUE TITLE
json format need use @theia/json or @theia/vscode-builtin-json-language-feature?

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#7341]
### Description

json format need use @theia/json or @theia/vscode-builtin-json-language-feature?
I can't format json file use @theia/json

### Reproduction Steps

```
    "dependencies": {
        "keytar": "latest",
        "@theia/getting-started": "next",
        "@theia/preview": "next",
        "@theia/editor-preview": "next",
        "@theia/plugin-dev": "next",
        "@theia/plugin-ext-vscode": "next",
        "@theia/json": "next",
        "@theia/git": "next"
    },
```

**OS and Theia version:**
Microsoft Edge Dev 82.0.446.0
Theia 0.17.0-next.9457f808
Windows 10

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@502647092 I believe you’ve already opened a similar issue https://github.com/eclipse-theia/theia/issues/6758. I think it’d be better to continue the discussion on the past issue.

**Comment by vince-fugnitto** [comment]
@502647092 

To answer your question:
1. Formatting is supported by the `@theia/json` extension, and it works correctly from sources.
If it does not work, it is likely fixed with resolutions as you mentioned https://github.com/eclipse-theia/theia/issues/6758#issuecomment-568673007.
2. Formatting from the `vscode-builtin-json-language-features` builtin is not yet supported (there is compatibility still missing from the framework). Moreover, there are other compatibility issues with the extension, for example https://github.com/eclipse-theia/theia/issues/6623, which is part of the reason why it has yet to be used in this repo to replace `@theia/json`.

**Comment by akosyakov** [comment]
But we should start working on deprecating @theia/json and switching to VS Code counterpart.

**Comment by 502647092** [comment]
`vscode-json-languageserver` is update
`@theia/json` work after I remove the following parameters
```
    "resolutions": {
        "vscode-languageserver-protocol": "3.15.0-next.9",
        "vscode-languageserver-types": "3.15.0-next.5",
        "**/vscode-json-languageserver/**/vscode-languageserver": "6.0.0-next.1"
    },
```

**Comment by 502647092** [comment]
`@theia/json` now can work don't have resolutions
