### ISSUE TITLE
Theia Extension Cannot apply @injectable decorator multiple times.

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#7390]
### Description
I cannot create a new theia extension since today.
When I create a new helloworld extension by typing 'yo theia-extension xxxx'
it compiles but when I start the theia app and see the browser then the console shows following error
```
index.js:61 Failed to start the frontend application.
(anonymous) @ index.js:61
Promise.catch (async)
./src-gen/frontend/index.js @ index.js:60
__webpack_require__ @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ bootstrap:198

index.js:63 Error: Cannot apply @injectable decorator multiple times.
    at injectable.js:8
    at DecorateConstructor (Reflect.js:541)
    at Object.decorate (Reflect.js:130)
    at _decorate (decorator_utils.js:42)
    at Object.decorate (decorator_utils.js:55)
    at Object.../node_modules/@theia/variable-resolver/node_modules/@theia/core/lib/browser/widgets/widget.js (widget.ts:27)
    at __webpack_require__ (bootstrap:63)
    at Object.../node_modules/@theia/variable-resolver/node_modules/@theia/core/lib/browser/widgets/index.js (index.ts:17)
    at __webpack_require__ (bootstrap:63)
    at Object.../node_modules/@theia/variable-resolver/node_modules/@theia/core/lib/browser/dialogs.js (dialogs.ts:20)
```

Here is the package.json in by browser-app

```json
{
  "private": true,
  "name": "browser-app",
  "version": "0.0.0",
  "dependencies": {
    "@theia/core": "latest",
    "@theia/filesystem": "latest",
    "@theia/workspace": "latest",
    "@theia/preferences": "latest",
    "@theia/navigator": "latest",
    "@theia/process": "latest",
    "@theia/terminal": "latest",
    "@theia/editor": "latest",
    "@theia/languages": "latest",
    "@theia/markers": "latest",
    "@theia/monaco": "latest",
    "@theia/typescript": "latest",
    "@theia/messages": "latest",
    "programmr_php7": "0.0.0"
  },
  "devDependencies": {
    "@theia/cli": "latest"
  },
  "scripts": {
    "prepare": "theia build --mode development",    
    "start": "theia start",
    "watch": "theia build --watch --mode development"
  },
  "theia": {
    "target": "browser"
  }
}
```

### Reproduction Steps

**OS and Theia version:**
Yarn version: 1.15.2
yo version: 2.0.6
Node version:10.15.3

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@dhananjayharel the error occurs since `@theia/typescript` has been deprecated and it's `latest` version is thus behind all other extensions.

It is generally not possible to mix-match versions of theia extensions as they will each pull different versions of `@theia/core` for instance which cannot be resolved, causing the multi-injector issue.

Checking `npm` you can see that `@theia/typescript` latest points to 0.15.0, while another extension like `@theia/getting-started` is at 0.16.1.

<img width="369" alt="Screen Shot 2020-03-21 at 10 07 14 PM" src="https://user-images.githubusercontent.com/40359487/77240790-793aa200-6bc0-11ea-810d-5960e4f45577.png">
<img width="377" alt="Screen Shot 2020-03-21 at 10 07 30 PM" src="https://user-images.githubusercontent.com/40359487/77240791-79d33880-6bc0-11ea-9c49-8dc6c9e018ae.png">


The fix has been made on the generator already in the most up-to-date version: https://github.com/theia-ide/generator-theia-extension/pull/53

Additional Info:
- you can see the following pull-request for the list of deprecated extensions: #6933

**Comment by dhananjayharel** [comment]
Thanks.
I can compile the plugin after updating the [plugin generator](https://github.com/theia-ide/generator-theia-extension/pull/53)
