### ISSUE TITLE
YAML Hover Bug

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse-theia/theia#7537]
### Description

![image](https://user-images.githubusercontent.com/50386709/78849964-8f779900-79db-11ea-8c0e-e15e1245f816.png)

YAML hovers provide incorrect description

### Reproduction Steps

Unkown

**Diagnostics:** 

Chrome Console:

![image](https://user-images.githubusercontent.com/50386709/78850194-31978100-79dc-11ea-97f0-cf928c73845f.png)
![image](https://user-images.githubusercontent.com/50386709/78850228-470cab00-79dc-11ea-9be0-8ca84d4b0c67.png)
![image](https://user-images.githubusercontent.com/50386709/78850266-61df1f80-79dc-11ea-9da1-b49d901aab68.png)

**Comment by akosyakov** [comment]
We need reproducible tests for the vanilla Theia to work on it.

**Comment by JPinkney** [comment]
Is this an issue with the schema for gitpod? Or an issue with the yaml language server? If it's an issue with the language server I can take a look if you have the schema available

**Comment by JesterOrNot** [comment]
@JPinkney [here](https://github.com/gitpod-io/gitpod-yml-schema/blob/master/gitpod-yml.schema.json) is the schema, I don't think thats the issue though, but feel free to take a look

**Comment by JPinkney** [comment]
I'm assuming you want the hover description to say `"Docker image to use for workspaces. Default is 'gitpod/workspace-full'"?`

If so it looks like the issue is that the schema from the schema store points to a schema that is incorrect: https://github.com/SchemaStore/schemastore/blob/003226ee24535dec1fde6ef00d5d76ea4651d202/src/api/json/catalog.json#L703.

I think the schema on the schema store should either point to `https://raw.githubusercontent.com/gitpod-io/gitpod-yml-schema/master/gitpod-yml.schema.json` or the schema should be updated on the gitpod.io website and then the hover should be correct

**Comment by akosyakov** [comment]
@JesterOrNot Could you transfer this issue to Gitpod please?

**Comment by JesterOrNot** [comment]
Done!
