### ISSUE TITLE
editor.maxTokenizationLineLength is not used leading to bogus coloring

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7617]
Reproducible with https://github.com/opencaesar/vocabularies/blob/9b8c1ff9d07803420cebe03f44687a4da253373b/src/imce.jpl.nasa.gov/foundation/base.oml and https://github.com/opencaesar/oml-vscode

**Comment by melaasar** [comment]
What do I need to do to get this fix? Do I need to rebuild the oml-vscode extension?

**Comment by akosyakov** [comment]
@melaasar Hi 👋 We limit tokenisation to max 400 characters by default since it can hang the browser for big files. But a user can change this default with `editor.maxTokenizationLineLength` preference. VS Code is using 20000 characters but they are running natively on desktop, so performance it is better.

**Comment by melaasar** [comment]
Thanks.  I  went ahead and added a workspace setting file where I added a value of 800 to editor.maxTokenizationLineLength:
https://github.com/opencaesar/vocabularies/blob/master/.theia/settings.json

However, when I start a new workspace, and browse to https://github.com/opencaesar/vocabularies/blob/master/src/imce.jpl.nasa.gov/foundation/base.oml
I still see the issue at line 5 (not  colored properly) because the token at line 4 is long despite it now being shorter than 800 limit. If I try to split the "..." token on line 4 across 2 lines, even by just putting the ending " on the next line, then the color problem goes away.

**Comment by akosyakov** [comment]
@melaasar It was not deployed to Gitpod yet. It was only merged for Theia. Check out it tomorrow or on Friday maybe it will be there.
