### ISSUE TITLE
npm scripts tree is empty when activated while explorer view is not visible

### ISSUE THREAD

**Issue by shahar-h** [eclipse-theia/theia#7738]
### Bug Description:
When npm builtin extension is activated while explorer view is not visible , npm scripts tree stays empty.

### Steps to Reproduce:

1. Run theia and open the browser with some node project as workspace root - it should contain at least one script. npm scripts tree should appear with content.
2. Refresh browser and immediately open some other view (i.e. search view) before npm extension is activated.
3. Wait for activation  of npm extension to finish.
4. Switch back to explorer view - npm scripts tree is empty. refresh / collapse & expand doesn't help.
Only browser refresh resolves this.

Note: This issue also happen with other trees, npm is just a convenient example.

I tried to debug the browser code and found that `onDidChangeVisibility` is not fired in this case:
https://github.com/eclipse-theia/theia/blob/0a691e224cec050a7f51f99d12924ebf478fc4c7/packages/core/src/browser/widgets/widget.ts#L163

### Additional Information

- Operating System: Windows 10, Debian 10
- Theia Version: build from master branch

**Comment by amiramw** [comment]
After investigation I have some more infromation and question. 

It seems that there is a race condition regarding the visibility of view container part. 
https://github.com/eclipse-theia/theia/blob/fd9d8ec04d07d259e94cf81a088db1ee500b22e1/packages/plugin-ext/src/main/browser/view/plugin-view-registry.ts#L391-L400

Due to the use of `toFire.dispose()` there is only one chance to fire the `onDidExpandView` event which triggers the preparation of the view. This firing can happen if the part is visible for a short time (due to the if above).
However `registerViewDataProvider` can be called after that single event was fired and then nothing is displayed.

@akosyakov maybe the event should be fired every time the visibility is changed and not only once?
