### ISSUE TITLE
preferences: render 'markdownDescription' as markdown

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7742]
#### Prerequisite:

Following #7105

#### Feature Description:

It is possible to define a `markdownDescription` property for preferences in the schema, which is ultimately used as a description of the preference including the tooltip (when editing JSON), and in the user-interface. In the user-interface, the `markdownDescription` should be properly rendered as markdown similarly to VS Code:

_Theia_:

<img width="631" alt="Screen Shot 2020-05-05 at 9 17 33 AM" src="https://user-images.githubusercontent.com/40359487/81070940-f93b7380-8eb1-11ea-90a9-c639b82c5e13.png">

_VS Code_:

<img width="637" alt="Screen Shot 2020-05-05 at 9 23 04 AM" src="https://user-images.githubusercontent.com/40359487/81070991-0d7f7080-8eb2-11ea-9fca-f0de189f8aca.png">

**Comment by jwebstar** [comment]
I started on this while looking at the new preferences UI and have made some progress:

Before:
![PrefBefore](https://user-images.githubusercontent.com/73082075/123251531-382bee80-d4e3-11eb-8687-a1bf2ba816eb.png)

After:
![PrefAfter](https://user-images.githubusercontent.com/73082075/123251550-3cf0a280-d4e3-11eb-8351-35b0acba7f36.png)

But I haven't got the internal settings links working yet. Rather than scrolling to that preference, clicking a link currently appends the id to the url instead. Before resuming with it I wanted to check:
1) If anyone has any guidance on how this should be done?
2) That nobody was already working on this?

**Comment by vince-fugnitto** [comment]
@jwebstar sorry for getting back so late, it already looks like some great progress! 👍 

> 1. If anyone has any guidance on how this should be done?

I haven't looked at it closely yet as what we could do but we can probably use the same idea we had in https://github.com/eclipse-theia/theia/pull/9318 to give the links the role of buttons and attempt to scroll-to the proper preference. Still, please feel free to open a draft pull-request with the changes so far and perhaps others can help.

> 2. That nobody was already working on this?

Not that I know of :)
