### ISSUE TITLE
scm input is not styled properly

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7794]
It is a recent regression. See for details: https://github.com/eclipse-theia/theia/pull/7769#issuecomment-627176542

**Comment by westbury** [comment]
This issue can be seen only when switching to another workspace that has not been previously opened.  Create a new folder and copy a project into it.  Then open the workspace to see the issue.  The problem does not occur if you open a workspace that has been opened before.

The problem is very transient.  If you type in the commit box, or open dev tools or do just about anything then the problem goes away.

The problem appears to be caused because the height is not set.

![Screenshot from 2020-05-12 13-29-19](https://user-images.githubusercontent.com/87310/81691512-d8949000-9454-11ea-8d5c-b4eafda0b8c5.png)

whereas when the problem does not show we see a height of 32px set in the style:

![Screenshot from 2020-05-12 12-09-04](https://user-images.githubusercontent.com/87310/81691619-05e13e00-9455-11ea-83aa-b728ba897b66.png)

The above screenshot was taken with v1.1.0 (prior to the conversion of Source Control view to use TreeWidget).  However the height property of 32px appears on current master too whenever the commit area is the correct size.

**Comment by akosyakov** [comment]
@westbury are you going to look into the fix or would it be fine if somebody else?

**Comment by westbury** [comment]
@akosyakov sorry, I'm a bit busy at this moment.  I was hoping someone would immediately know what was going on.  I don't know where those style properties are coming from, nor who or what is making the height usually be there but occasionally not be there.  If someone else has time to look that would be great.

**Comment by westbury** [comment]
I had another quick look.  The height is being set in autosize package which is a dependency of react-autosize-textarea.  I found that adding a couple of lines to ensure an update does fix the problem.  See https://github.com/eclipse-theia/theia/tree/fix-commit-height .  However I do not understand why the update should be necessary.  Hopefully someone else will understand all this better.

**Comment by akosyakov** [comment]
@westbury I will have a look at it.

**Comment by akosyakov** [comment]
Also SCM input is not preserved between reloads.
