### ISSUE TITLE
preference UI is very slow

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7875]
### Steps to Reproduce:

1. start like in https://github.com/eclipse-theia/theia/issues/7874#issuecomment-633536413
2. try to use search
3. UI takes very long time to react

**Comment by balajiv113** [comment]
Hi, Am looking into fixing this issue. 
As far as i have analysed, In preference UI, we are directly using ul & li tags to render. Due to this when the preference data get too large the UI rendering is slowed due to complete render of all preferences.
 
To provide fix, i was thinking about using TreeWidget.View (It uses react-virtualized underneath). This way even during large data we will render only the visual part and not all preference.
Is this approach looks good ? If there are any other pointer or suggestions do let me know.

**Comment by vince-fugnitto** [comment]
Closing thanks to the refactoring of https://github.com/eclipse-theia/theia/pull/9439 which improved the overall performance. If there are specific cases where the performance is slow or sluggish we can open concrete issues to address them.
