### ISSUE TITLE
Add new menu item in the output view context menu

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7912]
#### Feature Description:

Following issue #7570 , I think it would be nice  to have in the context menu an entry: "Copy all" to copy all the data from that output channel or "Select all"

**Comment by kittaakos** [comment]
> "Copy all" to copy all the data from that output channel or "Select all"

Probably we do not need both. You can select all with <kbd>Ctrl/⌘</kbd>+<kbd>A</kbd>, and copy with <kbd>Ctrl/⌘</kbd>+<kbd>C</kbd>. I do not see a reason having "Select All" as a menu item. Once you have triggered select all, you will copy, it's read-only. Let's not pollute the context menu just because we can add one more command. "Copy All" could be useful though.

**Comment by lmcbout** [comment]
I don't think we  need both, only one of them is enough

**Comment by salkin-naj** [comment]
I am interested in working on this issue. Did I read your conversation correctly, you want a 'Copy All' option, but no 'Select All'?

**Comment by kittaakos** [comment]
> I am interested in working on this issue.

Sounds great, go ahead!

> Did I read your conversation correctly, you want a 'Copy All' option, but no 'Select All'?

Correct 👍
