### ISSUE TITLE
[keybinding] As an extension developer I want to unregister keybindings by the command

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8209]
Currently, one can unregister a keybinding with a keybindings object or a keybinding string:

https://github.com/eclipse-theia/theia/blob/4c63f08a6283f19f6f28727727378f7c1e38e316/packages/core/src/browser/keybinding.ts#L197-L198

The current approach is inconvenient:
 - as the keybindings strings are case sensitive and the order of the keys do matter (#8170), and
 - a command can have multiple keybindings (#8202).

A `unregisterKeybinding(command: Command): void;` API would be neat, and the deletion should be based on `command` instead of `keybinding`.

**Comment by kittaakos** [comment]
I leave a possible solution here if someone wants to contribute.
```ts
unregisterKeybinding(key: string): void;
unregisterKeybinding(keybinding: Keybinding): void;
unregisterKeybinding(command: Command): void;
unregisterKeybinding(arg: string | Keybinding | Command): void {
    const keymap = this.keymaps[KeybindingScope.DEFAULT];
    const filter = Command.is(arg)
        ? ({ command }: Keybinding) => command === arg.id
        : ({ keybinding }: Keybinding) => Keybinding.is(arg)
            ? keybinding === arg.keybinding
            : keybinding === arg;
    for (const binding of keymap.filter(filter)) {
        const idx = keymap.indexOf(binding);
        if (idx !== -1) {
            keymap.splice(idx, 1);
        }
    }
}
```

**Comment by minyoungyang** [comment]
@kittaakos I learned a lot through your code. Thank you for your code.

**Comment by JonasHelming** [comment]
This is based on the comment: https://github.com/eclipse-theia/theia/issues/8209#issuecomment-661686777

**Comment by JonasHelming** [comment]
What I wonder is whether the current behavior of unregisterKeybinding(Keybinding) is actually matching expectations.
I would expect that this removes a "Keybinding" rather than all keybindings which have a matching key.
I would actually propose to change that so that unregisterKeybinding(Keybinding) removes keybindings from the registry, which are equal or even the same object rather then all keybindings for the key. Whether the condition is "equal" or "the same" also depends on https://github.com/eclipse-theia/theia/issues/8270
If you agree to this, I am happy to open another issue and provide a fix.
