### ISSUE TITLE
node debug exception breakpoint stripe issues

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8225]
### Bug Description:

When stopping with node debugger over an exception breakpoint there is a strip with exception stack trace that cover the program code behind.
I would expect the code to move down (like in vs code) or to make this stripe closable by end user.

Theia:
![image](https://user-images.githubusercontent.com/9420921/88237404-de45f780-cc87-11ea-92bd-e5e4a4d2d802.png)

Vscode:
![image](https://user-images.githubusercontent.com/9420921/88237556-26fdb080-cc88-11ea-979c-52010cb7033d.png)

See how line 4 and 5 are before and after the stripe so nothing gets lost.

Another issue with the stripe is that it stays even when openning another code editor tabs on the same line...

### Steps to Reproduce:

Create a.js script:

```javascript
var a = 5;
console.log(a);
if (a>2) {
    throw new Error("Error");
}
console.log("End");
```

Create node launcher:
```json
{
"type": "node",
"request": "launch",
"name": "Launch Program",
"program": "${workspaceFolder}/a.js",
"runtimeExecutable": "node"
}
```

- From debug pane set "Uncought Exceptions" breakpoint.
- Launch "Launch Program"

Now progran stops on exception breakpoint with:
- Stripe covering the code. 
- When moving to another opened tab the stripe stays.

### Additional Information

- Operating System: Windows, debian
- Theia Version: master

**Comment by DoroNahari** [comment]
@akosyakov @vince-fugnitto 
I looked into this issue and i saw that the reason the overlay is covering the editor is because the `heightInLines` prop is always set to `0`. 
https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/editor/debug-exception-widget.tsx#L62
https://github.com/eclipse-theia/theia/blob/master/packages/monaco/src/browser/monaco-editor-zone-widget.ts#L101

I was thinking about calculating the height of the overlay and  in accordance calculating the needed `heightInLines` but the height is available only from `componentDidMount` React component lifecycle method. 

How do you suggest to proceed?

**Comment by akosyakov** [comment]
> I looked into this issue and i saw that the reason the overlay is covering the editor is because the heightInLines prop is always set to 0.

Could you elaborate please why is it an issue?
