### ISSUE TITLE
HTTP error on load dc.services.visualstudio.com:443

### ISSUE THREAD

**Issue by mikael-desharnais** [eclipse-theia/theia#8277]
### Bug Description:
With the latest version, when I cannot to the backend using any browser, I get the following error : 
```
root ERROR [hosted-plugin: 10916] ApplicationInsights:CorrelationIdManager [ { Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com',
    host: 'dc.services.visualstudio.com',
    port: 443 } ]

```
I'm behind a corporate proxy.
I found that it is related to some vscode plugins that seem to use the ApplicationInsight package but I could not find the source code that causes the error.

### Additional Information

- Operating System: Windows 10
- Theia Version: Latest

**Comment by vince-fugnitto** [comment]
@mikael-desharnais do you have any additional information, for example which plugins you currently have installed?
It is a bit difficult to identify the issue without this information.

**Comment by marcdumais-work** [comment]
@mikael-desharnais I think you are correct about the source of these requests (ApplicationInsight AKA visualstudio telemetry). 

It would help if you could confirm if you were using this repo's example application or another Theia-based application? Also I understand that some Microsoft extensions may have their own telemetry, so can you confirm that you can reproduce the issue without any extra VS Code extensions installed by default (basically the VS Code built ins)? 

`node-debug2`, that we include by default with the example application, might be a [suspect](https://github.com/eclipse-theia/theia/issues/8062#issuecomment-647244758). Some VS Code built-in extensions that we also include in the example app, pull [vscode-extension-telemetry](https://www.npmjs.com/package/vscode-extension-telemetry) as a dependency. From its README:

"The module respects the user's decision about whether or not to send telemetry data."

Since we do not have a an equivalent to the vscode telemetry service nor the preference to disable telemetry, it could be that some extensions will conclude that they should send telemetry at will. There is also the fact that apparently the way this works is that when one opts-out, a telemetry is still sent to tell them that you've opted-out. Not sure if this is one per session or what. 

> With the latest version

I just remembered that we recently updated the `vscode.htnl-language-features` extension we use, after we fixed a bug by now bundling the typescript language server with it. Both of these look to be full of telemetry code, so maybe new attempted telemetry-related connections came from that.

**Comment by MikaelDesharnais-ST** [comment]
I use a clean clone of the theia repo and I start the examples/browser backend.
according to my researches, the plugins that can potentially call this url are : 
- vscode-builtin-html-language-features
- vscode-builtin-json-language-features
- vscode-builtin-markdown-language-features
- vscode-builtin-typescript-language-features
The error is thrown from within a child process and as it is I was unable to find its origin.

**Comment by mikael-desharnais** [comment]
By eliminating the other plugins, I found that the error is caused by : vscode-builtin-json-language-features

**Comment by mikael-desharnais** [comment]
Ok, I've found the problem.

On load, the vscode-builtin-json-language-features calls the following URL : 'https://dc.services.visualstudio.com/api/profiles/AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217/appId'

For the proxy configuration, it uses the HTTP_PROXY & HTTPS_PROXY environment variable. These variables were not defined globally in the system in my case so it was not working.

**Comment by marcdumais-work** [comment]
@mikael-desharnais Thanks for narrowing-down and reporting back.

**Comment by danarad05** [comment]
> I use a clean clone of the theia repo and I start the examples/browser backend.

Hi @mikael-desharnais 
I'm working on this issue and trying to reproduce issue - trying to find requests to dc.services.visualstudio.com when debugging - till now unsuccessfully - can't find any request to that url.

Could you elaborate exactly what steps you are taking in reproducing issue? any screen caps, network log, anything that would help me reproduce issue.

Thanks

**Comment by marcdumais-work** [comment]
Hi @danarad05 

>  seem to use the ApplicationInsight package

> trying to find requests to dc.services.visualstudio.com

Grepping into the vscode extensions folder (where our `vscode-builtins` come-from), I find that the few extensions that contribute advanced features use the `ApplicationInsight` package, and so might be the source of the failed connections:

markdown-language-features, json-language-features, image-preview, html-language-features,  git, typescript-language-features. There might be a few standalone extensions by Microsoft that might do the same (cpp, python,...)

> trying to find requests to dc.services.visualstudio.com when debugging

IIRC there's a list of such servers rather than this one being hard-coded, and one gets picked at runtime - it will not necessarily be the same one each time.

**Comment by danarad05** [comment]
@marcdumais-work 
Thanks for your comment. 
I saw that `applicationInsight` package is used in the Theia's vscode-builtin extensions and I used Fiddler and Wireshark to try and locate requests to microsoft or visualstudio or anything different. I personally couldn't find any - which means probably that I'm missing a step or requisite for reproducing this issue. One difference is obviously I'm not currently using a corp proxy - wanted to first locate requests and then try using proxy to reproduce errors.

I also think that adding the "telemetry.enableTelemetry" preference might work in disabling telemetry but I need to reproduce requests first which I'm unable to do currently.

@mikael-desharnais  - Any suggestion would be appreciated.

![image](https://user-images.githubusercontent.com/71069170/107499443-a5c32800-6b9d-11eb-8fc0-4a378bf96a19.png)

**Comment by marcdumais-work** [comment]
Thanks for investigating @danarad05 . 
> I also think that adding the "telemetry.enableTelemetry" preference might work in disabling telemetry but I need to reproduce requests first which I'm unable to do currently.

Not sure about that. It seems that in vscode they have an insight client, that initialises the library and can cause telemetry to be sent to Azure, unless disabled by user. I assume we do not have this client and that any extension that relies on it will not be sendng telemetry, but I could be wrong. 

See this vscode issue (similar to ours) and fix:
https://github.com/microsoft/vscode/issues/47687
https://github.com/microsoft/vscode-extension-telemetry/pull/19/files

Note: I think some standalone MS extensions might have their own telemetry, that does not respect the preference(maybe pre-dating it). Such self-contained cases would probably "work" or at least try to connect to a telemetry server.

**Comment by danarad05** [comment]
Thank you for your input @marcdumais-work. 
What still remains firstly is how to reproduce telemetry requests found by @mikael-desharnais...
