### ISSUE TITLE
Expected behaviour when multiple schemas are matched from schema store

### ISSUE THREAD

**Issue by sapirpol** [eclipse-theia/theia#8322]
### Bug Description:

When opening a `manifest.json` file in theia I get multiple schemas that are matched from schema store.
For example:

![image](https://user-images.githubusercontent.com/30637290/89557985-4f56e480-d81c-11ea-9f7a-ef4978e5b08b.png)

Here you can see auto-complete suggestions coming from both [foxx-manifest schema](https://github.com/SchemaStore/schemastore/blob/f3183484dbc0ed4504651fd6efc1a6035842823b/src/schemas/json/foxx-manifest.json#L217)  and [ui5-manifest](https://raw.githubusercontent.com/SAP/ui5-manifest/master/schema.json)

Is it a bug or a feature? 

### Steps to Reproduce:

1. Checkout theia v1.4.0.
2. Build and run theia - https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start
3. Create `webapp/manifest.json` file.
4. Try auto-complete.

**Comment by bd82** [comment]
The manifest.json name choice seems unfortunate. 

The SchemaStore [catalog](https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json) appears to have multiple entries that can match a `manifest.json`.
- [Foxx Manifest](https://github.com/SchemaStore/schemastore/blob/d7c44777621a0780978ffd795e2f03bd066c6413/src/api/json/catalog.json#L107-L112)
- [UI5 Manifest](https://github.com/SchemaStore/schemastore/blob/d7c44777621a0780978ffd795e2f03bd066c6413/src/api/json/catalog.json#L1371-L1376)
- [Web Manifest](https://github.com/SchemaStore/schemastore/blob/d7c44777621a0780978ffd795e2f03bd066c6413/src/api/json/catalog.json#L1455-L1460)
- [Web Extensions](https://github.com/SchemaStore/schemastore/blob/d7c44777621a0780978ffd795e2f03bd066c6413/src/api/json/catalog.json#L1449-L1454)

Is there any way for the end user to pick & choose which schema should be applied rather than apply all?
