### ISSUE TITLE
Support  new vscode 'in' operator for 'when' clauses

### ISSUE THREAD

**Issue by ronabet** [eclipse-theia/theia#8691]
### Feature Description:
There is a new `in` operator for `when` clauses that vscode added. This new operator allows for a dynamic lookup of a context key's value within another context key's value. For example, if you wanted to add a context menu command to folders that contain a certain type of file (or something that can't be statically known), you can now use the `in` operator to achieve it.

Example:

![Capture](https://user-images.githubusercontent.com/17123155/97843566-31513100-1cf2-11eb-9b75-8a134499754f.PNG)

For more info:
https://code.visualstudio.com/updates/v1_49#_in-operator-for-when-clauses

**Comment by amiramw** [comment]
@danarad05 will look into it

**Comment by danarad05** [comment]
Hi @vince-fugnitto , @akosyakov 
Cc: @amiramw @DoroNahari 

Seems like we need to update**@theia/monaco-editor-core** with latest changes in regard to support "in" in keybind "when" clause.
What I understand currently is that **@theia/monaco-editor-core** is npm package which references microsoft/vscode/.../standalone/0.20.x version. I see that there exists already a branch microsoft/vscode/.../standalone/0.21.x which as far as I understand needs to be updated to @theia version (similar to 0.20.x version - like usage of ContextKeyExpr instead of ContextKeyExpression.

I also found theia-ide/vscode/.../standalone/0.20.x which is referenced in theia code.

Please advise what is process for updating monaco-editor-core?

Thanks
Dan

contextkey.ts used in theia (screen cap when debugging) is same as microsoft/vscode/../0.20.x version:
![image](https://user-images.githubusercontent.com/71069170/98240967-ea25a300-1f72-11eb-9140-e5f174292cab.png)
![image](https://user-images.githubusercontent.com/71069170/98240993-f1e54780-1f72-11eb-950e-db3e5a27b681.png)

**Comment by vince-fugnitto** [comment]
@danarad05 I have never done it myself, but there is some documentation regarding the overall structure and migration steps necessary:
- https://github.com/eclipse-theia/theia/wiki/LSP-and-Monaco-integration

I believe it is still involving by looking at the last update: https://github.com/eclipse-theia/theia/pull/8010.

**Comment by danarad05** [comment]
Thanks @vince-fugnitto , seems to me thought that https://github.com/eclipse-theia/theia/wiki/LSP-and-Monaco-integration is not current - @typefox/monaco-editor-core doesn't look like its maintained:
![image](https://user-images.githubusercontent.com/71069170/98248515-b8660980-1f7d-11eb-88bc-84a2aa9cf534.png)

I think that maybe we switched to working with @theia/monaco-editor-core instead of typefox.

**@akosyakov Please advise**

Thanks

 fyi: @amiramw

**Comment by danarad05** [comment]
@akosyakov Please advise as we are not sure what is flow for updating 0.20x or should it be 0.21.x version? Are you supposed to fork [0.21x](https://github.com/microsoft/vscode/tree/standalone/0.21.x)?

**Comment by RomanNikitenko** [comment]
@danarad05 
Some steps are described here https://github.com/eclipse-theia/theia/issues/7697#issuecomment-638011680

**Comment by RomanNikitenko** [comment]
>  what is flow for updating 0.20x or should it be 0.21.x version?

The question was not to me - sorry - but I believe the answer is:
If required changes exist in 0.21.x of `Monaco` and doesn't exist in 0.20x (so they came in 0.21.x version) then the `Monaco` version should be updated to `0.21`: https://github.com/eclipse-theia/theia/issues/7697#issuecomment-638011680 + adaptation on `Theia` side, like https://github.com/eclipse-theia/theia/pull/8010

**Comment by danarad05** [comment]
Thanks @RomanNikitenko , you are welcome to give your input. 

Who will update @theia/monaco-editor-core version to 0.21x?

**Comment by RomanNikitenko** [comment]
> Who will update @theia/monaco-editor-core version to 0.21x?

I did previous two updates of `@theia/monaco-editor-core`: https://github.com/eclipse-theia/theia/pull/7149 and https://github.com/eclipse-theia/theia/pull/8010 with @akosyakov help.

Unfortunately I'm not sure I can provide the next update - it's not planned in our sprint plan.

@azatsarynnyy could you take a look ^^

**Comment by azatsarynnyy** [comment]
> Who will update @theia/monaco-editor-core version to 0.21x?

Hello @danarad05 
as Eclipse Theia is a result of the community efforts - it can be anyone :slightly_smiling_face: 
Last a couple of times it was @RomanNikitenko who took that responsibility.
Before that, it was @akosyakov 

If you wish, you can contribute by doing the next upgrade of Monaco editor :wink: 
I believe, @RomanNikitenko and @akosyakov can guide you. But keep in mind that it's very time-consuming task.

**Comment by danarad05** [comment]
@RomanNikitenko @azatsarynnyy not sure it is planned for my sprint plan either. 

@amiramw Please advise

**Comment by danarad05** [comment]
@RomanNikitenko 
Hi Roman, 
I might be able to go forward with creating the 0.21.x version. Are you available to support questions as they come up? I presume there is more to go through than explained in [link](https://github.com/eclipse-theia/theia/issues/7697#issuecomment-638011680) you provided - and so I want to know I have someone to reference - so I will waste as little time as possible.
Thanks.

**Comment by RomanNikitenko** [comment]
@danarad05 
Hello, Dan!
I can provide required steps and share my experience related to upgrade `Monaco` version.
At the same time as I mentioned above I did the previous updates with @akosyakov great help.
Anton expedited process on each step, his help especially important on the review step. 
So I believe it would be really nice to gain Anton's support before planing the next upgrade.

**Comment by danarad05** [comment]
@RomanNikitenko Thanks for mentioning that - it's important to know that Anton's support is critical here.

@akosyakov - do you think you would be available for some support on the matter? - I do not know how much support is needed from your side - you and Roman know best.

Thanks
cc: @amiramw

**Comment by marcdumais-work** [comment]
@danarad05 Thanks for bringing-up the Monaco update issue to the dev-meeting. 

Would you open an issue for this specific Monaco update that we need, where we can discuss it? Then I suggest you attempt a PR, even if not everything is clear from the get-go, and let committers help guide you, to refine it. We collectively have all the required knowledge to do this.

**Comment by danarad05** [comment]
> @danarad05 please, open a dedicated issue for upgrading the Monaco editor, as we had for one of the previous upgrades, e.g. #6900

@azatsarynnyy @marcdumais-work  @amiramw 
Opened #8969. Thanks
