### ISSUE TITLE
Implementation of registerWebviewViewProvider VSCode API

### ISSUE THREAD

**Issue by thegecko** [eclipse-theia/theia#8740]
Hi, Arm are interested in implementing the `registerWebviewViewProvider` VSCode API in the medium-term as the status outlines this has yet to be done:

https://che-incubator.github.io/vscode-theia-comparator/status.html

Are there any efforts or plans in progress to do this already and if not, how should we go about implementing this?
Are there any templates for API implementation or similar APIs we could follow?

cc @marechal-p @vince-fugnitto @akosyakov @azatsarynnyy @vince-fugnitto

**Comment by marechal-p** [comment]
Hopefully this helps: https://github.com/eclipse-theia/theia/wiki/Theia-Plugin-Implementation

**Comment by marechal-p** [comment]
Nothing planned on Ericsson's side regarding the `registerWebviewViewProvider` VS Code API.

**Comment by akosyakov** [comment]
Not from our side. There could be some overlap with https://github.com/eclipse-theia/theia/issues/6636 Since webviews, custom editors and views are using the same widget at the end. cc @amiramw

**Comment by akosyakov** [comment]
> Are there any efforts or plans in progress to do this already and if not, how should we go about implementing this?
Are there any templates for API implementation or similar APIs we could follow?

For the extension host process is the best just copy code from VS Code since some extensions sometimes rely on internal APIs and deviation will break it. For the main side you have more flexibility but still looking at VS Code helps.

**Comment by azatsarynnyy** [comment]
> Are there any efforts or plans in progress to do this already

We're not planning to work on it either, in the nearest future.
So, you can take it.

**Comment by amiramw** [comment]
cc @EstherPerelman who is working with me on #6636

**Comment by JonasHelming** [comment]
@thegecko 'WebviewViewResolveContext' seems to be still missing, could you have a quick check?

**Comment by thegecko** [comment]
@JonasHelming, agreed. It looks like `WebviewViewResolveContext` still needs to be implemented. The functionality offered is a very low priority in my opinion, however and we happen to not rely on it in our use case.

**Comment by JonasHelming** [comment]
Would be great to have for full compatibility. Maybe you could add it, now that you are still in the topic? :-)

**Comment by msujew** [comment]
@thegecko Well, not really. I just took the PR over from #10137 and fixed a few minor issues since the original owner was non-responsive.

**Comment by thegecko** [comment]
> @thegecko Well, not really. I just took the PR over from https://github.com/eclipse-theia/theia/pull/10137 and fixed a few minor issues since the original owner was non-responsive.

Ack :)

Perhaps we should just track this as in an issue as functionality to be added?

**Comment by sgraband** [comment]
I looked into taking over the follow up task. Is there really functionality missing? As far as is can see the `WebviewViewResolveContext` interface is already existing. It is just located in the `window` rather than the `root` namespace. The implementation also seems to be like the VSCode one.

So please correct me if i missed something, but it should be sufficient to move the `WebviewViewResolveContext` to the `root` namespace to ensure full compatability.

**Comment by thegecko** [comment]
> So please correct me if i missed something, but it should be sufficient to move the WebviewViewResolveContext to the root namespace to ensure full compatability.

Yes! I see this has been fixed in master here:

https://github.com/eclipse-theia/theia/pull/11216

And this is reflected in the latest comparison too:

https://eclipse-theia.github.io/vscode-theia-comparator/status.html
