### ISSUE TITLE
Color Picker extension doesn't work

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8897]
### Bug Description:
Clicking on "Pick Color" command throws an error that extension activation failed.
Doesn't happen in vscode.

### Steps to Reproduce:

1. Install "Color Picker" extension (anseki.vscode-color) from Open VSX Registry
2. Ctrl + Shift + p
3. Click on "Pick Color"

I get the following error:
Activating extension 'Color Picker' failed.

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: master

**Comment by vince-fugnitto** [comment]
@rayakoren I see that you've opened multiple issues related to extension compatibility. A couple of notes:

> Theia Version: 1.22.5

I'm not sure where this version was picked up from, the latest `theia` version at the time of writing is `1.9.0`: https://github.com/eclipse-theia/theia/releases

When describing issues, please provide as much detail as possible (especially logs).

I noticed that the extension is quite old (~2 years since the last commit), and based on its functionality it is likely to only work in the `electron` target if at all. Please be sure to have satisfied the following as well: https://open-vsx.org/extension/anseki/vscode-color#install.

**Comment by rayakoren** [comment]
@vince-fugnitto Thanks. I'm tested some extensions on local Theia, version master, I changed the version in all issues accordingly.

**Comment by rayakoren** [comment]
@vince-fugnitto I checked it in electron, it doesn't work there too, I get: 
Activating extension 'Color Picker' failed: Cannot find module '/.theia/extensions/anseki.vscode-color-0.4.5/extension/extension' Require stack: - /theia/packages/plugin-ext/lib/hosted/node/plugin-host-rpc.js - /theia/packages/plugin-ext/lib/hosted/node/plugin-host.js

**Comment by vince-fugnitto** [comment]
The extension does not work in vscode either with multiple errors in the dev-console.
I believe the native `vscode-css` support should be used instead which provides a color-picker for css.
