### ISSUE TITLE
Log File Highlighter extension doesn't work

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8899]
### Bug Description:
Nothing is highlighted in a log file.
Doesn't happen in vscode.

### Steps to Reproduce:

1. Install "Log File Highlighter" extension (emilast.logfilehighlighter) from Open VSX Registry
2. Reload Theia IDE
3. Open log file: *.log (with dates, times and log levels)

Nothing is highlighted as in the following screenshot:

<img width="928" alt="Screen Shot 2020-12-24 at 13 50 20" src="https://user-images.githubusercontent.com/49866055/103087164-40b47280-45ef-11eb-9802-e257a76add49.png">

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: master

**Comment by danarad05** [comment]
FYI:
@rayakoren 
cc: @amiramw 
On windows it seems to work:
![image](https://user-images.githubusercontent.com/71069170/103404799-8c21d000-4b5d-11eb-9ce1-d4a8194a2543.png)
![image](https://user-images.githubusercontent.com/71069170/103404807-993ebf00-4b5d-11eb-9d43-b4b97f516a69.png)

**Comment by amiramw** [comment]
and on gitpod?

**Comment by rayakoren** [comment]
@danarad05 It seems like it's the regular highlighting and not the one from the extension.
Did you reload Theia after installing the extension? 

@amiramw It doesn't work for me on gitpod.

**Comment by danarad05** [comment]
@rayakoren 
cc: @amiramw 
1. You were right I got the default styling before.
2. Played with it some more and found that on windows (I'm mentioning it because I can't check on macOS) highlighting works but just the "logFileHighlighter.customPatterns" settings and not "editor.tokenColorCustomizations" (as they are not supported currently in Theia).
![chrome-capture (1)](https://user-images.githubusercontent.com/71069170/103652653-127a4f80-4f6c-11eb-96a7-999033996a80.gif)
Also works in Gitpod:
![image](https://user-images.githubusercontent.com/71069170/103653313-0a6edf80-4f6d-11eb-8513-6c83e7539ba1.png)

**Comment by vince-fugnitto** [comment]
The extension works fine as previously mentioned:

![image](https://user-images.githubusercontent.com/40359487/199820614-58f1cf67-0078-4d40-b420-297b5fb3e25e.png)

Supporting `editor.tokenColorCustomizations` is a different feature.
