### ISSUE TITLE
Icons are missing in Java Projects Panel

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8905]
### Bug Description:
The icon of "Export Jar" and the command of "Collapse All" are missing in Java Projects Panel.
Works in vscode.

### Steps to Reproduce:

1. Install Project Manager for Java (vscjava.vscode-java-dependency) from Open VSC Registry
2. Install Language Support for Java(TM) by Red Hat (redhat.java) from Open VSC Registry
3. Open a java project

In the Java Projects panel, the icon of "Export Jar" and the command of "Collapse All" are missing:

In Theia:
<img width="322" alt="Screen Shot 2020-12-24 at 20 52 42" src="https://user-images.githubusercontent.com/49866055/103103528-4b402d80-462a-11eb-9872-573f5cc3e980.png">

In vscode:
<img width="363" alt="Screen Shot 2020-12-24 at 20 55 41" src="https://user-images.githubusercontent.com/49866055/103103560-7dea2600-462a-11eb-93d3-8ce63589c8c1.png">

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: master

**Comment by vince-fugnitto** [comment]
@rayakoren I believe in order to get the latest icons we would need a monaco update (`codicons` are contributed by the `@theia/monaco-editor-core`). 

- [export jar](https://github.com/microsoft/vscode-java-dependency/blob/d2f9b37715b290dbfb0d53ee0b7dc5c025446244/package.json#L119-L123) uses the `export` icon which is not available in our version

You can view our `codicons.css` by the following path:
`node_modules/@theia/monaco-editor-core/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.css`

**Comment by vince-fugnitto** [comment]
The following is now supported :+1: 


https://user-images.githubusercontent.com/40359487/125505659-8ebe9905-5996-4a08-bf60-d761b30bf43d.mp4
