### ISSUE TITLE
Request 'setStorageValue' failed on closing file without workspace when SQLTools extension is install

### ISSUE THREAD

**Issue by odeliat** [eclipse-theia/theia#8963]
### Bug Description:

When I install SQLTools extension and close file without workspace I get this error: (attached screen video)
```
root ERROR [hosted-plugin: 12752] Promise rejection not handled in one second: Error: Request setStorageValue failed with message: Cannot save data: no opened workspace , reason: Error: Request setStorageValue failed with message: Cannot save data: no opened workspace
root ERROR [hosted-plugin: 12752] With stack trace: Error: Request 'setStorageValue' failed
    at Proxy.<anonymous> (http://localhost:3000/bundle.js:143539:33)
    at StorageMainImpl.push.../../packages/plugin-ext/lib/main/browser/plugin-storage.js.StorageMainImpl.$set (http://localhost:3000/56.bundle.js:9109:34)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://localhost:3000/39.bundle.js:1207:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://localhost:3000/39.bundle.js:1192:41)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.receiveRequest (http://localhost:3000/39.bundle.js:1156:31)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.receiveOneMessage (http://localhost:3000/39.bundle.js:1125:22)
    at http://localhost:3000/39.bundle.js:1017:109
    at http://localhost:3000/39.bundle.js:1232:17
    at http://localhost:3000/bundle.js:141091:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:141106:39)
```
The error is in file packages\plugin-ext\src\main\node\plugins-key-value-storage.ts:59 (set method)

https://user-images.githubusercontent.com/14539932/104882035-04183480-596b-11eb-9275-88f4b506734c.mp4

I created a new extension with the use of workspaceState and got the same error but did get the string:

```
context.workspaceState.update("obj", "hi");
const msg = context.workspaceState.get("obj");
vscode.window.showInformationMessage(msg);
```
TheSQLTools also use the [same code](https://github.com/mtxr/vscode-sqltools/blob/b8938cafa59dd378d22a7ef24ecb710de51b400e/packages/plugins/connection-manager/attached-files.ts)

### Steps to Reproduce:

1. Run the server locally.
2. Install the [SQLTools](https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools).
3. Make sure there is no open workspace.
4. Open a random file.
5. Close that file.
6. Get the error on the server side.

### Additional Information

- Operating System: Local
- Theia Version: master

**Comment by vince-fugnitto** [comment]
@odeliat based on the condition, are you certain it's an actual issue? A workspace must be opened before you can set the the storage:

https://github.com/eclipse-theia/theia/blob/50b636b9eb4064b6651ef42882cec5bda5b37440/packages/plugin-ext/src/main/node/plugins-key-value-storage.ts#L56-L62

The same is true for `workspaceState`, based on the documentation, it applies to only opened workspaces:

![image](https://user-images.githubusercontent.com/40359487/104919643-9406b000-5964-11eb-8393-45e067c540dc.png)

**Comment by odeliat** [comment]
@vince-fugnitto This issue happens in Theia but not in vscode.
In vscode I am able to open and save files without a workspace. I tried the extension in vscode and didn't get the error. 
In Theia I am also able to do that (system files) but I get this error. 

The set method is activate but the `kind` parameter is empty and that is why we get the error thrown in line 59.

**Comment by vince-fugnitto** [comment]
@odeliat I'm not sure what you're expecting, by design the storage only works when a workspace is present:

https://github.com/eclipse-theia/theia/blob/b6add4a6e6e97cbdff73279fab0a0b116576ccb5/packages/plugin-ext/src/main/node/plugins-key-value-storage.ts#L56-L60

https://github.com/eclipse-theia/theia/blob/b6add4a6e6e97cbdff73279fab0a0b116576ccb5/packages/plugin-ext/src/main/node/plugins-key-value-storage.ts#L91-L97

https://github.com/eclipse-theia/theia/blob/b6add4a6e6e97cbdff73279fab0a0b116576ccb5/packages/plugin-ext/src/main/node/paths/plugin-paths-service.ts#L60-L69

When no workspace is present, the path is `undefined` meaning that storage is disabled and should not occur.

If you're looking to set storage independent of the workspace, then `globalState` should be used instead of `workspaceState`:

![image](https://user-images.githubusercontent.com/40359487/105049024-39d81e80-5a3a-11eb-8125-b39fd89d5925.png)

Note: I cannot tell what `vscode-sqltools` is doing since their extension code is obfuscated.

**Comment by danarad05** [comment]
@odeliat @vince-fugnitto @amiramw 
created small PR for this issue. You can call it a minor validation for case where extension sends false indication (it sends argument _isGlobal_ = false  - when workspace exists and when it doesn't).
