### ISSUE TITLE
Intellicode VSCode Extension + Java LSP - No Suggestions in Gitpod Theia

### ISSUE THREAD

**Issue by veredcon** [eclipse-theia/theia#9038]
### Bug Description:
There are no starred suggestions provided by intellicode in Java files.

### Steps to Reproduce:

1. Open master theia with gitpod
2. Install latest Language Support for Java by redhat - https://marketplace.visualstudio.com/items?itemName=redhat.java - 0.74.0
3. Install IntelliCode https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode - 1.2.11

Screenshot from gitpod:
![image](https://user-images.githubusercontent.com/9718939/107217559-007e4780-6a17-11eb-873c-d28766160f10.png)

Screenshot from VSCode:
![image](https://user-images.githubusercontent.com/9718939/107219345-9dda7b00-6a19-11eb-89a3-aef9e59c56f1.png)

### Additional Information

- Operating System: Linux
- Theia Version: 1.10.0

**Comment by vince-fugnitto** [comment]
@veredcon thank you for the issue, please note that `intellicode` is a proprietary extension which is illegal to use in products outside the vscode family according to their [license](https://marketplace.visualstudio.com/items/VisualStudioExptTeam.vscodeintellicode/license) (which is another reason it is not present under the open-source [open-vsx extension registry](https://open-vsx.org/)).

> INSTALLATION AND USE RIGHTS. You may install and use any number of copies of the software to use **solely** with Microsoft Visual Studio family of products and Microsoft Azure Data Studio.

The extension is closed-source and is difficult to identify what missing API(s) it uses in order to function correctly. If you can please provide additional logs, console errors which may identify what APIs are missing it would certainly help but as mentioned the extension is proprietary and should not be used.

**Comment by veredcon** [comment]
Thanks @vince-fugnitto for your reply! We had a requirement to add the intellicode but we understand it cannot be done.
Therefore I'm closing this issue in this stage.
Thank you!
