### ISSUE TITLE
Excessive WS channel usage blocks bi-directional communication between FE and BE

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#9063]
### Bug Description:

Communication between the FE and the BE is blocked if the WS channel is excessively used.

Let assume the following scenario:
 - The FE requests the BE to `start` sending messages periodically. (with 1 ms interval)
 - Every 1 ms, the BE sends a `notification` message to the FE.
 - The FE gets the `notification` message and logs it to the _Output_, for example.
 - After some time, the FE requests the BE to `stop` sending messages.
 - Currently, the FE's `stop` request must wait for all already sent `notification`s to arrive from the BE, then the message sending can be interrupted. This blocks the service communication and makes the UX quite bad.

### Steps to Reproduce:

1. Check out [my example](https://github.com/eclipse-theia/theia/compare/master...kittaakos:ws-channel-blocks?expand=1).
2. Start the app, and execute the `Toggle messages from backend` command. The BE will send a message to the FE in every ms. Open the `API Sample: Send` output channel and see the notifications from the BE.
3. Execute the `Toggle messages from backend` again, to request the stop. It takes so much time until the BE service has the chance to receive the stop request.

Behavior with 1ms notification interval:

https://user-images.githubusercontent.com/1405703/107793482-9fc47700-6d56-11eb-86ba-f7c6f6eb81bb.mp4

If I change the notification interval to a reasonable time interval, 100ms, it works:

https://user-images.githubusercontent.com/1405703/107793734-edd97a80-6d56-11eb-95a4-aa8b758d663e.mp4

### Additional Information

- Operating System:
- Theia Version:

**Comment by marechal-p** [comment]
> * Currently, the FE's `stop` request must wait for all already sent `notification`s to arrive from the BE, then the message sending can be interrupted. [...]

I tried your example and this point seems wrong: If you add a `console.log('toggle')` in the backend method that handles the command, you can see that the code is triggered almost as soon as you execute the command. What we see in the output where it goes on and on is due to data buffering and the output view taking too much time processing the stream, but the sending stopped a while ago.

Now it is true that while a channel is busy reading messages from a given channel, others consecutive messages will have to "wait for their turn" before being processed. This will always be a problem as long as we try to multiplex streams over a given TCP stream. So far we expected services to not do these kind of things, but if we want to minimize the problem we might have to open concurrent WS connections again. Your issue makes a good case for that at least. What do you think? Do you see other solutions?

**Comment by kittaakos** [comment]
> I tried your example and this point seems wrong: If you add a `console.log('toggle')` in the backend method that handles the command, you can see that the code is triggered almost as soon as you execute the command.

You're right. Thank you for looking into this, it was very helpful. 🙏 

> but if we want to minimize the problem we might have to open concurrent WS connections again.

Yes. This seems to be one possible approach at least to try. I am going to experiment with this and other ways and leave them here as part of my example.

**Comment by kittaakos** [comment]
I've changed the way how this should work. Instead of pushing the messages to the WS channel from the BE, I let the FE ask for new messages if there are any. This way, the app remains responsive. I did not want to create additional WS connections, as the problem would be the same. All posted messages must arrive.

[Here](https://github.com/eclipse-theia/theia/compare/master...kittaakos:ws-channel-blocks-vol2?expand=1) is the reworked example. Obviously, it's not production-ready, but one can get the idea.

Here it is in action:

https://user-images.githubusercontent.com/1405703/107931000-08d90400-6f7c-11eb-9dcd-68e96a07a6ac.mp4

Closing.
