### ISSUE TITLE
Performance of vscode.workspace.fs.readDirectory(Uri) is worse by *100 compared to vscode

### ISSUE THREAD

**Issue by idantr** [eclipse-theia/theia#9514]
### Bug Description:
Update the description after comments by @vince-fugnitto : 
When calling to vscode.workspace.fs.readFile(Uri)  the amount of time it takes differ significally from the times of the same code in vscode:
Running the our code in vscode locally we get response times of ~15 ms 
![VSCODE Local](https://user-images.githubusercontent.com/10183179/120463379-85b1b180-c3a4-11eb-92c2-7f1d744240dc.JPG)

When running the code in Theia via electron locally  n ~597ms range on the same file
![Theia Electron Local](https://user-images.githubusercontent.com/10183179/120463770-e93bdf00-c3a4-11eb-8842-9db4bb9a9419.JPG)

** also we saw that in vscode that consecutive calls are even faster

### Steps to Reproduce:

1. Create a very simple vscode plugin using the following code:
```
import * as vscode from 'vscode';
import * as _ from 'lodash';
import { promises as fs } from 'fs';
import * as path from 'path';
 
export async function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(vscode.commands.registerCommand('idan-test.readDirs', async () => {
        const baseUri: vscode.Uri = _.get(vscode.workspace.workspaceFolders, "[0].uri");
        const plUri: vscode.Uri = vscode.Uri.file(path.join(baseUri.fsPath, "package-lock.json"));
 
        const before = Date.now();
        const contentVscode: Uint8Array = await vscode.workspace.fs.readFile(plUri);
        const after = Date.now();
        vscode.window.showInformationMessage(`Result VSCODE - ${after - before}`);
        
        const beforeNode = Date.now();
        const contentNode = await fs.readFile(path.resolve(plUri.fsPath));
        const afterNode = Date.now();
        vscode.window.showInformationMessage(`Result NODE - ${afterNode - beforeNode}`);
    }));
}
```
2. in you `projects` folder insert the following file
[package-lock.json.txt](https://github.com/eclipse-theia/theia/files/6583849/package-lock.json.txt)
(remove the ".txt" in the end)
package-lock.json  486k

### Additional Information

- Operating System:  WIN10
- vscode 1.56.0
- theia latest master code revision 583220b2ecae38bf16f89403417c68e4c191d1dc

**Comment by vince-fugnitto** [comment]
> When running the our code in vscode locally we get response times of ~4-10 ms to get 4 directories and a few files
When running the code in Theia in gitpod using Theia as the UI we are getting response times in ~400ms range to query the same project

@idantr we aren't really comparing similar things or under similar circumstances.

We are comparing vscode _locally_ versus theia in the cloud (through gitpod with likely a server which is far away and will affect the response time due to the roundtrip). It would be better to get measurements of a similar use-case, perhaps vscode and theia locally (through electron) if we want to say it is "worse by 100* compared to vscode".

**Comment by vince-fugnitto** [comment]
Possibly related: https://github.com/eclipse-theia/theia/issues/8242#issuecomment-664372908.

**Comment by paul-marechal** [comment]
> When running the code in Theia in gitpod using Theia as the UI we are getting response times in ~400ms range to query the same project

Please try to trace this to know precisely where the time is spent.

**Comment by idantr** [comment]
After running the same in theia local browser vs. vscode the response times are the same
When running the same api vs. prallel node api i got response times of one factor better in node
example theia: 10ms to read 9-11 dirs 
node: took 1ms

**Comment by idantr** [comment]
After testing I saw the same behavior in clean vscode. i will open an issue to vscode and close this issue

**Comment by idantr** [comment]
@vince-fugnitto i updated the initial description.
i now tested theia running with electorn vs. vscode, both running locally and there is a significant reduction is performance in theia.
we get it in several filesystem api we tested , (readDirectory readFile)
can this be improved somehow?

**Comment by paul-marechal** [comment]
> can this be improved somehow?

PRs are welcome at the moment.

**Comment by idantr** [comment]
@vince-fugnitto @paul-marechal 
We did some more debugging and found that most of the time is spent in the RPC calls from frontend to the backend and back
those 2 calls on every request take most of the time.
Can we optimize the call from the plugin host to use node 'fs' directly when we identify the the uri is a real file system?
how would you suggest to continue? create a new dedicated provider for it?

**Comment by paul-marechal** [comment]
I don't know how this system works well enough, so I am not sure what the main approach should be.

From what I understand, you are saying that there are useless round trips happening? It makes sense to me that if we can avoid going to the frontend and back for no good reason then we should avoid it. Feel free to prototype something, I cannot dig deep enough to help you right now.

**Comment by idantr** [comment]
this issue is critical for us as our stakeholder are using theia extensively and we would like that they use vscode public api's and not custom code just for performance reasons.
@paul-marechal should this issue be raised in next the theia dev meeting? or would you recommend that to start a poc?

**Comment by paul-marechal** [comment]
@eclipse-theia/plugin-system anyone aware of this issue or has pointers for @idantr?

**Comment by tsmaeder** [comment]
@idantr You mentioned that the time is spent doing remote calls, is this wall clock time or do you you have any more detailed data on where in the code the time is spent? 

Do you have an idea which messages are sent over the wire? In particular, are the contents of the file being streamed (onFileStreamData) or sent as a single message?

**Comment by idantr** [comment]
@tsmaeder yes we did measurements in strategic places in the code when running on electron locally
these are the results in ms i printed:
root INFO ******** time readFile for disk-file-system-provider.ts = 3    -> [link](https://github.com/eclipse-theia/theia/blob/7d3b1d3b33cb565ec07965e5baf10c926006cdfd/packages/filesystem/src/node/disk-file-system-provider.ts#L258)
root INFO ******** time for $readFile in file-system-main-impl.ts = 232 -> [link](https://github.com/eclipse-theia/theia/blob/7d3b1d3b33cb565ec07965e5baf10c926006cdfd/packages/plugin-ext/src/main/browser/file-system-main-impl.ts#L102)
root INFO [hosted-plugin: 45460] ******** time for readFile in file-system-ext-impl.ts = 533 [link](https://github.com/eclipse-theia/theia/blob/92a7d05c35b43a72560a514d51d1a65be3ff5899/packages/plugin-ext/src/plugin/file-system-ext-impl.ts#L152)

so the call to fs.readFile is quick and is performed in the backend
to get the this call and back takes most of the time (remote calls same time for forward and same for back).
readFileStream was not called anywhere in the local flow.

in our implementation of theia i saw 2 singular websocket calls, one for each direction.

**Comment by paul-marechal** [comment]
[`file-system-main-impl.ts` is running in the browser runtime](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/main/browser/file-system-main-impl.ts#L91-L100), knowing that extensions are running on the backend this means the API goes backend to frontend and back... But since you tested on Electron we still serialize those calls over RPC, it seems surprising for it to take that long when everything's local.

I'd say what you measure paints an interesting picture, but it's still not clear what is causing this or where exactly the time is spent...

**Comment by tsmaeder** [comment]
@idantr thanks for the analysis, this is useful data. @paul-marechal I would be surprised if this was related to the data transfer time over the wire: As I understand it, we're talking about small text files (< 10kb). Over a 10mb/s line, that would take 10ms to transfer. So I'm not surprised that over the wire is +/- the same as electron. My money is on JSON.stringify(), but that's just a hunch.
@idantr while you have the measurement infrastructure in place: does it make a difference if you transfer large files vs. small files?

**Comment by slavik-lvovsky** [comment]
These are the required measurements:

1k file - 13-18 ms
5k file - 20-30 ms
62k file - 90-110 ms
477k file - 470-490 ms

**Comment by tsmaeder** [comment]
![chart](https://user-images.githubusercontent.com/13163770/122000177-b2a39280-cdae-11eb-906b-eedff9b40caf.png)

That looks pretty much linear with file size or slightly decreasing

**Comment by tsmaeder** [comment]
A quick inspection has revealed numerous areas for improvement:

1. Back end services are invoked through vscode-jsonrpc, which uses JSON.stringify() to encode messages. VS Code has it's own message protocol, which does not json-encode raw buffers.
2. For plugins, we run our own RpcProtocol implementation on top of the back end service protocol, which means we're encoding the same message twice
3. JSON.stringify() seems to grow linearly with the size of the encoded object, so at least it's O(n), like any sending of messages would be.
4. The size of the content response message in our services is about 3 times the size of the file we're reading: using json-encoded number arrays is very inefficient. A 1.43mb file results in an around 4.3 mb response message.

The lowest hanging fruit would probably be to encode the byte arrays for the file content more smartly. However, I believe in the long run we'll have to throw out the vscode-jsonrpc package and use our own implementation to have more control message serialisation.

**Comment by tsmaeder** [comment]
I've recently refactored RPCProtocol to be independent of plugin concerns, so I believe it could now be a base for replacing vscode-jsonrpc.

**Comment by tsmaeder** [comment]
t.b.h, I don't think this is an issue with JSON.stringify() or JSON.parse(): experimenting with those calls yields much smaller run times: 

```
interface Foo {
    foo: number[];
}


let obj: Foo = {
    foo: []
}

for (let i= 0; i < 500000; i++) {
    obj.foo.push(i);
}

let start = new Date();
let stringed = JSON.stringify(obj);
stringed = JSON.stringify(stringed);

let copy = JSON.parse(stringed);
copy = JSON.parse(stringed);

let end= new Date();

console.info(end.getTime()-start.getTime());
```

finishes in 30 milliseconds.

**Comment by slavik-lvovsky** [comment]
If JSON.stringify does not cause the performance degradation, what could be a reason for the issue?

**Comment by tsmaeder** [comment]
@slavik-lvovsky your guess is as good as mine at this point in time; investigation is needed.

**Comment by tsmaeder** [comment]
An obvious (although not trivial) improvement we could make is this: when we hook up services from plugins to the browser, we forward the messages something like this in the back end: 
```
connectionFromPluginHost.onMessage(message) {
   connectionToBrowser.send(message);
}
```
So we're always waiting to fully read the message from the plugin until we forward it to the browser (and vice-versa as well). This means that forwarding a message will roughly take double the time it takes to send a message over a single hop. 
Alternatively, we could just stream the messages to the browser side instead: read a small bit of data and immediately send it to the browser. That way the time would be x+delta instead of 2x. For small messages it doesn't make a difference, but for large ones, it does.

**Comment by tsmaeder** [comment]
Especially with file system calls (which go from plugin-host to back-end to browser and back to the back end and optionally to a plugin), we could save quite some time on large messages. 
Absent a streaming message router, using that streaming file read API might help in this case. We're not using it at this time, I believe)

**Comment by tsmaeder** [comment]
I did a very simple test reading 500kbytes from a raw nodejs websocket on localhost: reading 500k took 13ms. This seems consistent with the numbers VS Code is getting. So the performance hit _really is_ in the communication layers we add on top of websocket. Here's the client code:

```
    let t0;

    const ws = new WebSocket('ws://localhost:9898/');

    ws.onopen = function () {
        console.log('WebSocket Client Connected');
        t0 = performance.now();
        ws.send('Hi this is web client.');
    };

    ws.onmessage = function (e) {
        const t1 = performance.now();
        console.log(`request took ${t1 - t0} milliseconds.`);

        console.log("Received: '" + e.data.length /1000 + " kbytes'");
    };
```

and here's the server:

```
wsServer.on('request', function(request) {
    const connection = request.accept(undefined, request.origin);

    connection.on('message', function(message) {
      console.log('Received Message:', message.utf8Data);
      connection.sendUTF(msg);
    });
    connection.on('close', function(reasonCode, description) {
        console.log('Client has disconnected.');
    });
});
```

**Comment by tsmaeder** [comment]
I was able to gain about 25% on a 3 mb file by using a WebsocketChannel for communicating with the plugin host instead of passing the messages through the "PluginsServer" back-end service. The difference being that the message is JSON-encoded only twice (once for the rpc protocol, once for the WS channel) instead of 3 times. I would expect further savings to be had by changing or message encoding strategy for the WS Channel.

**Comment by tsmaeder** [comment]
Spoke too soon, the results are not repeatable...where the time goes remains a mistery.

**Comment by tsmaeder** [comment]
I'll have some time to investigate this issue next week or so.

**Comment by EstherPerelman** [comment]
> I'll have some time to investigate this issue next week or so.

@tsmaeder have you found the time for this issue?

**Comment by tsmaeder** [comment]
Unfortunately, my time evaporated due to https://github.com/eclipse-theia/theia/pull/10333 If you have some time to invest into the analysis of this issue, please go ahead.

**Comment by tsmaeder** [comment]
I've noticed a problem with encoding UInt8Array objects with JSON.stringify(): the resulting string is around 11 times bigger (in characters) than the number of bytes in the array: sending a string of 675k bytes over a vscode-jsonrpc call takes ~40ms, but sending a UInt8Array of length 675k takes ~700ms. I think we're starting to see where the problem resides. Thinking about how we can encode our messages more efficiently.

**Comment by paul-marechal** [comment]
I didn't look at the APIs involved but if we need to send `UInt8Array` over JSON we may need to encode them using base64?

**Comment by tsmaeder** [comment]
@paul-marechal that's what we'll have to do. The question is _how_ to do it? Ideally, we could provide a solution that automatically makes encoding RPC messages efficient without  clients (service implementations) having to deal with it. It would also be nice to preserve readability of message traffic for debugging and logging.
But first, we need verification that encoding the file contents efficiently will actuallly solve the problem.

**Comment by tsmaeder** [comment]
It gets courioser and courioser: when I create a binary buffer of 675000 bytes and use BinaryBuffer.toString() and then send that over jsonrcp, it takes ~400ms, whereas if I just take a string of 675000 characters (the chars being numbers from 1-8), transfering the string takes ~60ms. My suspicion is that sending the string over the websocket encodes differently for ascii chars than for random values. Investigating further.

**Comment by tsmaeder** [comment]
The encoding suspicion seems to hold up: making sure the bytes are between 65 and 73 ('a'..'h'), makes the transfer fast again.

**Comment by tsmaeder** [comment]
I've pushed a branch with my experiments to https://github.com/tsmaeder/theia/tree/9514_encoding_experiments

I'm using a weird kind of base64 encoding (see base64.ts) and got loading the 1.3mbytes file down to ~400ms from around 2000 ms. Note that using sockets in a way that does not require encoding of buffers (because websockets can transfer binary,) would be preferable. Reading a file of 475k from a plugin took around 150ms. Still a long way from the 15ms reported for VS code and the ~50ms I would expect from our code base.

**Comment by tsmaeder** [comment]
Using byte arrays (uint8array) and sending those over the socket (instead of strings) I can read a 475k file in 80ms from a plugin this is ~5 times longer than what the issue creator experienced. This number is similar in both the browser and electron cases.

Maybe more improvments can be made by using a 0-copy message sending scheme and perhaps using shared memory where appropriate (electron, but also back-end->plugin host)

**Comment by tsmaeder** [comment]
I have updated the experimental branch with my latest code: https://github.com/tsmaeder/theia/tree/9514_encoding_experiments

What it does:

1. Gets rid of JSON-RPC's `MessageConnection` and instead uses the WebsocketConnection
2. Uses a "MessageEncoder" to encode messages in binary format into a `BinaryBuffer` everywhere
3. Transfers binary data over websocket instead of strings
4. Adapted ProxyFactory to use a new `RPCProtocolImpl` class that uses the above
5. Adapted plugin system `RPCProtocolImpl` to use the above message encoding infra
6. Adapted everything around those changes to function minimally. 


__do not use this code!!!__ it's hacked into compliance in a bad way ;-)

**Comment by tsmaeder** [comment]
### Conclusions

Main learning: Encoding/Decoding binary data accounts for most of the performance problem. We can achieve similar performance to what VS Code does by avoiding unnecessary encoding/decoding steps for large messages

### Recommendations

1. Use the same protocol everywhere
We have different message encoding infrastructures in place for plugin main/ext remote calls and Theia back-end/front-end services. It would be easier if we could use the same infrastructure for encoding/decoding remote call messages.
2. Send binary data where possible
In the end, we always send bytes over a connection: using a string-based API will just encode that string in the end but outside of our control.  We should also have a good look at what comms APIs are _reall_ doing: for example `ChildProcess.send` will use `JSON.stringify()` on anything but a string or primitive.
3. Make message sending 0-copy/write-through
Right now we are creating message objects and then passing them to a channel. This style means that if we wrap messages at lower levels (for routing, for example), we always have to encode the message (because only the upper level knows how to encode that particular message) first and then copy the resulting buffer to the lower-level message buffer.  We should not be creating message objects and pass them to the lower levels, but instead directly write the encoded values to a message buffer that is managed by the lower level protocol. 
4. Use efficient transfer mechanisms
Depending on the situations (local/remote processes, etc.) we should evaluate what the most efficient way to transfer binary values is. For example, `ChildProcess.send()` between the back end and the plugin host seems to be wasteful.

**Comment by ChayaLau** [comment]
@tsmaeder - we are experiencing a general performance issues in all of the file system actions.
we are trying to figure out if the slowness when expanding a folder in the file explorer is related to this issue.

**Comment by tsmaeder** [comment]
@ChayaLau I can't really say, because I did not analyze that scenario. However, if we make message sending generally faster, every remote call should profit. 
I would recommend that you instrument the corresponding call in both the DiskFileSystemProvider in the back end and the RemoteFileSystemProvider in the front end. If you get a lot of difference for the same operations, message sending is a contributing factor. But there might be other reasons, for example doing unnecessary work or bad caching strategies.

**Comment by tsmaeder** [comment]
I jotted down an attempt at a write-through RPC framework here: https://github.com/tsmaeder/message-rpc I call it the "nochebuena" code drop :-)

**Comment by tsmaeder** [comment]
I can read a file from disk via a pass-through channel in ~3ms, which is basically the time it takes to read from disk. If we put this together with the experiment above writing through a web socket, I think this is promising.
