### ISSUE TITLE
Drag & Drop progress status

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#970]
Drag & Drop should have a way to display a progress status or some indication about the dropping remaining time. It could be displayed in the status bar.

**Comment by vince-fugnitto** [comment]
I believe we can use #5959 as a means to show progress for dnd events.

**Comment by lmcbout** [comment]
If you use the using >TXT: commands from https://github.com/AlexTugarev/txt/raw/master/txt-0.0.1.vsix
from issue https://github.com/eclipse-theia/theia/pull/5830
You will notice that if you close the progress window, it still shows on the status bar, I think this is the only thing missing for this issue to be solved. The progress dialog is good also for the D&D

**Comment by vince-fugnitto** [comment]
I thought that it can be handled generally as a progress in the `explorer`. 
Any time you have a long process (ex: cloning a repo and populating the explorer, dnd into the explorer, copy and paste into the explorer). I'm not sure a statusbar entry is necessary.

Also, it can potentially be handled by https://github.com/eclipse-theia/theia/pull/5535.

Do we really need or want a statusbar item displaying the progress? Perhaps a notification is better?

**Comment by vince-fugnitto** [comment]
@lmcbout I tested `master` and I believe it is sufficient.
When performing a dnd, a notification is triggered where we can see the progress of the upload.
We also have the ability to **cancel** the upload:

<div align='center'>

![v](https://user-images.githubusercontent.com/40359487/64888229-6c992800-d638-11e9-8049-b27f9cc24822.gif)


</div>

In my example you can see I cancelled prematurely, and not all files from `theia` were copied.
I believe this should meet the requirements of the issue.

**Comment by AlexTugarev** [comment]
@akosyakov @lmcbout @vince-fugnitto isn't this issue resolved already with the current upload progress message?

if it'd be a goal to indicate that progress in the EXPLORER as well, it could be done for the mentioned #5959 and also with the improvement from #6043. please be aware that those indicators do not support cancellation. OTOH the current progress notification can be hidden with ESC key, so you may loose the option to cancel as well.

I'm not sure if this issue is up-to-date, it also says `It could be displayed in the status bar`, which as far as I can see it mostly used for progress of background services/processes (e.g. LS initialization etc)

**Comment by vince-fugnitto** [comment]
> @akosyakov @lmcbout @vince-fugnitto isn't this issue resolved already with the current upload progress message?

Yes, I agree with you @AlexTugarev, the current upload progress message is sufficient (https://github.com/eclipse-theia/theia/issues/970#issuecomment-531356973). We have the ability to see a notification about a in-progess dnd, and also have the ability to cancel it. I believe this meets the requirements.
