### ISSUE TITLE
Redundant dependency of Theia Blueprint

### ISSUE THREAD

**Issue by linhanyu** [eclipse-theia/theia#9790]
![image](https://user-images.githubusercontent.com/17355591/127277582-4c9ad70f-7a84-4f86-8355-b33744b0baa8.png)

There is a redundant dependency of electron, made theiaBluePrint package has two electron executable(one from electron package, one from redundant dependency of theia/electron).
In 1.11.0, we can simply remove theia/electron and add native dependency in final package.json. But after 1.13.0, there are dependency of theia/electron in theia/core, which made we impossible remove theia/electron as before

**Comment by vince-fugnitto** [comment]
@linhanyu did you mean to open the issue at https://github.com/eclipse-theia/theia-blueprint? - there is already the following issue https://github.com/eclipse-theia/theia-blueprint/issues/48.

> But after 1.13.0, there are dependency of theia/electron in theia/core

It is not a dependency but a `peerDependency`, it expects `@theia/electron` to be present for the electron use-case, but should not automatically pull it.

**Comment by linhanyu** [comment]
Yes.We moved @theia/electron@1.11.0 to devDependency and native dependency(such as fs-extra) to dependencies, it's work well. But I can't do so after @theia/electron@1.13.0

**Comment by vince-fugnitto** [comment]
@linhanyu I believe that `@theia/electron` should not be a `devDependency`. 

To resolve the issue you can update your `electron-builder` configuration to exclude the nested `electron` when packaging, since `electron-builder` includes it's own version. In the future we can attempt to find a generic solution to the issue in the framework itself as to not make downstream applications have to each update the packager this way.

**Comment by linhanyu** [comment]
It works, thanks!

**Comment by vince-fugnitto** [comment]
> It works, thanks!

Great to hear! I'll close the issue for the moment since we have one tracking it already in `theia-blueprint`.
We will then try to identify a way to handle the `electron` dependency from the framework more cleanly.
