### ISSUE TITLE
Layout cannot restored when a large binary file is opened.

### ISSUE THREAD

**Issue by shuyaqian** [eclipse-theia/theia#9843]
### Bug Description:
Layout cannot restored when a large binary file is opened.

### Steps to Reproduce:

1. open a large binary file
2. refresh page
3. page cannot be restored.
![image](https://user-images.githubusercontent.com/6367259/128286640-076146d4-5d89-4f7d-8dc8-fb72958ddd28.png)

The output error:
![image](https://user-images.githubusercontent.com/6367259/128286522-8bfff879-d49e-4280-9c3e-d61c6b65337b.png)

I find that the error is reported here. Does the judgment of object equality need to be modified?
![image](https://user-images.githubusercontent.com/6367259/128286733-06e7eba3-4b66-4976-aa05-de97007d6ac2.png)

### Additional Information

- Operating System: linux
- Theia Version: 1.13.0

**Comment by msujew** [comment]
I can confirm that this issue is still present on `master`. I tested it by using a 10MB zip file. Deleting the file from the file system allows to load the application again.

> I find that the error is reported here. Does the judgment of object equality need to be modified?

This error is independent of this bug and appears even if the workspace successfully opens.

**Comment by colin-grant-work** [comment]
I have done some testing, and I'm fairly confident that the problem is that when we try to restore the editor targeting the binary file, we trigger this dialog:

https://github.com/eclipse-theia/theia/blob/b3a5aab829e68ba7ebbe35db2f72bdb80973c488/packages/filesystem/src/browser/file-resource.ts#L328-L336

But we do so before the shell is revealed, so the user can't respond to the dialog, and the application gets stuck.
