### ISSUE TITLE
monaco: fuzzy matching no longer works

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9851]
#### Bug Description:

Following https://github.com/eclipse-theia/theia/pull/9154, `fuzzy` searching is broken in the `quick-input` or `quick-service`.

#### Steps to Reproduce:

1. start the application with `theia` as a workspace folder.
2. use <kbd>F1</kbd> to trigger the quick-commands
3. search for `ag` - notice that only results that have exactly `ag` as a substring are present.

https://user-images.githubusercontent.com/40359487/128385633-4670b9a4-b55b-4314-bfa6-08afae32c919.mp4

The following is valid with fuzzy:

```
C(a)lls: Show Out(g)oing Calls
```

**Comment by vince-fugnitto** [comment]
The `fuzzy` searching works properly by default (verified in the [playground](https://microsoft.github.io/monaco-editor/playground.html)) so something seems wrong with the upgrade.

**Comment by EstherPerelman** [comment]
Hi @vince-fugnitto, may I ask you (as you authored #9928)  to update the [`filterItems`](https://github.com/EstherPerelman/theia/blob/4924bc753539d42608e086e56ba0cc728b777abd/packages/core/src/browser/quick-input/quick-input-service.ts#L226) function to fix the next problem (focus on the bold letters),
this causes the search order to be unsorted because it put down items that need to be upper:
on theia:
![theia run](https://user-images.githubusercontent.com/71729183/143855080-ccbbb079-afcc-48b8-bd9e-fb6433134bfd.png)

on vscode:
![vscode run](https://user-images.githubusercontent.com/71729183/143855087-36d830e1-6643-4316-9422-1f9f3a08bd2b.png)

**Comment by vince-fugnitto** [comment]
> may I ask you (as you authored #9928) to update the filterItems function to fix the next problem (focus on the bold letters).

@EstherPerelman I don't plan on revisiting the search at this time, if you have an improvement then please go ahead. The use-case you described is also not so critical, the result still displays it is just that fuzzy matching is more eager than matching the whole word, and results are still sorted (alphabetically).

> this causes the search order to be unsorted because it put down items that need to be upper.

The search order for commands is always alphabetical, the fuzzy just helps us match results.
