### ISSUE TITLE
support vscode-jupyter extension

### ISSUE THREAD

**Issue by tianhaoyang** [eclipse-theia/theia#9867]
Currently theia supports vscode-python extension, which is a basic notebook-like python execution UI. However, a brand-new jupyter extension [vscode-jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) has been released recently, which is much more powerful and user-friendly. Can theia support this?

**Comment by msujew** [comment]
Hi @tianhaoyang. I'll have to disappoint you there, the new Notebook API is not supported by Theia. As it's quite large - I looked into it a few weeks ago while it was still in a proposal state - with around 30k LOC, I don't expect Theia to support it in the near future.

Regarding support for it, while a lot of stuff can be simply copied from vscode's repo, the whole rendering and glue code will have to be rewritten to accommodate Theia's architecture. That'll be quite a large undertaking. Though, I won't stop anyone from trying it ;)

**Comment by vince-fugnitto** [comment]
Please also note that it is possible that `ms-toolsai.jupyter` is in fact proprietary, or uses proprietary dependencies which will not make it available to be published to `open-vsx` and may cause legal issues when consumed by non-vscode products:

- https://github.com/theia-ide/theia-apps/issues/441#issuecomment-772842409
- https://github.com/theia-ide/theia-apps/issues/485#issuecomment-890134143

**Comment by tianhaoyang** [comment]
@msujew @vince-fugnitto Thank you for your response. If you have any updates on this issue, please notify me. BTW, 
@msujew do you have any tips for rewriting the Notebook API to accommodate Theia's arch?

**Comment by msujew** [comment]
@tianhaoyang Not really tips, just general differences between Theia and vscode. Generally, I don't think it's too difficult to rewrite, but just a rather long process due to the amount of code:

* Theia is using React for rendering, while vscode uses their custom DOM rendering API. (which you can find [here](https://github.com/microsoft/vscode/tree/main/src/vs/base/browser)) This in turn requires us to rewrite the whole rendering code.
* Theia is using inversify for dependency injection, vscode (again) uses its own implementation. This shouldn't be too hard to rewrite, it's just a lot of code. Probably not all vscode services match 100% with Theia's services, which could make this task a bit harder.

**Comment by tsmaeder** [comment]
@msujew there used to be a jupyter plugin that was based on a custom editor. I was under the impression that they basically moved that inside the VS Code base. Maybe that is an easier starting point?

**Comment by msujew** [comment]
@tsmaeder Mostly, yes. AFAIK previous versions of the jupyter extensions used a custom editor, which used the normal custom editor API. The basic architecture (notebooks, notebook serialization, notebook rendering) is quite similiar between the internals of the old jupyter extension and the new vscode native implementation. Nevertheless, the native implementation is way faster (beside having a better UI). So I can imagine they changed quite a lot.

The old custom editor based jupyter extension is working btw inside Theia (although not flawlessly) see the python extension 2020.10 version.

**Comment by tsmaeder** [comment]
Here's what you get installed when you install the `ms-python` extension from open-vsx:

https://files.slack.com/files-pri/T04MJ6NNU-F05A89YTELT/image.png

**Comment by tsmaeder** [comment]
The ms-python extension declares an "extensionPack" with the ms-toolsai/jupyter extension. This extensions than declares an extension pack like so:
```
"extensionPack": [
        "ms-toolsai.jupyter-keymap",
        "ms-toolsai.jupyter-renderers",
        "ms-toolsai.vscode-jupyter-slideshow",
        "ms-toolsai.vscode-jupyter-cell-tags"
    ],
```

**Comment by tsmaeder** [comment]
the `jupyter-renderers` extension contributes a renderer for https://github.com/jupyter-widgets/ipywidgets. I would expect this is required to show many notebooks.

**Comment by tsmaeder** [comment]
`ms-toolsai.jupyter-keymap` just adds keybindings, so should have no problems.

**Comment by tsmaeder** [comment]
`ms-toolsai.vscode-jupyter-cell-tags` adds support for manipulation metadata tags on cells. Not needed at first, IMO.

**Comment by tsmaeder** [comment]
As mentioned in https://github.com/eclipse-theia/theia/pull/12442#issuecomment-1549103779 etc., in order to use python notebooks in a way we consider reasonable for a MVP would require us to 

* implement cell execution
* implement custom notebook renderers (including support for interactive renderer through messaging)
* Reasonable cell editing experience, not part of this for a MVP is (IMO)
   * Drag & Drop of cells
   * Notebook & cell toolbars (can be done via menu/command palette) as a workaround
   * Performance improvements beyond for large files
* Sundries, like stubbing any "proposed" API not needed for starting the python

**Comment by tsmaeder** [comment]
Note that the jupyter extension uses a largish list of "proposed" apis:
```
        "notebookDeprecated",
        "notebookMessaging",
        "notebookMime",
        "notebookCellExecutionState",
        "portsAttributes",
        "quickPickSortByLabel",
        "notebookKernelSource",
        "interactiveWindow",
        "notebookControllerAffinityHidden",
        "quickPickItemTooltip"
```,

but unless we analyze the use of those API's in the extensions source code, it's hard to judge which ones need a real implementation until we can actually _run_ jupyter notebooks. For that, we'll need the above list of features.

**Comment by msujew** [comment]
We have implemented a bunch of the proposed APIs in the recent months and the vscode-jupyter extension is now running fairly stable. Closing the issue.
